"bank"
"complete job"
"bookstore"
"fast food restaurant"
"midwest"
"great britain"
"mexico"
"pass water"
"literacy"
"cry"
"pants"
"take time"
"farm house"
"lots of attention"
"being entertained"
"people"
"stay in bed"
"puncture wound"
"two eyes"
"classroom"
"carpet"
"inspiration"
"indestructible"
"rest area"
"stupid"
"offspring"
"barn"
"new perspective"
"new job"
"crime"
"eat"
"library"
"dawdle"
"get in line"
"satisfaction"
"ignition switch"
"A) beat, B) direct traffic, C) city, D) street, E) president"
"refrigerator"
"puddle"
"A) facade"
"rock"
"pay bills"
"newspaper"
"wall"
"broken law"
"being employed"
"get money"
"violin case"
"library"
"A) fish market, B) pet shop, C) fishmongers, D) intertidal zone, E) obesity"
"on planet earth"
"a seizure"
"momentum"
"fall down"
"get tired of"
"classroom"
"california"
"friend's house"
"bland"
"go somewhere"
"new york city"
"hell"
"bodies of water"
"tree"
"state park"
"friends house"
"not"
"department store"
"school"
"europe"
"bored"
"school"
"play with toys"
"chess game"
"popular in america"
"A) irritability, B) depression, C) getting out of bed, D) happiness, E) discomfort"
"cage"
"A) bell cat, B) bush, C) attic, D) countryside, E) laboratory"
"choice"
"go to jail"
"walk"
"construction site"
"supply food"
"piggy bank"
"stew pot"
"sick person"
"A) cooking"
"knowledge"
"african continent"
"rest"
"vomit"
"stairwell"
"wash dishes"
"music store"
"new york city"
"not understand"
"A) happiness, B) stress relief, C) pleasure, D) ocean, E) may laugh, s>"
"productive"
"keep things"
"resort"
"rich person"
"barges"
"open mind"
"share files"
"getting hurt"
"damaged"
"coastal cities"
"family tree"
"universe"
"becoming tired"
"fall asleep"
"A) commercial building, B) old movie, C) small neighborhood, D) past, E) mall"
"attic"
"agitate"
"A) car, B) house, C) offices, D) park, E) movie theatre"
"orchestra"
"sail boat"
"bus stop"
"lots of space"
"bookstore"
"hockey game"
"detestable, C) effusive, D) enabled, E) apathetic"
"students"
"s>"
"mars"
"were thirsty"
"apply for job"
"floor"
"complete collection"
"apartment building"
"injury"
"television"
"testify"
"satisfaction"
"get tired, D) gain ground, E) trip over"
"west virginia"
"horror"
"perjury"
"tears"
"countryside"
"resistance"
"time test"
"outsider"
"closed room"
"A) manual, B) process information, C) power down, D) control model, E) reason exists, s>"
"bank machine"
"wash your clothes"
"motion"
"comfortable clothes"
"patience"
"satisfaction"
"feminism"
"church"
"have a friend"
"bodybuilder"
"roots"
"boredom"
"rock"
"not_duplicate"
"forget"
"every house"
"military base"
"church"
"brooklyn"
"music store"
"living room"
"spinal injuries"
"pet store"
"end of line"
"completing"
"quality"
"pass time, D) have fun, E) interesting"
"strip mall"
"butcher shop"
"A) zoo, B) pan, C) bowl, D) kitchen, E) spoon"
"learn to walk"
"branch out"
"mortal"
"wasting time"
"broken jaw"
"orchestra"
"ground"
"zoos"
"children's story"
"outside"
"A) need to, B) hungry, C) feel more energetic, D) weak, E) regenerate"
"falling down"
"thailand"
"A) tropical jungle, B) manual, C) work, D) transit, E) countryside"
"club"
"lawn"
"facebook"
"last several years"
"read"
"cost money"
"united states"
"reduce"
"slow down, B) crash, C) speed up, D) land, E) carry people"
"cause suffering"
"sick"
"museum"
"the backside"
"strong feelings"
"A) sky, B) house, C) lamp, D) match, E) candle"
"look angry"
"blind person"
"quarries"
"painting"
"welcome guests"
"overconfidence"
"compliance"
"s>"
"restaurant"
"police station"
"fiddle"
"watch film"
"chicken"
"work"
"digesting"
"go broke"
"department store"
"acting"
"head north"
"dustbin"
"A) boiling water, B) paper bag, C) restaurants, D) underground, E) cupboard"
"imagination"
"zoos"
"sometimes bad, B) happy, C) respiration, D) growing older, E) death"
"relaxation"
"A) dining room, B) conference, C) kitchen, D) in a lake, E) demonstration"
"free money"
"yawn"
"classroom"
"tanned, B) wet, C) wide, D) very deep, E) fish, s>"
"collapsed"
"turn inside out"
"downtown"
"concert venue"
"classroom"
"valley"
"A) forest, B) bathroom, C) windowsill, D) countryside, E) cage"
"have fun"
"unpleasant things"
"bone"
"man suit"
"part of his brain was"
"suicide"
"wellness"
"A) triangle"
"intertidal zone"
"pollution"
"play cards, B) skateboard, C) meet interesting people, D) listen to music, E) go to a concert"
"underground"
"bathroom"
"frying pan"
"ore"
"happy"
"personal cleanliness"
"A) pleasure, B) detachment, C) exercise, D) bankruptcy, E) fights"
"much money"
"airport"
"bathroom"
"national park"
"release energy"
"new york city"
"A) bar, B) friend's house, C) desktop, D) party, E) office"
"television"
"studying"
"set table"
"suffering"
"sweat"
"A) summarize main points, B) close mouth, C) write down, D) may disagree, E) talk, s>"
"use paper"
"judge people"
"boredom"
"tetrahedron"
"fuel"
"read"
"communication"
"son's room"
"each city"
"cash register, B) desk drawer, C) fish tank, D) bank, E) pay envelope"
"pleasure"
"race track"
"having fun"
"listen to music"
"A) table"
"insubstantial"
"street"
"paralysis"
"when communicating with my boss what should i do Options: A) misunderstandings, B) transfer of information, C) learning, D) confusion, E) silence"
"market"
"talk to each other"
"marine museum"
"running out of money"
"avoid pain"
"cabinet"
"A) freezer, B) store"
"act responsibly"
"casino"
"have money"
"washington d.c"
"bus depot"
"Joe"
"shopping mall"
"english alphabet"
"current"
"A) microphone, B) arena"
"A) counter, B) coffee table, C) school room, D) backpack, E) bedside table"
"very entertaining"
"chicago"
"safety"
"hen house, B) burrow, C) california, D) england, E) mountains"
"talk to each other, D) smoke pot,"
"back of house"
"wishing well"
"typhoon"
"place of work"
"new jersey"
"satisfaction"
"work"
"store"
"we all"
"falling asleep"
"shelf"
"nuclear weapons"
"study"
"A) night sky, B) galaxy, C) outer space, D) hollywood, E) eat cake, s>"
"high school band"
"start reproduction"
"not_duplicate"
"sewing room"
"oversupply"
"knee injury"
"bus stop, B) library, C) motel, D) airport"
"hospital"
"write will"
"massachusetts"
"getting tired"
"getting wet"
"listening"
"appear beautiful"
"desktop"
"arid regions"
"hand"
"go faster"
"talk to people"
"decay"
"unique personality"
"ask questions"
"department store"
"look around"
"melted"
"A) drawer, B) shelf, C) pantry, D) apartment, E) cabinet"
"forest"
"reading"
"A) desk drawer, B) office building, C) manual, D) office supply store, E) desktop, s>"
"airplane"
"toy box"
"airport"
"vase"
"bridge"
"keg"
"nigeria"
"accidents"
"A) cruise ship, B) home, C) mall, D) restaurant"
"joy"
"head injuries"
"not_duplicate"
"pet shop"
"movie"
"divorce"
"one moon"
"lobby"
"neighbor's house"
"change of heart"
"laziness"
"distant"
"A) table"
"full"
"relaxation"
"compact"
"michigan"
"rest"
"map"
"front door"
"hungry"
"marching band"
"china town"
"mammals"
"england"
"field"
"refrigerators"
"nightmare"
"new friends"
"pedalling"
"own home"
"organ"
"run away"
"rough"
"neighbor's house"
"eventually die"
"moon"
"building"
"doing nothing"
"A) cupboard, B) mail box, D) garage, s>"
"plan revenge"
"work"
"overpriced"
"nursery"
"shine brightly"
"wonderful"
"A) hear news, B) analyse, C) go somewhere, D) examine thing, E) see favorite show"
"A) apartment"
"detention"
"clothing store"
"air"
"manhattan"
"coffee shop"
"funeral"
"city"
"hardware store"
"touch everything"
"fraternity house"
"get away from"
"stagnation"
"A) mall, B) grocery store, C) grocery store, D) shop, E) supermarket"
"fridge"
"illusion"
"case"
"falling asleep"
"eastern hemisphere"
"stretches"
"caged in"
"british columbia"
"not_duplicate"
"press coverage"
"basement"
"mall"
"halloween"
"family tree"
"unnecessary"
"pencil case"
"thundershock"
"handshake"
"truck stop"
"fishing boat"
"exchanging ideas"
"A) floor"
"substation"
"freeway"
"movie"
"feel guilty"
"A) kitchen"
"building"
"learning about world"
"A) certificate, B) phone book, C) lineup, E) roster"
"procrastinate"
"walk"
"suburbs"
"capitol building"
"matrimony"
"run away"
"begin work"
"outside bedroom window"
"tall building"
"decomposition"
"yellow pages"
"purse"
"photograph"
"neighbor's house"
"department store"
"partner"
"count to ten"
"eye contact"
"bible"
"stairwell"
"open doors"
"make money"
"tennessee"
"A) loft, B) attic, C) bell cat, D) countryside, E) laboratory"
"getting in shape"
"internet"
"rebirth"
"clam chowder"
"potential"
"practice"
"below"
"backpack"
"living room"
"fall down"
"A) table, B) disneyland, C) refrigerators, D) pantry, E) shop"
"lie to himself"
"dairy farm"
"wealth"
"graduated"
"A) ocean"
"bus station"
"A) desert, B) hole, C) india, D) cage, E) rain forest"
"rug"
"not_duplicate"
"greater mobility"
"friend's house, B) university"
"sea plant"
"A) oven, B) freezer, C) plate, D) tupperware, E) grill"
"A) closet, B) under the bed, C) television, D) attic, E) most buildings, s>"
"animal"
"bookstore"
"sporting event"
"california"
"profane"
"smile"
"A) municipal park"
"housing estate"
"building"
"get lost"
"A) texas"
"conference"
"boredom"
"orchestra"
"call each other"
"desire to win"
"court room"
"standing in line"
"transporting"
"lay in bed"
"kettlebell"
"A) library, B) health department, C) mail box, D) drawer, E) bookstore"
"drink beer, E) sit quietly, s>"
"A) bookstore, B) library, C) electrical circuit, D) cabinet"
"fast food restaurant"
"desk drawer"
"past"
"A) mountainous area, B) wood pile, C) jungle, D) petting zoo, E) animals"
"A) set table, B) think, C) read books, D) play games, E) lie"
"listen to music"
"music store"
"concert hall"
"pool of blood"
"money"
"kitchen"
"san francisco"
"office"
"painting his nails, B) playing marbles, C) constructing, D) need for rest, E) wild ride, s>"
"helping others"
"heaven"
"gain weight"
"A) refrigerator, B) bookstore, C) cupboard, D) school building, E) wardrobe"
"garage"
"A) ice pack, B) freezer, C) laboratory, D) warehouse, E) refrigerator"
"big city, B) town, C) small town, D) canada, E) yellow pages, s>"
"baseball stadium"
"arena"
"art supplies"
"listen to music"
"food poisoning"
"electrolytic cell"
"country"
"answer question, B) learn language, C) do mathematics, D) be able to count, E) begin to study"
"multiplication"
"library"
"fatigue"
"thirsty"
"silent"
"america"
"tie around, B) wind around, C) weave, D) stringbed, E) ball up, s>"
"A) tomb"
"fridge"
"build trust"
"dresser drawers"
"jump to conclusions"
"human experience"
"eat"
"write"
"gain weight"
"old person"
"marching band"
"losing"
"A) cheat, B) fair, C) in competition, D) practice, E) sabotage,"
"jean"
"library"
"file cabinet"
"take several forms"
"sore muscles"
"lose money"
"lose weight"
"slender"
"school"
"heat"
"europe"
"woodland, D) ocean, E) cafe"
"A) cabin in the woods, B) california, C) front yard, D) conservatory, E) tropical forest"
"court room"
"street, B) tropical forest, C) garden of eden, D) new mexico, E) white house"
"waterfall"
"medicine cabinet"
"library"
"exercise"
"water fountain"
"calm"
"with brush"
"bathroom"
"library of congress"
"open field"
"defeat"
"s>"
"air conditioning"
"kitchen cupboard"
"A) shelter, B) floor, C) warm place, D) farmhouse, E) living room"
"china"
"living room"
"A) luggage store"
"trust"
"commute"
"to see the fish"
"owner"
"plant seeds"
"thin out"
"losing money"
"s>"
"water plants"
"tampa"
"A) synagogue"
"headache"
"cave"
"crime scene"
"pay debts"
"street corner"
"floors"
"warm coat"
"enlightenment"
"being entertained"
"ulcers"
"s>"
"fridge"
"stress"
"deceitful"
"problems"
"organization"
"say words"
"england"
"toy store"
"hardware store"
"being happy"
"water cooler"
"jar"
"lazy"
"straightforward, B) serious, C) solemn, D) somber, E) funny"
"home, B) library, C) stationery store"
"A) furniture store"
"s>"
"fights"
"amusement park"
"boredom"
"web page"
"bus depot"
"strange"
"writing down"
"fish market"
"neck"
"everything"
"ample"
"A) shop, B) mall"
"last several years"
"caregiver"
"bar"
"library"
"farmland"
"talking loudly"
"forest"
"body of water"
"gain weight"
"listen to radio"
"vegas"
"mexica"
"farmer's market"
"london"
"viking ship"
"human body"
"english house"
"A) appliance store"
"A) istanbul, B) concert, C) bedroom, D) antique shop, E) human being"
"get arrested"
"vancouver island"
"make larger"
"s>"
"back yard"
"tear down"
"kennel"
"control children"
"bluegrass music"
"paid for"
"attract attention"
"europe"
"practice"
"attack"
"mill"
"airport"
"drawer"
"A) laughter, B) sweating, C) embarrassed, D) breathing heavily, E) tiredness"
"action"
"grocery shop"
"not_duplicate"
"breathlessness"
"s>"
"university campus"
"locomotion"
"united states"
"desk drawer"
"have sex, C) kiss, D) flirting, E) going on a date,"
"play sports"
"jar"
"dishwasher"
"headphones"
"because of his anger"
"jerusalem"
"washington state"
"sporting goods store"
"feed themselves"
"cool house"
"closed eyes"
"office building"
"ringmaster"
"A) theater, B) floors, C) concert hall, D) education, E) school"
"A) sleep"
"living room"
"supermarket door"
"cabinet"
"beach"
"captivity"
"depress"
"fish department"
"A) bedroom, B) table, C) wheel barrow, D) building, E) office"
"bowls"
"s>"
"get frustrated"
"heat"
"theatre"
"A) gear shift, B) garage, C) kitchen, D) jewelry store, E) hardware store"
"A) roots"
"shady places"
"parents"
"hug"
"garage"
"nuclear plant"
"plate"
"theater"
"mail property tax payments"
"country"
"furniture store"
"neighborhood"
"adriatic sea, B) medinean sea, C) hand, D) see, E) atlantic ocean"
"bookcase"
"being arrested"
"jungle"
"skyscraper"
"church"
"A) microscope, B) abbreviate, C) glasses, D) camera, E) telescope"
"newsstand"
"lumberyard"
"hell"
"frostbite"
"many words"
"fresh cake"
"afterword"
"twenty four"
"both positive and negative, B) unknowable, C) important to people, D) ocean, E) confusing"
"effort"
"man crew"
"fast food"
"street"
"email"
"cling film"
"rocky hills"
"chemistry lab"
"market"
"A) box, B) grocery store"
"bug campers"
"swarm"
"cast iron stomach"
"sporting goods store"
"jewelry store"
"slowly"
"bankruptcy"
"hardware store"
"ridiculous"
"gulf states"
"dishwasher"
"bank"
"cellar"
"ask questions"
"end of line"
"balloon"
"grocery store"
"fall asleep"
"bathhouse"
"A) flower pot, B) shelf, C) windowsill, D) outside, E) sill"
"phoenix"
"brownstone"
"less dense than water"
"death"
"small town"
"encyclopedia"
"jogging"
"automobile accidents"
"supermarket"
"isolation, B) grief, C) happiness, D) relief, E) angry"
"panic"
"bus stop"
"walked"
"beach"
"pretty smart, B) singing, C) dark, D) very colorful, E) light, s>"
"viking ship"
"diminishment"
"warm up"
"effectively treated"
"butterflies"
"go to jail"
"process information"
"toxic"
"anxiety"
"valley"
"florida keys"
"A) suitcase"
"convenience store"
"go down"
"bookcase"
"laughter"
"headache"
"battleship"
"defecating"
"restaurant"
"phone book"
"A) computer network, B) electrical circuit, C) lineage, D) company, E) wall"
"care"
"go to movies"
"daydream, B) headache, C) get ideas, D) sleep, E) become distracted"
"checkers"
"care less"
"announce"
"crooked"
"dirt"
"outside, C) well, D) garden shed, E) garage"
"go to bed"
"office building"
"s>"
"make"
"fighting"
"stationery store"
"get answers"
"A) toolbox"
"everglades"
"city or town"
"A) grocery store, B) antique shop, C) house, D) dark place, E) street"
"beat"
"being raped"
"buy food"
"buildings"
"write will"
"A) briefcase, B) desk drawer, C) friend's house, D) pocket, E) sidewalk"
"heat"
"not_duplicate"
"A) microwave, B) desktop, C) shelf, D) art show, E) wall"
"balance"
"service station"
"receiving"
"end of line"
"stretch"
"fart"
"music store"
"chemistry lab"
"book of stories"
"farmer's market"
"unable to work"
"hopping"
"fly"
"movie"
"hope for peace"
"A) building, B) business district, C) above ground, D) most towns, E) center of town, s>"
"forest"
"amazon river"
"make food"
"surface of earth"
"A) closet"
"common interests"
"inner ear, D) nasal cavity, E) autistic"
"confession"
"asking you're a child answering questions"
"illness"
"music room"
"passed"
"A) cleanness"
"basketball"
"drunk driving"
"department store"
"wisdom"
"play hockey"
"clutter"
"gain confidence, B) concentrate, C) get attention, D) pay attention, E) stop talking, s>"
"headache"
"large building"
"state park"
"on sidewalks"
"abandon"
"stall"
"solid object"
"newspapers"
"A) nursery, B) south pacific, C) desert, D) sea water, E) atlantic ocean"
"big city"
"see art"
"tennis court"
"coffee shop"
"bird's nest"
"inappropriate"
"country club"
"bite"
"A) corner"
"judge feelings"
"valley"
"A) motel room, B) apartment, C) bathroom, D) games, E) house, s>"
"make person sick"
"intellectual challenge"
"toaster"
"boredom"
"bath store"
"the person in the cat, trying to kill him, did what?"
"state park"
"state"
"A) person, B) hamper, C) upstairs, D) backpack"
"bloom"
"shore line"
"study french cooking"
"one choice for pet"
"full sunlight"
"neatness, B) tiredness, C) order, D) exhaustion, E) sneezing,"
"plan"
"orbits"
"dirty"
"euthanasia"
"headache"
"floor"
"garage"
"newspaper"
"A) kill each other, B) thank god, C) experience pain, D) hatred, E) talk to each other"
"japan"
"packaging materials"
"false information"
"patience"
"out of pocket"
"parents"
"brother's house"
"concentration"
"discomfort"
"typewriter"
"school"
"living room"
"A) desk drawer, B) cabinet, C) purse, D) classroom, E) pocket"
"crowd"
"incarceration"
"supermarket"
"kill animals"
"liquor store"
"atlas"
"teach courses"
"bowling alley"
"using water"
"spittle"
"parking garage"
"you're into"
"frustration"
"sand trap"
"not_duplicate"
"newspaper"
"wash themselves"
"work"
"eat every day"
"prisoner"
"go somewhere"
"refrigerator"
"restaurant"
"face problems"
"underpass"
"first class"
"A) seeing bear, B) see beautiful views, C) get wet, D) getting lost, E) murdered by a landshark"
"need for food"
"man made"
"snowflake"
"louisiana"
"your body"
"research laboratory"
"run"
"solar system"
"A) pantry, B) store, C) gas, D) liquid, E) garage"
"friend's house"
"A) upstairs, B) aloft, C) diagonal, D) upstream, E) upwards"
"feeling happy"
"A) envy, B) jealousy, C) education, D) fear, E) excitement"
"floor"
"make pretty"
"unbalanced"
"financial security"
"prosecution"
"mad cow disease"
"A) water"
"trust himself"
"not_duplicate"
"satisfaction"
"farmer's market"
"A) sailboat"
"money"
"bird's nest"
"confidence"
"A) desert, B) college campus, C) recreational center, D) athletic club, E) park"
"water fountain"
"friend's house"
"ladder"
"body of water"
"electric motor"
"table"
"kitchen cupboard"
"cash drawer, B) teh bank, C) safety deposit box, D) pocket, E) piggy bank"
"kitchen"
"car"
"thrift store"
"cupboard"
"become disillusioned"
"mountain"
"theater"
"A) beach, B) city hall, C) closet, D) garage, E) school"
"calluses"
"trouble"
"loser"
"sore muscles"
"restaurant"
"milwaukee"
"fridge"
"spend money"
"shelf"
"make more money"
"losing weight"
"impossibility"
"A) california, B) tokio, C) downtown, D) narnia, E) large town"
"repetition"
"pain"
"zoo"
"go out to play"
"very loyal"
"bicycle shop"
"space"
"supermarket"
"lion"
"fight enemy"
"shoot"
"work room"
"cabinet"
"painful"
"A) backpack, B) bank, C) desk drawer, D) eat cake, E) office desk"
"help"
"city"
"laboratory"
"cool off"
"music class"
"first turn on power"
"regular poker game"
"start fighting"
"drunker"
"petrify"
"minister"
"cast shadow"
"road rage"
"unhealthy"
"A) three vertices, B) point, C) 3 sides, D) three sides, E) math book, s>"
"exit ramp"
"bad dreams"
"annoyance"
"enemies"
"eating food"
"show"
"mall"
"babies"
"orbit"
"sharing of ideas"
"anger"
"differently"
"marine museum"
"supermarket"
"fall down"
"music store"
"mentally challenged"
"learning"
"feelings of guilt, B) prison sentence"
"laughter"
"beach"
"high school"
"ignorance"
"work out"
"you?"
"sell products"
"feel better"
"bus depot"
"lie"
"dictionary"
"economic boom"
"university"
"bones"
"daydreams"
"michigan"
"market"
"desire to travel"
"trunk"
"manhattan"
"fly"
"deadworks"
"hallway"
"skate"
"old barn"
"A) forest, B) nest, C) roof, D) leaves, E) sky"
"eat hamburger"
"write down"
"afraid of"
"interesting"
"nausea"
"A) opera house, B) school band, C) music store, D) orchestra"
"lot of"
"tarnish"
"stock certificate"
"silence"
"trunk"
"A) diverse, B) round, C) square, D) orange, E) complicated"
"A) big house, B) train, C) cabin, D) living room"
"dog's mouth"
"new york city"
"buy food"
"happiness"
"laughter"
"rug"
"born again"
"A) wipe out"
"install"
"prehistoric times"
"remorse"
"A) die"
"joy"
"show appreciation"
"state park"
"state fair"
"A) cloud, B) snow storm, C) billow, D) air, E) snowstorm"
"basement"
"stress"
"corn fields"
"pond"
"exhausting"
"balkan peninsula"
"A) supermarket"
"watching television"
"maryland"
"outdoors"
"citrus"
"passing out, C) death, D) drunk, E) exhaustion"
"death"
"stay in bed"
"skin irritation"
"A) cinema"
"music store"
"overcast"
"reasonable"
"bridge"
"sad"
"finishing her homework"
"A) clerk, B) indoors, C) movie theater, D) venue, E) auditorium"
"america"
"river bed"
"neighbor's house"
"infinite"
"universe"
"false information"
"see particular program, B) see exhibits, C) see people play game, D) have conversation, E) watch film"
"medicine cabinet"
"done"
"university"
"s>"
"A) offer"
"computer"
"mountains"
"middle ages"
"library"
"cigarette, D) lighter fluid."
"lose"
"taxi"
"lack of fuel"
"gas"
"making money"
"buy tickets"
"fair"
"A) drawer"
"reckless"
"basement"
"downtown"
"knowledge"
"talk with people"
"lie"
"stock market"
"ecology"
"container"
"heartburn"
"do time"
"being prepared"
"forest"
"kew gardens"
"garden center"
"feel important, B) trust himself, C) own house, D) electrical circuit, E) know what time, s>"
"sharp claws"
"apartment building"
"outside"
"eddie bauer"
"winery"
"grab"
"hardware store"
"coma"
"new construction"
"computer hard drive"
