"A) bank, B) library, C) department store, D) mall, E) new york"
"Complete job"
"A) doctor, B) bookstore, C) market, D) train station, E) mortuary"
"A) fast food restaurant, B) pizza, C) ground up dead cows, D) mouth, E) cow carcus,"
"Midwest, B) countryside, C) estate, D) farming areas, E) illinois, F) southeastern states"
"Great britain"
"mexico"
"Procreate"
"Reading newspaper one of many ways to practice your what?"
"A) cry, B) hear sounds, C) singing, D) arthritis, E) making music"
"Vinyl is a strange thing to replace?"
"Options"
"A) farm house, B) barnyard, C) stockyard, D) slaughter house, E) eat cake,"
"A) bone, B) charm, C) petted, D) lots of attention, E) walked"
"Not_duplicate"
"People"
"Stay in bed, C) stop bicycle, D) examine thing, E) suicide"
"A fencing thrust with a sharp sword towards a person would result in what?"
"Two eyes"
"In which drawer do adults use glue sticks?"
"A) lumberyard, B) synagogue, C) floor, D) carpet, E) hardware store"
"The artist was sitting quietly pondering, then suddenly he began to paint when what struck him?"
"indestructible"
"A) rest area, B) school, C) stadium, D) apartment, E) hospital"
"clumsy, B) ineffectual, C) dull, D) clumsy, E) stupid"
"offspring"
"A) barn, B) public office, C) public office, D) out of doors, E) freezer"
"Blue read material outside of his comfort zone because he wanted to gain what?"
"new job"
"Lie"
"A) eat, B) hasten, C) antedate, D) bring forward, E) advance"
"A) library, B) subway station, C) county engineer's office, D) super market, E) home"
"Question"
"A) get in line, B) sing, C) stand in line, D) turn left, E) turn right"
"Answer"
"ignition switch"
"A) beat, B) direct traffic, C) city, D) street, E) president"
"Question:"
"A) whirlpool bath, B) coffee cup, C) cup, D) soft drink, E) puddle"
"A) facade, B) front door, C) doorway, D) entrance porch, E) hallway"
"Bob the lizard lives in a warm place with lots of water."
"August needed money because he was afraid that he'd be kicked out of his house"
"newspaper, D) online, E) manual"
"A) art show, B) wall, C) newspaper, D) car, E) table, F) car, G) car, H) car, I) car, J) car, K) car, L) car, D) newspaper, E) table,"
"James knew that he shouldn't have been buying beer for minors."
"A) anxiety and fear, B) increased workload, C) praise, D) less sleep, E) being employed"
"A) get money, B) have money, C) bring cash, D) go to market, E) bring cash,"
"John was first violin, so he had to bring something important to work every day."
"Library"
"A) fish market, B) pet shop, C) intertidal zone, D) intertidal zone, E) obesity"
"On planet earth, C) dress shop, D) school, E) train wreck, F) train wreck, G) train wreck, H) train wreck, I) train wreck,"
"A) slurred speech, B) slurred speech, C) death, D) forgetfulness, E) pass out,"
"Time"
"Fall down, B) breathe, C) play tag, D) be dismembered by a chainsaw, E) become adult"
"not_duplicate"
"A) movie theatre, B) bowling alley, C) factory, D) store, E) classroom"
"america"
"Question"
"A) bland, B) lifeless, C) sandy, D) neutral, E) freezing"
"Options"
"In my pocket, B) michigan, C) new york city, D) restaurant, E) public house"
"A) hell, B) school, C) indoors, D) internet cafe, E) house"
"A) maritime, B) bodies of water, C) saltwater, D) galapagos, E) fish market"
"In a jar, D) pet shops, E) tropical forest, F) feild, G) pet shops"
"State park"
"eat in restaurant, B) make bread, C) cook dinner, D) friends house, E) friends house, F) friends house, G) friends house, H) friends house, I) friends house,"
"Not_duplicate"
"A) bathtub, B) washing area, C) hotel, D) shower stall, E) department store, F) department store, G) department store, H) department store, I) department store, J) department store, K) department store,"
"A) school bus, B) boat, C) hospital, D) school, E) school, D) hospital, E) school, E) school, E) school, E) school, E) school, E) school, E) school, E) school, E) school, E) school, E) school, E) school, E) school, E) school, E) school, E) school, E) school, E) school, E) school, E) school, E) school,"
"europe"
"Bored"
"Sally used a clipboard to hold her papers while she read off names at the beginning of the day."
"Question"
"chess game"
"A) popular in america, B) full of air, C) gone, D) round"
"Question"
"A) cage, B) sky, C) countryside, D) desert, E) windowsill, F) cage, D) sky, E) desert, F) windowsill,"
"A) bell cat, B) bush, C) attic, D) countryside, E) laboratory"
"John felt that his actions were fate"
"A) go to jail, B) cry, C) find god, D) guilty conscience, E) problems"
"George didn't have a car, but he still had his two feet."
"A crane uses many a steel cable when working a"
"Answer"
"A) piggy bank, B) wallet, C) toy, D) ground, E) pocket"
"A) wharf, B) red lobster, C) tidepools, D) boss's office, E) stew pot"
"sick person"
"A) cooking, B) cook food, C) backpack, D) drawer, E) drawer, F) drawer, G) drawer, H) drawer, I) drawer, J) drawer, K) drawer, L) drawer, M) drawer, N) drawer, O) drawer, P) drawer, S) drawer, T) drawer,"
"Not a good idea, but it's a good idea to have a list of things you're remembering about, and then put them in a box to indicate which ones are most important to you."
"Amazon basin"
"James and Jennifer planned on going to bed early so that they could spend a long time doing what?"
"a) health, B) stagger, C) stagger, D) get arrested, E) vomit"
"stairwell"
"Question"
"symphony"
"A) urban area, B) metropolis, C) chicago, D) new york city, E) toronto"
"Answer"
"Billy set aside a block of time for having fun after work."
""
"Question"
"resort"
"rich person"
"A) michigan, B) amsterdam, C) venice, D) bridge, E) barges to travel on,"
"Open mind"
"Multitask"
"riot"
"Wet clothes"
"Not_duplicate"
"James's nice asked him about her grandfather."
"James looked up and saw the start twinkling in the black yonder"
"A) becoming tired, B) tennis elbow, C) exercise, D) hunger, E) victory"
"James found the sound relaxing."
"A) commercial building, B) small neighborhood, C) past, D) mall, E) past"
"Toy store, B) michigan, C) living room, D) attic, E) cupboard"
"James told his son to settle down and be careful."
"A) car, B) house, C) offices, D) park, E) movie theatre"
"orchestra"
"Sailors drive many different types of boats, what type of boat involves their namesake"
"A) bus stop, B) tunnel, C) synagogue, D) fairy tale, E) street corner"
"Question:"
"A) bookstore, B) classroom, C) discount store, D) school room, E) bedside table"
"Falcons vs the Jets"
"James noticed that his penis was bigger.."
"students"
"Coral sea, C) under water, D) flower bed, E) florida keys"
"A) outer space, B) weekly world news, C) roswell, D) universe, E) mars"
"a party, B) were thirsty, C) refreshment, D) getting drunk, E) celebrating"
"Answer"
"not_duplicate"
"A) complete collection, B) own house, C) procrastinate, D) explode, E) have to hold,"
"A) field, B) star can, C) city or town, D) apartment building, E) apartment building"
"A) sore muscles, B) errors, C) happiness, D) injury, E) fun,"
"Drive in movie, B) drive in movie, C) television, D) video store, E) show"
"The victim was to take stand today, they were going to do what?"
"A) cleanliness, B) mistakes, C) growth, D) satisfaction, E) late,"
"Question"
"West Virginia"
"A) horror, B) anxiety and fear, C) rejection, D) increased workload, E) being employed"
"committing perjury"
"A) tears, B) please, C) like, D) thank, E) make happy, F) make sad, G) make happy, H) make sad, I) make happy,"
"A) countryside, B) great plains, C) encyclopedia, D) jungle, E) north america, F) encyclopedia, D) jungle"
"not_duplicate"
"Question:"
"Sam was a stranger. Even so, Mark treated him like what?"
"Bob's only light source was a small bulb"
"James thought of criminal justice like a computer program. It need to work right."
"A) ticket machine, B) bank machine, C) telephone, D) automated teller, E) automated teller"
"Wash your clothes, B) practice, C) take off uniform, D) stretch, E) practice, D) practice, E) practice, D) practice, E) practice, E) practice, E) practice, E) practice, E) practice, E) practice, E) practice, E) practice, E) practice, E) practice, E) practice, E) practice, E) practice, E) practice, E) practice, E) practice, E) practice, E) practice, E) practice, E) practice"
"A) motion, B) stretch, C) exercise, D) movement, E) muscles"
"ipod"
"A) falling down, B) literacy, C) buying, D) knowing how to read, E) patience"
"Answer"
"feminism"
"A) eat cake, B) closet, C) office building, D) own house, E) own house,"
"Learn how to, B) have a friend, C) knowledge, D) take class, E) have computer,"
"body of animal, B) arm, C) bodybuilder, D) body of dog, E) human body"
"Roots"
"Food, B) relaxation, C) killing, D) missing morning cartoons, E) boredom"
"A) backyard, B) rock, C) mine, D) cherry, E) peach"
"Question"
"I couldn't find anybody who recalled the event, what were they adroit at doing?"
"A) every house, B) every table, C) every restaurant, D) every restaurant, E) restaurant, F) restaurant, G) restaurant, H) restaurant, I) restaurant,"
"military base"
"A) bedroom, B) movie theater, C) bowling alley, D) church, E) office"
"A) brooklyn, B) subdivision, C) bricks, D) new york city, E)"
"Music class, B) college, C) music store, D) music room, E) music band"
"A) living room, B) parlor, C) furniture store, D) basement, E) kitchen"
"Pools are not only a source of water for children but also for adults and can be a source of serious injury to swimmers and their families"
"A) tropical forest, B) oregon, C) woods, D) pet store, E) louisiana"
"End of line, B) buildings, C) apartment, D) neighbor's house, E) address"
"Not a good idea to do a test or a test of your knowledge, but it is a good idea to do a test or a test of your knowledge."
"Question"
"Answer"
"A) strip mall, B) city or town, C) shoppingcentre, D) boutique, E) vermont"
"Bill puts meat on the scale, where does Bill work?"
"A) zoo, B) pan, C) bowl, D) kitchen, E) spoon"
"A) learn to walk, B) walk slowly, D) breathe, E) stand still"
"B) branch out, C) wear costume, D) pretend, E) sing songs"
"mortal"
"wasting time"
"Question"
"Orchestra"
"Answer"
"zoos"
"Children's story"
"A) outside, B) world, C) protection, D) colorado, E) america"
"A) need to, B) hungry, C) feel more energetic, D) weak, E) regenerate"
"A) falling down, B) sweating, C) exhaustion, D) getting tired, E) getting sick,"
"A) zoo, B) barrel, C) research laboratory, D) captivity, E) thailand"
"A) tropical jungle, B) manual, C) work, D) transit, E) countryside"
"A) club, B) assembly hall, C) meditation center, D) meeting, E) church"
"lawn"
"Answer"
"A) go fast, B) start running, C) look good, D) last several years, E) last several years,"
"Question"
"Cost money, B) slow down, C) move people, D) turn right, E) get girls"
"united states"
"Question"
"A) slow down, B) crash, C) speed up, D) land, E) carry people"
"A) recur, D) effectively treated, E) cause suffering"
"sick"
"A) museum, B) laboratory, D) library, E) industrial area"
"A) drawer, B) desk, C) the backside, D) office, E) measure distance,"
"A) strong feelings, B) herpes, C) shortness of breath, D) excitement, E) arousal"
"A) sky, B) house, C) lamp, D) match, E) candle"
"A) smell smoke, B) cry, C) bank savings, E) look angry"
"Blind person"
"A) quarries, B) field, C) park, D) bridge, E) made from rocks"
"A bald eagle is likely to be found on what kind of work?"
"Answer"
"A) overconfidence, B) effectiveness, C) knowing more, D) head grows larger, E) growth"
"A) compliance"
"Question"
"restaurant"
"A) police station, B) crime scene, C) restroom, D) drawer, E) holster"
"Fiddle"
"Question"
"A) feather"
"A) work, B) school building, C) paper, D) city, E) habit"
"Not hungry, C) gas, D) weight gain, E) feeling fullness,"
"Question"
"A) tin, B) department store, C) garden, D) small hole, E) cupboard"
"performing a type of?"
"The car was going from Alabama to New York, what was its goal?"
"Dustbin"
"A) boiling water, B) paper bag, C) restaurants, D) underground, E) cupboard"
"Writers with a great imagination can amass a large fortune?"
"zoos"
"Sometimes bad, B) happy, C) respiration, D) growing older, E) death"
"Relaxation, B) arthritis, C) adrenaline, D) your, E) sweater may produced,"
"A) dining room, B) conference, C) kitchen, D) in a lake, E) demonstration"
"A) candy, B) death and, C) free money, D) discount, E) credit"
"YAWN"
"A) classroom, B) outdoors, C) aquarium, D) north carolina, E) great britain"
"A) tanned, B) wet, C) wide, D) very deep, E) fish,"
"A) collapsed, B) full, D) stretchable, E) stretchable"
"a) turn inside out,"
"A) appear suddenly, B) appear suddenly, C) appear suddenly, D) bottom out, E) east"
"Question"
"year"
"A) forest, B) valley, C) outdoors, D) countryside, E) woods, F) wetlands, G) mountains, H) deserts, I) deserts,"
"A) forest, B) bathroom, C) windowsill, D) countryside, E) cage"
"Joe and Mac were playing basketball. They did it every day in their back yard."
"Nomads are people who have no home or car and who have no place to stay."
"A) a treat that you dog will enjoy?"
"Women used to be expected to wear a dress but it's now acceptable for them to wear what?"
"A) awake, B) repeat, C) sleeping, D) read aloud, E) concentrate"
"Not the answer"
"Healthy"
"A) triangle"
"Intertidal zone"
"A) say hello, B) wreak, C) pollution, D) smoke, E) relaxation"
"Question"
"A) boiling water, B) rocket ship, C) paper bag, D) underground"
"Bathroom"
"A) oil, B) freezer, C) ham sandwich, D) oven, E) frying pan"
"A) multivitamin, B) farm, C) michigan, D) earth, E) ore"
"A) happy, B) receiving money, C) spending money, D) selling out, E) selling out, F) selling out, G) selling out, H) selling out, I) selling out, J) selling out, K) selling out,"
"hydration, B) personal cleanliness, C) personal cleanliness, D) will drown, E) use of water"
"A) pleasure, B) exercise, C) bankruptcy, D) fights, E) fights"
"A) much money, B) own house, C) creativity, D) new car, E) caregiver"
"A) car, B) theatre, C) airport, D) hotel, E) disneyland"
"Question"
"A) south america, B) amazon basin, C) temperate zone, D) national park,"
"Question"
"new york city, B) subdivision, C) ring, D) hazleton, E) live in"
"A) bar, B) friend's house, C) desktop, D) office, E) office"
"A) books, B) dard, C) closed room, D) television"
"Question"
"Question"
"he was having a hard time expressing himself in a healthy way, the psychologist said he was mentally what?"
"A) tension, B) releases heat, C) winning or losing, D) sweat,"
"Question: How would you express information to a deaf person?"
"Not_duplicate"
"A) judge people, B) work miracles, C) judge men, D) everywhere, E) judge men"
"A) cooties, B) boredom, C) colds and flu, D) taking tests, E) taking tests"
"tetrahedron"
"Food, B) refrigerator, C) cargo ship, D) port, E) fuel"
"Answer"
"Communication"
"Question"
"each city, B) office building, C) a zoo, D) washington dc, E) washington dc"
"Answer"
"A) pleasure, B) owning, C) debt, D) spending money, E) smart, F) smart,"
"A) race track, B) fair, C) raised by humans, D) in a field, E) countryside"
"A) having fun, B) it's more relatable, C) learn new things, D) becoming absorbed, E) falling asleep"
"listen to music, B) watch television, C) making blankets, D) eat, E) watching tv"
"Question"
"Leo's 2000 dollar debt seemed what?"
"The man flew his airplane over the city and saw pollution visibly in the sky"
"A) fights, B) drunkenness, C) staggering, D) puke, E) paralysis"
"When communicating with my boss what should i do Options: A) misunderstandings, B) transfer of information, C) learning, D) confusion, E) silence"
"In a market where will you find fish?"
"Own land, B) own home, C) talk to each other, D) believe in god, E) spend time"
"Not a good idea to be outside during a shark filled tornado"
"Overstocking"
"Acceptance"
"A) ocean, B) water cooler, C) cabinet, D) dishwasher, E) dining room, F) ocean, G) ocean, H) ocean, I) ocean, J) ocean, K) ocean, L) ocean, D) ocean, E) dining room,"
"Answer"
"Question"
"Casino"
"Spend frivolously, D) fly in airplane, E) have money"
"Washington d.c."
"train station"
"Joe was hit by a ball and fell down."
"A) shopping mall, B) bedroom, D) laundromat, E) bathroom"
"A) syllable, B) post office, C) envelope, D) english alphabet, E) word"
"Current"
"A) microphone, B) radio station, C) radio station, D) trees, E) town"
"A) coffee table, B) school room, C) backpack, D) bedside table"
"Football"
"A) chicago"
"Not_duplicate"
"A) hen house, B) burrow, C) california, D) england, E) mountains"
"Question"
"roundabout"
"wishing well"
"typhoon"
"Place of work"
"A) maryland, B) indiana, C) on tv, D) park, E) new jersey"
"A) satisfaction, B) have fun, C) thrilling, D) made, E) smart,"
"Work, tacos, C) mass, D) wrestle, E) wrestle"
"Not_duplicate"
"We all have a choice of what to do, and we all have a choice of what to do."
"Question:"
"A) shelf, B) board, C) church, D) table, E) dark"
"cyanide"
"Study"
"A) night sky, B) galaxy, C) outer space, D) hollywood, E) eat cake,"
"band"
"Options A) expiration, B) growing older, C) sometimes bad, D) death, E) start reproduction"
"Question"
"A) sewing room, B) tailor shop, C) clothes store, D) cotton mill, E) cotton mill,"
"Oversupply"
"A) sweating, B) pain, C) medium, D) knee injury"
"A) bus stop, B) library, C) motel, D) airport, E) subway"
"For help, C) hospital, D) bus stop, E) building"
"write will"
"A) massachusetts, B) new england, C) my house, D) new jersey, E) connecticut"
"A) getting tired, B) working, C) procrastination, D) jumping, E) sitting down"
"The cat carefully navigated the area, they do everything they can to avoid what?"
"Listening is a very common activity in which someone is listening to someone else."
"appear beautiful, B) appear blue, C) shows a rainbow, D) rain water, E) cloud over"
"Question: Pens, computers, text books and paper clips can all be found where?"
"A) ball stopped, B) west texas, C) arid regions, D) garden, E) warm place"
"A) office building, B) school, C) courtroom, D) airport, E) hand,"
"he picked up his pace to a run, he wanted to do what?"
"Question"
"death and decay"
"Options"
"Question:"
"A) counter, B) train station, C) school room, D) desk, E) department store"
"A) interesting, B) look around, C) take pictures, D) change of surroundings, E) new experience"
"carved, B) melted, C) antarctica, D) antarctica, E) sculptured"
"A) drawer, B) shelf, C) pantry, D) apartment, E) cabinet"
"niagra falls, B) forest, C) waterfall, D) ground, E) tree"
"A) reading, B) meditate, C) fall asleep, D) bunk, E) think"
"Answer"
"A) in cinema, B) falling down, C) show, D) airplane"
"Toy box, B) movies, C) child's hand, D) toybos, E) child park"
"A) pocket, B) terrorists hands, C) airport, D) sea ship, E) briefcase"
"A) market, B) table, C) countryside, D) anthology, E) vase"
"A) waterfall, B) hatred, C) bridge, D) valley"
"Question"
"Gulf of Guinea"
"Answer"
"Restaurant"
"A) joy, D) afraid, E) terrible,"
"James was concerned about the consequences of many what?"
"Not_duplicate"
"A) desert country, B) dessert, C) pet shop, D) tropical areas, E) zoo,"
"A) guitar, B) music room, C) orchestra, D) case, E) movie"
"Question:"
"One moon, B) milky way, C) god's creation, D) stars, E) universe"
"Room service, B) church basement, C) lobby, D) large room, E) country club"
"A) refrigerator, B) friend's house, C) keg, D) neighbor's house, E) kitchen, F) keg, G) keg, H) keg, I) keg, J) keg, K) refrigerator, L) keg, D) neighbor's house, E) kitchen,"
"Change of heart, B) anguish, C) anger, D) boredom, E) anxiety"
"A) flatulence, B) happiness, C) laziness, D) fall asleep, E) comfort"
"Question"
"A) table, B) office, C) desk, D) kitchen, E) ocean"
"Question: If you stop and have food all around you, what are you?"
"Question"
"not_duplicate"
"Michigan"
"Not_duplicate"
"he opened the glove compartment and handed his passenger the what to navigate?"
"A) car stand, B) hotel, C) own home, D) front door, E) bus depot"
"A) litter tray, B) whiskers, C) hungry, D) feline, E) thirsty"
"A) symphony, B) concerto, C) choir, D) theater troupe, E) marching band"
"China town"
"Animals who have hair and don't lay eggs are what?"
"John was an aristocratic fox hunter."
"A) field, B) bathroom, C) michigan, D) minnesota, E) painting"
"A) shop, B) bookcase, C) shelf, D) refrigerators, E) kitchen"
"nightmare"
"A) getting drunk, B) making new friends, C) new contacts, D) doing drugs, E) set home"
"B) practice, B) sense of balance, C) driving, D) good balance, E) pedalling"
"Books and magazines, B) own home, C) kitchen, D) shelf, E) meeting"
"A) killing, B) office, D) terminal, E) organ"
"blunderbuss"
"A) rough, B) non smooth, C) uneven, D) plastic, E) bumpy"
"Options"
"A) death, B) flying, C) reproducing, D) food consumed, E) eventually die"
"Options"
"A) michigan, B) florida, C) wine, D) texas, E) building"
"Not a good idea"
"Question"
"Question"
"Answer"
"Overpriced"
"nursery"
"Not_duplicate"
"A) damage, B) wonderful, C) exhaustion, D) orgasm, E) lazy,"
"Question"
"A) apartment, B) loft, C) store, D) rug, E) stairs"
"A great teacher can be what when you are attending school?"
"Shopping mall, B) museum, C) laundromat, D) clothing store, E) bedroom"
"air"
"Manhattan, office, D) fifth avenue, E) new york city"
"A) coffee shop, B) office, C) table, D) washing, E) kitchen"
"Funeral"
"Not_duplicate"
"Hardware store, B) toolbox, C) logging camp, D) tool kit, E) auger"
"Question"
"Fraternity house"
"A) frightened, B) run up stairs, C) get away from, D) go quickly, E) go faster"
"A) stagnant, B) tradition, C) hunger, D) paper money, E) paper money,"
"A) mall, B) grocery store, C) grocery store, D) shop, E) supermarket"
"A) cupboard, B) oven, C) stomach, D) fridge"
"managed"
"Not_duplicate"
"Question"
"A) eastern hemisphere, B) open plain, C) television program, D) great outdoors, E) television program"
"stretches"
"Question"
"A) british columbia, B) body of water, C) wooded area, D) pay debts, E) zoo"
"Question"
"Press coverage"
"The electricity went out and everyone was shrouded in darkness."
"A) clerk, B) strip mall, C) city, D) neighborhood, E) neighborhood,"
"A) halloween, B) summer, C) easter, D) kwaanza, E) give gift"
"Family tree"
"not_duplicate"
"Answer"
"He walked into the room and had a great shock, his friends had what him?"
"Question"
"A) truck stop, B) amusement park, C) atlas, D) mall, E) gas station"
"A) sports, B) fishing gear, C) soccer game, D) fishing boat, E) badminton"
"Sage loved communicating He liked doing what with his peers?"
"A) floor, B) humane society, C) comfortable chair, D) window sill, E) window sill,"
"Radio shack"
"Freeway, B) race track, D) alley, E) parking lot"
"A) baggage compartment, B) movie, C) subway, D) airplane, E) cargo hold"
"E) spills,"
"A) kitchen, B) safe, C) own house, D) building, E) pantry"
"A) motel, B) hostel, C) building, D) lobby, E) office park"
"Question"
"Question:"
"procrastinate"
"A) walk, B) agitate, C) wander, D) remove, E) disturb"
"Rural"
"capitol building"
"matrimony"
"A) run away, B) hurry along, C) fine motorists, D) direct traffic, E) help"
"begin work"
"hen house, B) english hunt, C) mountains, D) outside bedroom window, E) england"
"A) go down, B) apartment building, C) tall building, D) office building, E) cabin"
"rebirth, decomposition"
"Yellow pages, B) town, C) business sector, D) town, E) at hotel"
"Answer"
"if a bald eagle is found, what is he likely to do with it?"
"Music school, B) music store, C) neighbor's house, D) drawing room, E) drawing room"
"A) department store, B) restaurant, C) hotel, D) dime store, E) bathtub"
"Anus, B) partner, C) arousal, D) trust, E) cooperation"
"A) count to ten, B) state name, C) dress herself, D) clean room, E) socialize"
"A) get tired of, B) small talk, C) eye contact, D) social life, E) social life,"
"bible"
"stairwell"
"Answer"
"A) cross street, B) draw attention to themselves, C) make money, D) fall down, E) come home"
"tennessee, B) south carolina, C) louisiana, D) oklahoma, E) mountains"
"Question:"
"A) exhaustion, B) getting in shape, C) fitness, D) injure himself, E) fatigue"
"A) internet, B) book, C) online, D) google, E) manual"
"A) rebirth, B) human experience, C) sadness, D) decomposition, E) obesity"
"In what type of non-vegetarian soup is one likely to find a potato?"
"A) qualification, B) strength, C) pity, D) competence, E) potential"
"practice"
"Sun set is a phenomenon that occurs when the sun rises and sets in relation to the earth's surface."
"Question"
"A) persia, B) table, C) living room, D) hall"
"Question"
"Question:"
"Question"
"A) home, B) dairy farm, C) cattle show, D) dairy barn, E) corral"
"A) home, B) wealth, C) bankruptcy, D) lose money, E) get rich,"
"graduated, B) masters, C) postgraduate, D) phd, E) professor"
"A) ocean, B) getting off of bus, C) airport, D) urban area, E) towns"
"Bill wanted to pick up a stranger, preferably a responsible one with kids"
"A) desert, B) hole, C) india, D) cage, E) rain forest"
"Question:"
"Not_duplicate"
"A) pleasure, B) greater mobility, C) desire to travel, D) global warming, E) increased security"
"Question:"
"A) beach, B) ocean, C) ocean, D) water, E) sea plant"
"i want to store cooked steak?"
"Question:"
"A) eyes, B) fingertips, C) brainstem, D) human body, E) human body"
"A) bookstore, B) drawer, C) health department, D) mail box, E) library"
"A) sporting event"
"California"
"halibut"
"Smile"
"A) municipal park, B) office, C) state park, D) cemetary, E) public gardens"
"A) housing estate, B) neighborhood, C) mars, D) woods, E) suburbs"
"Building"
"A) get lost, B) require water, C) trained, D) bark, E) roll over, F) bark, G) bark, H) bark,"
"A) texas, B) kansas city, C) maine, D) falling down, E) falling down, F) falling down, G) falling down, H) falling down, I) falling down, I) falling down, I) falling down, I) falling down, I) falling down, I) falling down, I) falling down, I) falling down, I) falling down, I) falling down, I) falling down, I) falling down, I) falling down, I)"
"Building"
"Boredom"
"A) orchestra, B) church, C) chinese temple, D) chinatown, E) music store"
"Answer"
"Question"
"court room"
"Not a problem. He did not like standing in line."
"Transporting"
"A) lay in bed, B) lay in bed, C) go to bed, D) relax, E) lie down"
"barbell"
"Library"
"Not a match for the image shown."
"A) bookstore, B) library, C) electrical circuit, D) cabinet, E) important when traveling,"
"Restaurant"
"Answer"
"A) book or library, B) book or magazine, C) newspaper, D) past, E) future"
"Question"
"Question"
"listen to music, B) watch television, C) walk, D) play basketball"
"A) music store, B) brass band, C) brass band, D) marching band, E) marching band"
"A) concert hall, B) museum, C) school, D) hockey game, E) sporting event"
"Stabbing to death of a person is what sort of way to die?"
"Options"
"Question"
"A) san francisco, B) refrigerator, C) big box retailer, D) tree, E) market"
"A) desk, B) meeting, C) office, D) table, E) work"
"Stark was just having fun, and he wasn't hurting anyone."
"The church was giving assistance, what were they hoping to accomplish?"
"Question"
"Health problems, D) indigestion, E) gain weight,"
"A) refrigerator, B) bookstore, C) cupboard, D) school building, E) wardrobe"
"Garage"
"A) ice pack, B) freezer, C) laboratory, D) warehouse, E) refrigerator"
"Restaurant"
"baseball stadium"
"A) below, B) concert hall, C) concert hall, D) museum, E) building"
"hair salon"
"a) meet interesting people, B) lift weights, C) listen to music, D) play chess, E) entertain"
"Food poisoning, D) heartburn, E) gain weight"
"Battery"
"A) country, B) democracy, C) canada, D) civilization, E) tax office"
"Answer"
"Multiplication, B) multiply, C) putting together, D) unity, E) pay debts"
"A) pocket, B) classroom, C) table, D) library, E) shelf"
"Fatigue"
"thirsty"
"A) silent, B) opera, C) silence, D) television, E) elevator"
"A) new york, B) blocks of flats, C) center of town, D) america, E) big cities"
"Stringbed"
"A) tomb, B) arena, C) access rooms, D) public building, E) house"
"Question"
"A) build trust, B) hurry home, C) ignore people, D) believe in god, E) jump to conclusions"
"A) hospital, B) chest, C) home, D) dresser drawers, E) cabinet"
"Jump to conclusions, B) hurry home, C) build trust, D) pay bills, E) sing"
"Procreation"
"enlightenment, D) communication, E) frustration"
"Answer"
"a shrink ray"
"Christine?"
"Joe plays a percussion instrument in something."
"A) losing, B) competition, C) having fun, D) win, E) injury"
"A) cheat, B) fair, C) in competition, D) practice, E) sabotage"
"A) jean, B) mulberry tree, C) garments, D) expensive clothing, E) parachutes"
"library"
"Not a problem, but I'm not sure where to put my resume."
"Question:"
"Sore muscles"
"A) play cards, B) double winnings, C) lose money, D) play poker, E) to win the prize"
"-"
"Question"
"School, B) string quartet, C) orchestra, D) kitchen, E) music room"
"heat"
"Mandy lived in a train station. She longed to see distant places."
"Joe is a squirrel, which is an animal."
"A) cabin in the woods, B) california, C) front yard, D) conservatory, E) tropical forest"
"court room, B) shallow waters, C) poker game, D) sea world, E) pond arena"
"A) street, B) tropical forest, C) garden of eden, D) new mexico, E) white house"
"Answer"
"A) supermarket, B) diaper bag, C) liquor store, D) hollow log, E) medicine cabinet"
"Library"
"A) good health, B) exercise, C) muscle tone, D) sweat, E) feel better"
"water fountain"
"Not a good idea"
"Answer"
"Doorway"
"Library of Congress, B) pocket, C) backpack, D) suitcase, E) synagogue"
"A) open field, B) ivory coast, C) steppe, D) encyclopedia, E) encyclopedia"
"A) winning or losing, B) aggression, C) gain, D) defeat, E) sweat,"
"Summer, B) park, C) sea, D) moon,"
"A) fan, B) get wet, C) get cold, D) air conditioning, E) get wet, D) get wet, E) air conditioning"
"Question: Where would you store a pillow case that is not in use?"
"A) shelter, B) floor, C) warm place, D) farmhouse, E) living room"
"China"
"A) living room, B) parlor, C) music hall, D) music room, E) museum"
"A) luggage store, B) courtroom, C) airport, D) office building, E) hand,"
"Question:"
"Bus to work is a common way to get to work and to get to your destination"
"Question"
"Question"
"A) seed plants, B) plant seeds, C) garden, D) grow corn, E) produce food"
"A) thin out, B) grow in ear, C) fall out, D) bulge, E) composted"
""
"John loved his snake. It was the only ting he loved."
"Water plants"
"I picked from an apple tree outside of Fort Wayne, where am I?"
"A) synagogue, B) front porch, C) classroom, D) obesity, E) grocery store"
"Hang over, D) headache, E) intimacy, F) hang over, G) hang over, H) hang over, I) hang over, J) hang over, K) hang over,"
"cave"
"A) crime scene, B) blood bank, C) slaughter house, D) needle, E) crime scene"
"Pay debts"
"The town house went right to the curb, a slot effectively made a mailbox of the what?"
"A) theater, B) concert hall, C) floors, E) school"
"Warm coat"
"A) enlightenment, B) confusion, D) smartness, E) anger"
"Not the answer"
"A) ulcers, B) degree, C) understanding of, D) gaining knowledge, E) happiness"
"Question"
"A) hamshackle, B) pizza, C) fridge, D) refrigerator, E) part of meal"
"A) efficiency, B) aggravation, D) aggravation, E) stress"
"Sam wasn't lying, but he left out important details."
"Problems, B) distress, C) fear, D) go to jail, E) killer"
"A) army, B) battle, C) wildlife, D) country, E) organization"
"Answer"
"iowa"
"A) child's room, B) boy's bedroom, C) toy store, D) house, E) toy store"
"Hardware store, B) engine, C) fishing camp, D) lake, E) sporting goods store"
"Not_duplicate"
"Water cooler, B) space shuttle, C) baby shower, D) bus stop, E) family"
"Question:"
"A) lazy, B) own house, C) talented, D) reproduce, E) reproduce,"
"A) straightforward, B) serious, C) solemn, D) somber, E) funny"
"Question"
"A) furniture store, B) schoolroom, C) patio, D) office building, E) library"
"Question"
"A) excitement, B) getting tired, C) overtime, D) anger, E) fights"
"Amusement park"
"Answer"
"A) web page, B) store, C) la ville, D) bus, E) email"
"eat cake, C) bus depot, D) football stadium, E) surface of earth"
"A) train, B) strange, C) human, D) stupid, E) dangerous"
"..."
"Answer"
"neck"
"Everything"
"It was very full, and Sam couldn't stop staring at it."
"A) shop, B) mall, C) department store, D) drawer, E) library"
"A) go too fast, B) honk the horn, C) honk the horn, D) go fast, E) start running"
"Caregiver"
"A) bottle, B) refrigerator, C) hockey game, D) casino, E) bar"
"Library"
"A) kansas, B) meadow, C) farmland, D) countryside, E) rural area"
"Probably talking loudly, D) amount to nothing, E) believe in god,"
"Forest"
"Sea water"
"A) nausea, B) death, C) illness, D) health problems, E) gain weight"
"Answer"
"A showroom feature washers and refrigerators, where is this showroom located?"
"mexico"
"A) last all night, B) farmer's market, C) jar, D) honeyful, E) honeyful, F) farmer's market, G) farmer's market, H) farmer's market,"
"A) london, B) apartment building, C) city, D) falling down, E) town"
"A) tree, B) mulberry bush, C) chicken coop, D) rabbit warren, E) rabbit warren"
"Building"
"Avalon is a city in the United States of America."
"A) appliance store, B) sports stadium, C) dress emporium, D) hot room, E) football stadium"
"Not the answer"
"A) get arrested, B) have fun, C) get sick, D) spend money, E) stupidity"
"a piece of land in Canada where you can find marmot?"
"Reduce, it seemed girls no longer want to what?"
"Question"
"Question:"
"A) tear down, B) raze, C) mutilate, E) demolition"
"Billy saw a dog running from him and did his best to get away from it. He leaped up to where the dog couldn't reach and was stuck."
"Answer"
"bluegrass music"
"Free Gift:"
"Question"
"James"
"Practice"
"The dogs were protecting their own when they decided to what the bad man?"
"Mill"
"A) airport, B) luggage compartment, C) with the pilot, D) room, E) clothing store"
"Options"
"A) laughter, B) sweating, C) embarrassed, D) breathing heavily, E) tiredness"
"Not_duplicate"
"Grocery shop"
"he was beginning to worry they wouldn't get on the ride before closing, they had been standing in queue for a long what?"
"Breathlessness"
"Often a person has a fear of water or a dislike of being wet, it is still important to make sure they are having a bath why?"
"A) lights, B) crowd, C) university campus, D) theater, E) park"
"walking"
"united states"
"Question"
"A) genetic mutation, B) have sex, C) flirting, D) going on a date, E) having sex, D) kiss, E) having sex, D) kissing, E) having sex, D) flirting, E) having sex, D) kissing, E) having sex, D) flirting"
"Question"
"jar"
"A) dishwasher, B) water fountain, C) sand box, D) kitchen cabinet, E) kitchen sink"
"A) take it all in, B) headphones, C) desktop, D) conference, E) concert"
"Because of his anger he couldn't clearly explain or what?"
"jerusalem, B) jewish neighborhoods, C) dining in, D) new york city, E) dining,"
"washington state, B) utah, C) northern california, D) the desert"
"A) sporting goods store, B) backpack, C) kitchen, D) sharp edges, E) dog house"
"Feed yourself"
"Cool house, B) warm room, C) gas or electric, D) burn child, E) brown meat"
"A) religious experience, B) closed eyes, C) loss of control, D) sleep, E) hallucination"
"Not_duplicate"
"The music was festive but why are the horses dancing in circles Options"
"A) theater, B) floors, C) concert hall, D) education, E) school"
"A) sleep, B) write, C) make bread, D) stay in bed, E) enjoy film"
"A) tent, B) car, C) living room, D) friend's house, E) apartment"
"supermarket door"
"Options"
"A) ocean, B) found in ocean, C) water, D) found in sea, E) beach"
"Question"
"A) sadden, B) demote, C) demote, D) drop, E) decrease"
"Fish department, C) fancy restaurant, D) government submarine, E) chesapeake bay,"
"Question"
"bowls"
"cheshire"
"A) get mad, B) compile, C) debug, D) write code, E) get frustrated"
"John knew that the sun produced massive amounts of energy in two forms."
"A) courtroom, B) office building, C) press charges, D) theatre"
"James bought a new set of tire chains and put them somewhere he could find them."
"A) roots, B) millions of cells, C) see work, D) leaves to gather light, E) flowers on"
"shady places, B) screened porch, C) pots, D) ceramics, E) clay pot"
"Parents"
"hug"
"a) garden shed, B) hardware store, C) greenhouse, D) in a van, E) in a van, F) in a van, G) in a van, H) in a van, I) in a van,"
"A) airbase, B) prison, C) mill, D) nuclear plant, E) recording studio"
"A) table, B) restaurant, C) popular, D) oven"
"The actors and actresses were changing into costumes in the dressing room, it was almost time to take the what stage?"
"Answer"
"A thoroughfare meandered through fields and woods, where was it passing though?"
"Furniture store, B) parlor, C) turkey, D) living room, E) den,"
"Not_duplicate"
"A) adriatic sea, B) mediterranean sea, C) hand, D) see, E) atlantic ocean"
"chest of drawers, B) stove, C) hold alcohol, D) bookcase, E) grocery store"
"A) being arrested, C) pool of blood, D) mess, E) grisly"
"atlantic ocean"
"A) skyscraper, B) new york, C) school building, D) city, E) work"
"A) club, B) restaurant, C) university, D) pub, E) church"
"A) microscope, B) abbreviate, C) glasses, D) camera, E) telescope"
"Bank"
"A) carpet, B) river, C) lumberyard, E) synagogue"
"A) desert, B) baseball diamond, C) hell, D) baseball stadium, E) baseball field"
"A) enemies, B) sweat, D) tension, E) frostbite"
"Many words"
"eat ice cream"
"afterword"
"A) week, B) bright, C) night, D) twenty four, E) year"
"A) both positive and negative, B) unknowable, C) important to people, D) ocean, E) confusing"
"Options"
"Man crew"
"A) need care, B) come home, C) fast food, D) watch television, E) wash dishes"
"- Street"
"A) syllable, B) english alphabet, C) word, D) email, E) invitation"
"cling film"
"A) west virginia, B) kentucky, C) desert, D) sea, E) rocky hills"
"A) hospital, B) most businesses, C) classroom, D) public building"
"A) gay bar, B) market, C) grocery store, D) refrigerator, E) container"
"A) box, B) grocery store, C) eyes, D) chewing, E) mouth,"
"A) spread disease, B) fly away, C) cat condo, D) bug campers, E) swamp"
"swarm"
"A) cast iron stomach, B) physical exertion, C) shin splints, D) adventure, E) fatigue"
"Sporting goods store"
"A) jewelry store, B) jewelry box, C) shopping, D) jewelry box, E) hock, F) hock, G) hock, H) hock,"
"Not_duplicate"
"The first step is that it will show you how to declare what?"
"Ax handle is a handle that is used to lift a hammer or a hammer from a hammer or a hammer from a hammer or a hammer from a hammer or a hammer from a hammer or a hammer from a hammer or a hammer from a hammer or a hammer from a hammer or a hammer from a hammer"
""
"deep south"
"A) kitchen cupboard, B) floor, C) table, D) dishwasher, E) flea market"
"Question"
"Answer"
"Answer"
"James saw a kite flying in the sky. He traced the string back to its origin and found it."
"Balloon"
"A) bottle, B) grocery store, C) spaceship, D) hockey game, E) hockey game"
"Turn off, functions, D) entertainment, E) fall asleep"
"Not_duplicate"
"A) flower pot, B) shelf, C) windowsill, D) outside, E) sill"
"phoenix"
"Brownstone"
"gilded"
"A) loose skin, B) beauty, C) miss universe, D) death, E) healthier"
"Billy lived in the capital of his country, then he moved to a small town, D) contain governmental activities, E) lowercase"
"A) color, B) class, C) meeting, D) university, E) encyclopedia"
"jogging"
"A) automobile accidents, B) backache, C) pollution, D) smoke, E) low fuel tank"
"A) supermarket, B) factory, C) juice, D) hostel, E) cabinet"
"A) isolation, B) grief, C) relief, D) angry"
"Small group, B) alone, C) solitary, D) panic,"
"A) bus stop, B) hockey game, C) hockey game, D) motel, E) alley"
"walked"
"A) waves, B) seattle, C) suitcase, D) beach, E) jacket closet"
"A) pretty smart, B) singing, C) very colorful, D) very colorful, E) light,"
"viking ship"
"A) disgust, B) reduction, C) depression, D) demotion, E) diminishment"
"Warm up"
"Cause suffering"
"A) action, B) butterflies, C) a sense of calm, D) anxiety,"
""
"Question"
"Mercury is unsuitable for human life or not"
"anxiety"
"a creek could be located in the opposite for the city which is called what?"
"A) flower bed, B) tide pool, C) florida keys, D) coral sea, E) aquarium"
"A) suitcase, B) bedroom, C) closet, D) draws, E) dresser"
"mall"
"sundown"
"Question"
"A) insight, B) laughter, D) fear, E) insight, E) fear,"
"A) headache, B) bad breath, C) heartburn, D) gain weight, E) farts"
"a) cape canaveral florida, B) battleship, C) ocean, D) trapeze"
"Question"
"A) popular, B) baked in oven, C) restaurant, D) oven, E) plate"
"mexico, B) phone book, C) town, D) city, E) sun dial"
"A) computer network, B) electrical circuit, C) lineage, D) company, E) wall"
"Question:"
"Open eyes, B) go to movies, C) kick ball, D) make art, E) look for,"
"Daydream, B) headache, C) get ideas, D) sleep, E) become distracted,"
"Checkers, B) barrels, C) baking soda, D) buffalo, E) salt"
"Golf is a game of skill and skill is a game of luck."
"A) announce, B) communicate, C) educate, D) inform, E) cancel"
"bent"
"Dirt, instruments, ore, car, junkyard, etc."
"Question:"
"Find time, B) check mail, C) listen to music, D) go to bed, E) stop worrying"
"A) office building, B) office supply store, C) desk drawer, D) with dwight, E) desktop"
"Not a problem"
"Question"
"A) fighting, B) misunderstanding, C) deception, D) play, E) distrust"
"A) nasa, B) classroom, C) stationery store, D) purse, E) office supply store"
"Question"
"Question:"
"Everglades"
"A) city or town, B) get supplies, C) strip mall, D) vermont"
"Question: Where would you need to use a lantern?"
"A) beat, D) street, E) park"
"A) being raped, B) they didn't know the passcode, C) they didn't know the passcode, D) were evil, E) were a thief"
"Answer"
"Buildings"
"write will"
"Answer"
"europe"
"Answer"
"A) microwave, B) desktop, C) shelf, D) art show, E) wall"
"A) wheels, B) feet, C) pedalling, D) practice, E) good balance,"
"Service station"
"Delivery"
"A) at the top, B) movie theaters, C) train station, D) end of line, E) opera house"
"Question: Exercise is very good for you, for faster recovery you should always do what afterwards?"
"Not a fan of the fart?"
"A) band practice, B) concert, C) music store, D) symphony, E) music room"
"A) supermarket, B) bar, C) pub, D) restaurants, E) chemistry lab"
"Book of stories"
"A) supermarket, B) farmer's market, C) farmer's market, D) salad, E) refrigerator"
"A) rejuvenation, B) no longer exist, C) no longer exist, D) unable to work, E) change of color"
"hopping"
"A) guard house, B) fly, C) eat, D) follow ultralight airplane, E) group together"
"A) movie, B) auditorium, C) theatre, D) show"
"Answer"
"A) building, B) business district, C) above ground, D) most towns, E) center of town"
"A) roof, B) inside home, C) forest, D) yard, E) park"
"amazon river"
"not_duplicate"
"surface of earth"
"A) closet, B) door, C) corner, D) shelf, E) library"
"A) smile, B) open mind, D) common interests, E) laughter"
"A) tastebud, B) inner ear, C) nose, D) inner ear, E) autistic"
"A) confession, B) state park, C) sing, D) carnival, E) opera"
"Answer"
"he has lactose intolerant, but was eating dinner made of cheese, what followed for him?"
"Music room is a room where students are taught to play music."
"A) passed, B) completing, C) passed, D) passing, E) succeeding"
"A) cleanness, B) wetness, C) exfoliation, D) use water, E) hygiene"
"A) sporting event, B) basketball, D) society, E) ranch country"
"D) drunk driving"
"Answer"
"A) job, B) boredom, C) anxiety, D) impatience, E) wisdom"
"A) ski, B) play hockey, C) summer, D) knit, E) warm"
"a) poverty, B) clutter, C) getting, D) satisfaction, E) more happiness,"
"Question"
"A) program created, B) stress, C) happiness, D) ocean, E) headache"
"A) box, B) convention center, D) public building, E) large building"
"John wanted scatter his wife's remains in a lake in the wilderness. He had to delay before of where he lived."
"Not_duplicate"
"A) orphan"
"A) stall, B) taxi, C) taxi, D) crash, E) speed up,"
"A) solid object, B) molar, C) dentist, D) unbrushed tooth, E) teeth, F) cavity in a tooth, G) cavity in a cavity in a tooth, H) cavity in a tooth, I) cavity in a cavity in a tooth, J) cavity in a tooth, K) cavity in a tooth, L) cavity in a tooth, M) cavity in a tooth, N) cavity in a tooth, O) cavity in a tooth,"
"Newspapers are the most common form of information about current events."
"A) nursery, B) south pacific, C) desert, D) sea water, E) atlantic ocean"
"a yurt, B) resort area, C) big city, D) michigan, E) going on vacation"
"Not a problem, but it is not a good idea to do crossword puzzle, or do crossword puzzle, or do crossword puzzle, or do crossword puzzle, or do crossword puzzle, or do crossword puzzle, or do crossword puzzle, or do crossword puzzle, or do crossword puzzle, or do crossword puzzle, or do crossword puzzle, or do crossword puzzle, or do crossword puzzle, or do crossword puzzle, or do crossword puzzle, or do crossword puzzle, or do crossword"
"the target"
"A) coffee shop, B) kitchen, C) hand, D) table, E) office"
"Not a good idea"
"Not a good idea"
"A) swimming pool, B) country club, C) fitness center, D) park"
"A) bite, B) digestion, C) feel pleasure, D) pass water, E) listen to each other, F) digest, G) feel pleasure, H) pass water, I) digest, I) digest, I) digest, I) digest, I) digest, I) digest, I) digest, I) digest, I) digest, I) digest, I) digest, I) digest, I) digest, I) digest, I) digest, I) digest, I) digest, I) digest, I)"
"A) corner, B) street, C) closet, D) garden, E) bathtub"
"judge feelings"
"valley"
"James need to use a public toilet but there were no public ones in sight."
"A) concert, B) bedroom, C) make person sick, D) building, E) church"
"Answer"
"A) plastic bag, B) supermarket, C) toaster, E) prison"
"Not_duplicate"
"Bath store, B) bedroom, C) hospital, D) flower garden, E) michigan"
"Question"
"A) bordello, B) rest area, C) garden, D) bus stop, E) state park"
"A) state, B) democratic, C) kingdom, D) democracy, E) dictatorship"
"Answer"
"bloom"
"A) fish market, B) shallow waters, C) atlantic ocean, D) fresh water, E) shore line"
"Study french cooking"
"She wanted a kitten and puppy so why did she only get the puppy?"
"A) full sunlight, B) bright sunshine, C) sunny place, D) eat cake, E) direct sunlight, F) direct sunlight, G) direct sunlight, H) direct sunlight, I) direct sunlight, J) direct sunlight, N) direct sunlight, O) direct sunlight, P) direct sunlight, S) direct sunlight,"
"A) neatness, B) tiredness, C) order, D) exhaustion, E) sneezing,"
"A) rumpspringa, B) meeting new people, C) having fun, D) meet new people, E) plan"
"A) ice, B) set orbits, C) universe, D) space, E) solid nucleus"
"A) bedroom, B) pleasant, C) painful, D) dirty, E) dirty, F) dirty, G) dirty, H) dirty, I) dirty, J) dirty, K) dirty, N) dirty, O) dirty, P) dirty, S) dirty,"
"A) euthanasia, B) pass water, C) die of cancer, D) feel pain, E) feel pleasure"
"Question: What is the thing that is agitated in your head when kissing?"
"Billy was reading the newspaper as he commuted to work, but once he got to his destination he balled it up and put it somewhere."
"A) garage, B) pool, C) utility room, D) hardware store, E) wishing well"
"Newspaper"
"A) kill each other, B) experience pain, C) experience pain, D) hatred, E) talk each other"
"japan"
"packaging materials"
"False information, C) hungry, D) brain tumor, E) brain tumor"
"Timing is a very important factor in the development of a child's behavior."
"a pan handler in the streets, how did he give assistance?"
"Principal"
"A) family reunion, B) brother's house, C) family picture book, D) party, E) party,"
"energh,"
"Awake after a night of heavy drinking?"
"wrapping paper"
"A) school, B) meadow, C) lamb, D) farm, E) fairgrounds"
"Question"
"A) desk drawer, B) cabinet, C) purse, D) classroom, E) pocket"
"A) crowd, B) city, C) city, D) high school, E) high school"
"A) problems, B) trial, C) imprisonment, D) prosecution"
"supermarket"
"Answer"
"A) grocery store, B) diaper bag, C) gas station, D) liquor store, E) medicine cabinet"
"atlas"
"teach courses"
"Bowling alley, football stadium, soccer field, D) sporting event, E) sporting goods store"
"A) sing a song, B) neatness, C) allergies, D) using water, E) using water"
"spittle"
"Question"
"A) you're into, B) prostitute, C) you're curious, D) curiosity, E) heterosexual woman in love"
"Answer"
"Answer"
"Not_duplicate"
"newspaper"
"Question:"
"Work"
"A) fever, B) eat every day, C) excited, D) headache, E) expressive, F) eat every day, G) eat every day, H) eat every day, I) eat every day, J) eat every day, K) eat every day, L) eat every day,"
"Prisoner"
"Question"
"A) office supply store, B) stationery store, C) martyr's chest, D) refrigerator"
"A) brothel, B) building, C) bowling alley, D) at hotel, E) at hotel, F) at hotel, G) at hotel, H) at hotel, I) at hotel, J) at hotel, K) at hotel,"
"Face problems"
"Humans need shelter to survive."
"Not the only option, but it is a good way to travel if you have a bad flight."
"Options"
"A) need for food, B) sweating, C) fastfood, D) thirst, E) exercise"
"Man made structures are not as beautiful as those that are natural."
"snowflake"
"louisiana"
"Sleeping"
"A) banana tree, B) sailor suit, C) theatre, D) mulberry bush, E) research laboratory"
"A) fall down, D) fall down, E) run"
"solar system"
"A) pantry, B) store, C) gas, D) liquid, E) garage"
"Question"
"James was below the balloon. He watched it rise."
"Not_duplicate"
"A) envy, B) jealousy, C) fear, D) excitement, E) envy"
"A) microwave, B) bedroom, C) living room, D) floor, E) floor, F) floor, G) floor, H) floor, I) floor, J) floor, K) floor, L) floor, M) floor, N) floor, O) floor, P) floor, S) floor, T) floor,"
"Question"
"It was very uneven"
"Financial security, B) live well, C) compliments, D) discounted furniture"
"Question"
"Not_duplicate"
"A) ocean, B) garage, D) harbor, E) river"
"Trust himself"
"Question"
"A) reward, B) boredom, C) boredom, D) boredom, E) satisfaction"
"Question"
"A) sailboat, B) closet, C) closet, D) table, E) apartment"
"Life partner, B) larger house, C) second chances, D) money, E) headache"
"Kite"
"he had no issue committing perjury, he had a what that he would get away with it?"
"A) desert, B) college campus, C) recreational center, D) athletic club, E) park"
"A) sand box, B) kitchen cabinet, C) waterfall, D) water fountain, E) table"
"he enjoyed visiting where?"
"ladder"
"A) fish market, B) jungle, C) sea water, D) body of water, E) soup, F) soup,"
"electric motor"
"table"
"A) cruet, B) table setting, C) kitchen cupboard, D) cabinet, E) store"
"A) cash drawer, B) teh bank, C) safety deposit box, D) pocket, E) piggy bank"
"A) home, B) serve food buffet, C) dining room, D) living room, E) kitchen"
"A) airplane, B) scooter, C) motorboat, D) car, E) motor vehicle"
"A) clothing store, B) thrift store, C) apartment, D) gap, E) gap, F) clothing store"
"A) cupboard, B) at hotel, C) swimming pool, D) clothes line, E) backpack"
"A) no problems, B) better themselves, C) face problems, D) learn from each other, E) become disillusioned"
""
"Not_duplicate"
"Answer"
"Calluses"
"What does impeachment mean for the president?"
"plebeian"
"Not_duplicate"
"A) restaurant"
"A) city, B) electrical circuit, C) residential area, D) suburbia, E) milwaukee"
"A) fridge, B) sheet music, C) desk, D) bed, E) medical chart"
"Not_duplicate"
"Question: If there is gum on your shoe where did it likely come from?"
"Question"
"A) losing weight, B) healthy, C) get in shape, D) weight loss, E) sweat,"
"not go"
"A) california, B) tokio, C) downtown, D) narnia, E) large town"
"A) repetition, B) sense of wonder, C) accidents, D) intimidation, E) increased knowledge"
"Not_duplicate"
"zoo"
"A) study, B) begin school, C) row boat, D) row boat, E) clean room"
"Dogs are often known as man's best friend because they are friendly, loyal, found outside, and very smart"
"A) boat, B) michigan, C) train station, D) bicycle shop, E) trunk of car,"
"Space"
"Where do you buy condoms?"
"A) goat, B) expensive, C) lion, D) wolf, E) meadow"
"not_duplicate"
"Sip through, B) damnation, C) shoot, D) commit crime, E) eat breakfast"
""
"A) cabinet, B) supermarket, C) jail, D) butt, E) own home, F) own home, G) own home, H) own home, I) own home,"
"A) painful, B) blind, C) contagious, D) contagious, E) bring joy, F) bring pain, G) bring sadness, H) bring joy, I) bring pain, J) bring joy, K) bring sadness,"
"Question:"
"James was someone who was caught in his own delusions."
"Not the answer"
"The flasks was used to distill elements, where was it being used?"
"Cool off, B) punch, C) illustrate point, D) fight, E) release energy"
"A) in pythagorus' band, D) in pythagorus' band, E) music class"
"first turn on power"
"The guys had a regular poker game, rather than going to the movies this what their what?"
"A) start fighting, B) play, C) lots of attention, D) petted, E) bone,"
"Dan fell off a bar stool because he was more than ever drunker"
"The wood was still rough to the touch, what did the woodworker have to do?"
"A) peon, B) indian, C) minister, D) follower, E) employee"
"The flower grew tall to compete for sunlight, what did its neighbor do?"
"Road rage is a negative emotion that can be triggered by a careless maneuver in a car."
"Healthy"
"Answer"
"Exit ramp"
"A) bad dreams, B) a good nights sleep, C) rest, D) sleepiness, E) get pregnant, F) sleepiness, G) sleepiness, H) sleepiness, I) sleepiness, J) sleepiness, K) sleepiness,"
"annoyance, D) might scare, E) irritated"
"Not a good idea, but it's a good idea to try harder."
"Question"
"For what event might one buy tickets for seats?"
"A) mall, B) business, C) store, D) sale, E) sell goods, F) sell goods, G) sell goods, H) sell goods,"
"A) babies, B) sadness, C) rapport, D) ejaculation"
"orbit"
"A) having a concert., B) cough, C) sharing of ideas, D) speak, E) sneeze"
"A) fists, B) boxing gloves, D) anger, E) hands"
"not_duplicate"
"Pool hall, B) tomales bay, C) marine museum, D) business, E) desert"
"A) supermarket, B) pantry, C) motherboard, D) bar, E) bar"
"Dance can be elegant and specific, or you can just have fun and what?"
"Music store"
"A) mentally challenged, B) lots of space, C) lots of space, D) hungry, E) acknowledgment,"
"A) winning, B) learning, C) losing, D) fatigue, E) skill"
"A) feelings of guilt, B) prison sentence, C) terrible, D) encouragement, E) die"
"Laughing after surprising them is a good sign of what?"
"Not_duplicate"
"A) high school, B) canteen, C) polytechnic, D) large room, E) all kinds of schools"
"ignorance"
"Answer"
"When you do something and have fun, its something you?"
"Answer"
"A) feel better, B) sweating, C) ocean, D) arthritis, E) arthritis,"
"A) bus depot, B) end of line, C) opera, D) neighbor's house, E) meeting"
"Lie, D) indictment"
"Dictionary"
"Debt, B) economic boom, C) being able to use, D) disagreements, E) trading"
"eat cake"
"Options"
"Question"
"A) michigan, B) new york, C) new york, D) mountains, E) countryside"
"A) field, B) restaurant, C) market, D) food store, E) field, D) market, E) food store"
"A) believe in god, B) smoke marijuana, C) desire to travel, D) use weapons, E) throw away"
"south africa"
"A) manhattan, B) drink and dance, C) alcohol, D) major city, E) downtown area"
"Answer"
"Deadworks"
"Question"
"A) skate"
"A) kitchen, B) computer lab, C) old barn, E) research laboratory"
"A) forest, B) nest, C) roof, D) leaves, E) sky"
"A) eat hamburger, B) eat breakfast, C) open fridge, D) buy food, E) cook dinner"
"Write down"
"A) afraid of, B) good at, C) make pet, D) different, E) different,"
"- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - "
"Intoxication"
"A) opera house, B) school band, C) music store, D) orchestra, E) bathroom stall"
"A) lot of, B) plenty, C) more, D) big, E) lot of,"
"Not_duplicate"
"Apple Inc."
"Silence"
"A) trunk, B) diner, C) space shuttle, D) shop, E) shop, F) shop, G) shop, H) shop, I) shop, J) shop, K) shop, L) shop, M) shop, N) shop, O) shop,"
"Question"
"A) big house, B) train, C) cabin, D) living room, E) home"
"Question: If you own a cat where is the last place you'd want to find it?"
"A) los angeles, B) food court, C) new york city, D) jewish community, E) jewish neighborhoods"
"Buy food, B) see other people, C) buying vegetables, D) buy a fat pig, E) traveling"
"Question"
"A) smiling, B) pleasure, C) hurt, D) injuries, E) laughter"
"Question"
"A) unable to work, B) born again, C) change of color, D) dead, E) no longer exist"
"Not_duplicate"
"Question"
"Prehistoric times"
"remorse"
"A) die, B) interruption, C) bleed, D) hatred, E) dying"
"Joy"
"A) show appreciation, B) asking for, C) exchanging, D) smile, E) smile,"
"Bob stands in the grass surrounded by trees and nature, where is Bob?"
"A) in kentucky, B) in central park, C) state fair, D) central park, E) state fair"
"A) cloud, B) snow storm, C) billow, D) air, E) snowstorm"
"A) basement, B) tool shed, C) repair shop, D) store room, E) store room"
"A) frustration, C) rejection, D) defeat, E) stress"
"A) chicken coop, B) beach, C) fairytale, D) great outdoors, E) corn fields"
"Question"
"exhausting"
"middle east, B) balkan peninsula, D) provide meat, E) asia minor, F) asia minor, G) asia minor, H) asia minor, I) asia minor,"
"A) supermarket, B) home, C) mart, D) obesity, E) closet"
"Question"
"maryland"
"Sky most beautiful?"
"A) slide, B) band, D) orchestra, E) coconut"
"Usually, marathoners feel tired after running twenty six miles, but some that have pushed themselves too hard might be prone to what?"
"Billy liked driving cars. He was good at it."
"Question"
"Options"
"A) cinema, B) theatre, C) movies, D) show, E) hockey game"
"symphony"
"Overcast, hideous, D) hideous, E) misshapen"
"A) reasonable, B) more money, C) not go to work, D) return to work, E) union"
"- The landscaper was carefully arching stones together, he was creating an elaborate what over the creek?"
"Not_duplicate"
"The poor girls needed a light to see, what was the relationship between that light and finishing her homework?"
"A) clerk, B) indoors, C) movie theater, D) venue, E) auditorium"
"europe"
"The low trickle of water revealed a stone, where was the stone found?"
"Question"
"A) very old, B) infiniverse, C) getting younger, D) infinite, E) real"
"Universe"
"False information, D) brain tumor, E) bull rider"
"Answer"
"Medicine cabinet"
"not_duplicate"
"A) airport, B) church, C) furniture store, D) university, E) living room"
"countryside"
"A good interview after applying for a job may cause you to feel what?"
"Answer"
"Mountains"
"A) middle ages, B) chess board, C) kids story, D) fairy tale, E) castle"
"A) library, B) bus station, C) army barracks, D) locker room"
"cigarette, D) lighter fluid."
"James decided that competing was the right choice."
"Taxi, carry people, car, stall, crash"
"Traffic accident"
"Not hungry"
"A) making money, B) leave home, C) success, D) malaise, E) bad mood"
"Buy tickets, B) passenger, C) read, D) add gas, E) run through checklists,"
"Fair"
"Question"
"A) reckless, B) bellicose, C) defensive, D) aggressive, E) dauntless"
"John felt a snake slither over him as he rested. He was afraid to raise his covers for fear of startling it."
"A) city, B) downtown, C) mall, D) shopping center, E) own house, F) own house, G) own house, H) own house, I) own house, J) own house, K) own house, L) own house, M) own house, N) own house, O) own house,"
"Question"
"Question:"
"Question"
"Stock market, D) real estate, E) treasure chest"
"Ecosystem"
"A) basement, B) cardboard box, C) ocean floor, D) high school, E) container"
"Question"
"Do time"
"Not_duplicate"
"Sky"
"A) kew gardens, B) garder, C) backyard, D) shop, E) beautiful garden,"
"A) pot, B) museum, C) garden center, D) formal garden, E) backyard, F) formal garden"
"Question:"
"Sharp claws"
"he was nervous, but where would he be soon?"
"A) found outside, B) frightening, D) four legs, E) four legs,"
"scotland, B) brown, C) fabric store, D) clothing stores, E) eddie bauer, F) scotland, D) eddie bauer,"
"A) winery, B) fruit stand, C) field, D) kitchen, E) food"
"A) grab, B) look down, C) throw, D) falling, E) may fall,"
"A) garden shed, B) hardware store, C) brothel, D) greenhouse, E) greenhouse,"
"coma"
"Building"
"computer hard drive"
