"bank"
"complete a job"
"Bookstores"
"fast food restaurants"
"farming areas"
"great britain"
"Mexico"
"Listening to each other"
"literacy"
"making music"
"record albums and wallpaper"
"peaceful actions"
"farm"
"something other"
"being entertained"
"other people"
"examine thing"
"puncture wound"
"two eyes"
"office"
"floor"
"an idea or inspiration"
"incredibly strong"
"rest areas, schools, stadiums, or hospitals"
"stupid"
"offspring"
"barn"
"a new perspective"
"new position"
"crime"
"speed up your progress"
"subway station"
"something other than hurry"
"stand in line"
"satisfaction"
"ignition switch"
"a governmental jurisdiction"
"refrigerator"
"whirlpool bath"
"front door"
"tropical rainforest"
"pay bills"
"manual"
"table"
"knowledge"
"securing employment"
"get money"
"violin case"
"telephone booth"
"pet shop"
"dress shop"
"slurred speech"
"momentum"
"fall down"
"become tiresome"
"classroom"
"rural or sparsely populated area"
"friend's house"
"desert"
"hear news, B) read book, C) see favorite show, D) comedy show"
"in my pocket"
"house"
"bodies of saltwater"
"fields"
"state park"
"friends house"
"confident"
"shower stall"
"house"
"Europe"
"bored"
"school"
"playing with toys"
"chess game"
"gone"
"irritability"
"sky"
"laboratories"
"choice"
"having a clear conscience or feeling at peace with themselves"
"walk"
"construction sites"
"produce food for consumption"
"piggy bank"
"stew pot"
"elderly"
"backpack"
"knowledge"
"african continent"
"rest"
"actions"
"stairwell"
"no particular skills or qualifications"
"symphony"
"Toronto"
"make it clearer"
"alleviate stress and unwind"
"productive"
"form and maintain friendships"
"populated area"
"rich person"
"bridge"
"open mind"
"do arithmetic"
"strong reaction"
"damaged"
"coastal cities"
"her family history"
"the night sky"
"exercise"
"fell asleep"
"small neighborhoods or downtown commercial areas"
"living room and cupboard"
"disturb or interrupt the mating process"
"home"
"symphony or orchestra"
"row boat"
"bus stop and a tunnel"
"lots of space"
"discount stores"
"hockey game"
"detestable"
"graduate students, researchers, and other professionals"
"flower beds"
"outer space"
"were likely thirsty"
"shower"
"floor"
"have to hold"
"city or town"
"physical injury"
"a device that can display movies within their home"
"testify"
"satisfied"
"gain ground"
"Kentucky"
"Anxiety and fear"
"perjury"
"positive"
"high elevation mountain areas"
"resistance"
"tell story"
"a friend"
"closed space"
"power down"
"automated teller"
"practice"
"exercise"
"comfortable clothes"
"literacy"
"positive feeling or emotion"
"feminism"
"office building"
"take a class"
"arm"
"flowers on"
"relaxation"
"peach pit"
"initiate"
"forgetting the event"
"mansion"
"military base"
"bowling alley"
"ringing the doorbell or buzzing the intercom"
"music store"
"living room"
"spinal injuries"
"pet store"
"when they are waiting in line"
"get to the end or finish line"
"something else"
"have fun"
"boutique"
"butcher shop"
"bowls"
"stand still"
"branch out"
"mortal"
"wasting time"
"broken jaw"
"orchestra"
"Forests"
"zoos"
"children's stories"
"protection"
"feeling more energetic"
"exhaustion"
"Thailand"
"tropical jungle"
"golf club"
"lawn"
"demonstration"
"perform well over a long period of time"
"reading"
"transportation"
"united states"
"reduce the problem's impact or prevalence"
"slow down"
"the illness might return or recur"
"behaving in a sensational or exaggerated way"
"Industrial areas"
"desk"
"shortness of breath"
"lamp"
"look angry"
"Ray Charles"
"quarries"
"paintings"
"ready parlor for guests"
"knowing more"
"compliance"
"an issue with their body"
"nightclub"
"drawer"
"fiddle"
"watch film"
"porcupines"
"work"
"digestion"
"something negative"
"gardens"
"performance"
"heading north"
"dustbin"
"boiling water"
"creative ideas"
"surface of the earth"
"less than ideal"
"relaxation"
"conference"
"a bonus"
"yawn"
"aquariums"
"getting wet"
"empty"
"vomit"
"the opera house"
"show"
"classroom"
"valleys"
"cages"
"enjoyed the activity"
"move from place to place without having a permanent home"
"a bone"
"pants"
"focus"
"catching a cold"
"Healthy"
"geometric shape"
"tide pool"
"cause serious injury or even death"
"listen to music"
"in a container or bag"
"bathroom"
"frying pan"
"multivitamin"
"happy"
"personal cleanliness"
"conflict and disagreement"
"more money"
"airport"
"house"
"temperate zone"
"write letter"
"New York City"
"desktop"
"Dard"
"something"
"setting the table"
"something"
"increase adrenaline or releasing endorphins"
"writing down information"
"uses up paper"
"anything"
"boredom"
"tetrahedron"
"cargo ship"
"open book"
"communication"
"son's room"
"each city"
"cash register, B) desk drawer, C) fish tank, D) bank, E)"
"something"
"fairs"
"to acquire new information or skills"
"provide some background noise or entertainment"
"table"
"Tiny"
"air"
"paralysis"
"silence"
"market"
"spend time"
"outdoors"
"Poverty"
"achieve a certain goal"
"cleaning or storage"
"store"
"responsible behavior"
"casinos"
"have money readily available to cover those costs"
"Washington D.C."
"bus depot"
"injury"
"shopping mall"
"envelope"
"current taxes"
"radio station or seen on a TV channel"
"coffee table book"
"violent tackles and injuries"
"Chicago"
"safe"
"burrows or dens"
"make tools"
"neighborhood"
"wishing well"
"motor"
"place of work"
"racetrack"
"satisfaction"
"playing sports, running, and other exercises"
"playing a game"
"share a common experience or fate"
"fall asleep"
"darkness"
"poisonous gas"
"study"
"outer space"
"marching band"
"start to grow and mature"
"asking a question"
"sewing room"
"oversupply"
"enjoying themselves"
"bus stop"
"hospital"
"will"
"New England"
"tired"
"falling"
"listening"
"Clouding over"
"desktop"
"arid regions"
"hand"
"increase speed"
"try to make new friends by talking to people"
"decomposition"
"feelings"
"ask their name"
"department store"
"look around and exploring the area"
"melt"
"cabinet"
"on the ground"
"focus their attention on their breath, mantra, or other object of contemplation"
"office supply store"
"Martorell"
"child's hand"
"airport"
"vase"
"bridge"
"can"
"rain forest"
"exacerbate this aggression"
"cruise ships"
"joy"
"multiple times"
"life is short"
"pet shop"
"an object that produces sound or music when played"
"marriage"
"Orion"
"lobby"
"neighbor's house"
"boredom"
"flatulence"
"distant"
"kitchen"
"full"
"relaxation"
"compact"
"Michigan"
"something specific"
"map"
"front door"
"hungry"
"choir"
"California, Downtown, and China Town"
"mammals"
"England"
"field"
"refrigerators"
"nightmare"
"new friends"
"pedalling"
"shelf"
"organ"
"gather"
"rough"
"neighbor's house"
"reproduction"
"cellar"
"wine"
"musical activity"
"tools, equipment, or a vehicle"
"wait for the date to arrive"
"work"
"expensive"
"nursery"
"shine brightly"
"sexual pleasure and orgasm"
"analyze"
"apartment"
"positive impact"
"clothing store"
"water vapor"
"Manhattan"
"kitchen"
"funeral"
"a city"
"hardware store"
"think"
"fraternity house"
"run away"
"stagnation"
"shop"
"cupboard"
"managed"
"case"
"unwind"
"open plain"
"a fast pace"
"confined"
"wooded area"
"panic"
"press coverage"
"Grand Canyon"
"Strip malls"
"Halloween"
"family tree"
"not the right thing to do"
"fountain pens"
"thundershock"
"have sex"
"a specific location"
"fishing boat"
"interacting"
"bed"
"electrical substations"
"freeway"
"movie"
"guilt or discomfort"
"own house"
"lobby"
"gain knowledge about the world"
"roster"
"procrastination"
"wander"
"suburbs"
"capitol building"
"procreate"
"help"
"begin work"
"hen house"
"tall building"
"Decomposition"
"hotel"
"water fountain"
"capture an image"
"music school or music store"
"bathtubs"
"partner"
"state their own name"
"eye contact"
"bible"
"stairwell"
"open doors"
"Making money"
"tennessee"
"Laboratories"
"improve his physical condition"
"internet"
"Decomposition"
"Clam chowder"
"she could achieve success"
"repeated the activity or strategy"
"below"
"backpack"
"hall"
"fall down"
"shop"
"lying down"
"cattle show"
"wealth"
"graduated"
"urban areas"
"train station"
"rain forests"
"rug"
"\"action\""
"greater opportunities to travel"
"university or college"
"the ocean"
"wrap it tightly in plastic wrap or aluminum foil"
"under the bed"
"animal"
"Bookstores"
"sporting events"
"California"
"common"
"frown"
"Municipal parks"
"an area where there are no other houses or apartments nearby"
"nuclear power plant"
"get lost"
"Texas and Kansas City"
"conference"
"boredom"
"music store"
"call each other"
"desire to win"
"court room"
"standing for long periods of time"
"transporting"
"naps"
"blunderbuss"
"drawer"
"fishing"
"bookstores and libraries"
"mouth"
"desk drawer"
"past"
"mountainous"
"engage in critical thinking"
"walk"
"music store"
"concert hall"
"violent"
"money"
"baseball stadium"
"San Francisco"
"a place where he can meet with others to discuss the paperwork"
"playing marbles"
"help someone or some group of people"
"heaven"
"negative consequences"
"refrigerator, bookstore, school building, or wardrobe"
"garage"
"freezer and refrigerator"
"small town"
"baseball diamond"
"building"
"art supplies"
"listen to music"
"a negative health outcome"
"battery"
"Canada"
"answer question"
"multiplication"
"classroom"
"fatigue"
"thirsty"
"silent"
"America"
"tie around"
"public buildings"
"farmer's market, grocery bag, pantry, and fridge"
"jump to conclusions"
"dresser drawers"
"jump to conclusions"
"human experience"
"relax"
"use water"
"become larger"
"an adult"
"a larger, organized group"
"enjoyment"
"fair"
"parachutes"
"A library"
"office desk"
"dilute the blood, and potentially cause dangerous electrolyte imbalances"
"muscle fatigue and soreness"
"losing money"
"vegetables are good for you"
"not acquainted"
"orchestras"
"heat"
"Europe"
"woodland areas"
"conservatory"
"court room"
"White House"
"drawer"
"supermarket"
"a library"
"exercise"
"water fountain"
"techniques for controlling and calming their behavior"
"using a brush"
"home"
"backpack or suitcase"
"open field"
"losing"
"moon"
"air conditioning"
"drawer"
"A farmhouse"
"China"
"a room specifically designated for music-related activities"
"luggage store"
"trust"
"commuting"
"to catch fish"
"defend"
"grow corn"
"thinning"
"losing money"
"rude"
"watering the plants"
"Indiana"
"synagogue"
"hang over"
"cabinet"
"Slaughterhouses"
"pay debts"
"town house"
"theater or concert hall"
"warm coat"
"Enlightenment"
"being entertained"
"ulcers"
"Learning to walk"
"fridge"
"some sort of negative emotional or mental impact"
"deceptive"
"killer"
"army"
"say words"
"urban or suburban"
"child's room"
"fishing camp"
"being happy"
"water cooler"
"container"
"talented"
"somber, respectful, and serious"
"stationery store"
"schoolroom"
"increase the risk of contracting sexually transmitted diseases"
"excitement"
"amusement parks"
"arguments"
"web page"
"surface of earth"
"cautious or wary"
"not actively engaged in taking notes or writing down anything"
"fish market"
"thruway"
"everything"
"bare"
"A mall"
"starting to function properly again"
"caregiver"
"bar"
"Hotels"
"rural or countryside areas"
"making noise"
"forest"
"sea water"
"death"
"listen to radio"
"appliance store"
"Mexico"
"farmer's market"
"London"
"rabbit warren"
"human body"
"English house"
"appliance store"
"bedroom"
"have fun"
"Vancouver Island"
"do something"
"people often read magazines to pass the time while waiting to see a healthcare professional"
"storybook"
"torn down afterwards"
"table"
"guide children"
"bluegrass music"
"paid for"
"were lonely"
"England"
"practicing their music"
"attack"
"mill"
"somewhere"
"drawer"
"fatigue"
"using energy"
"grocery store"
"a long"
"Breathlessness"
"hygiene"
"theater"
"making progress"
"united states"
"desk drawer"
"sexual intercourse"
"watching TV"
"jars"
"dishwasher"
"headphones"
"too angry"
"new york city"
"Pacific Northwest"
"Sporting goods stores"
"consuming food"
"generate heat"
"religious experience"
"office building"
"carnival"
"theater"
"stay in bed and relax"
"apartment"
"public place"
"table"
"ocean"
"captivity"
"negative emotion or state"
"fish department"
"table or a small side table"
"instruments"
"Lancashire"
"get mad"
"heat"
"courtroom"
"garage"
"leaves"
"shady places"
"parents"
"hug"
"garage or a garden shed"
"nuclear plant"
"plate"
"theater"
"Property tax payments"
"rural area"
"furniture store"
"neighborhood"
"hand"
"bookcases"
"being arrested"
"Amazon River basin"
"skyscrapers"
"Churches"
"microscope"
"newsstand"
"lumberyard"
"on a sports field or playing surface"
"Frostbite"
"the amount of words in it"
"eat ice cream"
"something"
"24"
"beyond human comprehension"
"effort"
"take charge of the ship and navigate it to safety"
"attention, support, and guidance"
"residential area"
"Word"
"caps"
"hilly or mountainous"
"chemistry lab"
"gay bar"
"grocery store"
"bug campers"
"swarm"
"appropriate footwear and clothing"
"Sporting goods"
"jewelry store"
"Rushing"
"debt"
"hardware store"
"foolishly"
"Gulf States"
"kitchen cupboard"
"bed"
"basement or cellar"
"ask questions"
"end of line"
"balloon"
"Casinos"
"falling asleep"
"bathhouse"
"outside"
"phoenix"
"Brownstone"
"porous"
"loose skin"
"smaller town or city"
"knowledge"
"period of recovery"
"low fuel tank"
"factory"
"positive"
"subdued"
"Motels"
"walked"
"beach"
"very colorful"
"viking ship"
"depression"
"warm up"
"effective in improving the mental illness"
"nervous"
"intentionally causing someone's death"
"receive data"
"toxic"
"anxiety"
"rural"
"florida keys"
"suitcase"
"convenience store"
"negative"
"bookcase"
"laughter"
"symptom"
"trapeze"
"defecating"
"restaurant"
"phone book"
"computer network"
"something to offer"
"take a specific action"
"lead to a certain outcome"
"something that is used for storage"
"care less"
"announce"
"something else"
"ore"
"utility closet"
"go to bed"
"desk drawer"
"Spain"
"construct"
"deception"
"specialized stores"
"to help solve a crime"
"toolbox"
"Everglades"
"cities and towns"
"dark place"
"beat"
"being raped"
"open its mouth"
"audience"
"seek help"
"desk drawer"
"it is able to exchange heat from its body with the cooler air outside its body, which"
"something"
"desktop or a shelf"
"balance"
"ground"
"receiving"
"end of line"
"Stretching"
"go back home and retrieve the forgotten item"
"band practice, concert, symphony, and music room"
"chemistry labs"
"book"
"supermarket"
"they are no longer able to work due to their condition"
"jump rope"
"fly"
"performance"
"hope for peace"
"center of town"
"on a roof or inside a home"
"Amazon River"
"make food"
"surface of the earth"
"shelves"
"common ground or interests"
"inner ear"
"confession"
"teaching"
"indigestion"
"music room"
"passing"
"maintaining personal hygiene"
"basketball"
"drunk driving"
"department store"
"wisdom"
"ski"
"something"
"gain confidence"
"happiness"
"convention center"
"state park"
"parks"
"abandoning a child"
"the plane will lose its thrust and begin to descend rapidly"
"solid object"
"newspapers"
"sea"
"big city"
"see art"
"motion"
"table"
"plate"
"impolite"
"country club"
"digestion"
"garden"
"resentment"
"valley"
"motel room"
"heavy metal music typically requires high volume and a lot of energy"
"intellectual challenge"
"toaster"
"clean"
"Hospitals"
"accelerate"
"rest area"
"central government and individual states"
"backpack"
"produce flowers"
"Atlantic Ocean"
"study french cooking"
"one choice for pet"
"direct sunlight"
"exhaustion"
"planning"
"highly elliptical"
"dirty"
"succumb to the cancer and die"
"headache"
"floor, C) subway, D) ground, E) lawn"
"utility room"
"newspaper"
"express gratitude or give thanks"
"Japan"
"packaging materials"
"false information"
"patience"
"out of pocket"
"parents"
"a family reunion"
"effort"
"headache"
"typewriter"
"meadow and farm"
"living room"
"pocket"
"crowd"
"imprisonment"
"supermarket"
"obtaining or preparing food"
"liquor store"
"atlas"
"imparting knowledge to students"
"bowling alley"
"water"
"saliva production"
"store"
"you're into"
"frustration"
"achieve a goal or complete an action"
"rhythmic movement"
"newspaper"
"wash themselves"
"weight-classed sports"
"Eating healthy and regularly"
"prisoner"
"expressing themselves"
"desk"
"hotel"
"better themselves"
"Homes"
"First class"
"seeing bear, B) see beautiful views, C) get wet, D) getting lost"
"appetite"
"artificial"
"snow"
"Louisiana"
"snoring and dreaming"
"banana tree"
"Lifting weights"
"solar system"
"pantry"
"primary school"
"upwards"
"joy and happiness"
"envy"
"microwave"
"smell good"
"very"
"financial security"
"prosecution"
"mad cow disease"
"garage"
"trusting one's own abilities and decisions"
"conflict"
"satisfaction"
"refrigerator"
"table"
"Life partner"
"to its nest"
"confident"
"park"
"water fountain"
"someone else's home"
"high place"
"jungle"
"electric motor"
"table"
"table settings"
"pocket"
"dining room"
"airplane"
"Gap"
"hotel"
"disillusioned"
"sandplain"
"theater scene"
"outdoors"
"Calluses"
"removal of a government official, such as a president, from office due to illegal or"
"inferior"
"negative outcome"
"restaurant"
"Milwaukee, Wisconsin"
"medical chart"
"spend money"
"discarded gum on the sidewalk"
"increase their income"
"healthy"
"not very likely"
"a neighborhood with a significant Japanese community"
"intimidation"
"happiness, excitement, and joy"
"Zoos"
"go out to play"
"usually implies a sense of loyalty and companionship"
"bicycle shop"
"space"
"supermarkets, drugstores, and convenience stores, and sometimes in family planning clinics or"
"goat"
"meet someone"
"shooting"
"work room"
"cabinet"
"negative"
"desk drawer"
"matter to"
"subdivisions"
"laboratory or chemistry lab"
"cool off"
"music class"
"turn on power"
"social"
"interacting with a dog"
"drunker"
"sand the wood with sandpaper"
"survivor"
"blocked the sunlight"
"road rage"
"Unhealthy"
"three vertices"
"exit ramp"
"a good night's sleep"
"bothersome or irritating"
"she would feel more pressure to succeed"
"personal hygiene purposes"
"movies"
"A mall"
"many"
"orbit"
"sharing of ideas"
"anger"
"something else"
"Tamales Bay"
"bars or casinos"
"having fun"
"music store"
"cognitive or physical impairment"
"learning"
"prison sentence"
"something"
"Park"
"high school"
"ignorance"
"work out"
"enjoy"
"sell products or services to customers"
"improving mood, reducing stress, and building a sense of accomplishment"
"bus depot"
"lying"
"dictionary"
"Economic boom"
"different type of use"
"bones"
"why others believe in something that feels fake to them"
"mountainous areas"
"Food store"
"desire to travel"
"after the tree has bloomed"
"downtown areas"
"perform work"
"breathing"
"bedroom"
"Skateboarding"
"old barn"
"nests"
"eat hamburger"
"Talking"
"frightened or terrified"
"acquiring knowledge"
"intoxication"
"orchestra"
"large amount"
"ruin"
"stock certificate"
"stillness"
"bedroom"
"it suggests that he could see the whole planet"
"living room"
"dog's mouth"
"new york city"
"buy food"
"relieved and grateful"
"pleasure"
"rug or mat"
"born again"
"fall off his board or wipe out"
"turn lock"
"prehistoric period"
"remorse"
"interruption"
"conflict or negative outcome"
"show gratitude"
"state parks"
"state fair"
"clouds"
"a repair shop"
"negative"
"outside in a natural environment"
"pond"
"common experience"
"Balkan Peninsula"
"home"
"an activity"
"Maryland"
"outdoors"
"Citrus"
"passing out"
"death"
"stay in bed"
"negative outcomes"
"a performance"
"music store"
"something happened"
"reasonable"
"bridge"
"negative"
"not have any clear connection"
"entrance of a venue or performance space"
"America"
"river bed"
"neighbor's house"
"something that has existed for a long time"
"something larger"
"making fun of others"
"interact"
"medicine cabinet"
"cooked well"
"airport terminals and churches"
"farming areas"
"hope"
"computers"
"countryside"
"Middle Ages"
"transit"
"cigarette"
"lose"
"taxi"
"lack of fuel"
"digestion"
"a feeling of malaise or general unease"
"purchase tickets"
"dog hair"
"drawer"
"aggressive"
"bedroom"
"downtown areas"
"something"
"send email"
"there may have been something said by the friends during the chat"
"the stock market"
"ecosystem"
"storage item"
"heartburn"
"attempt to escape"
"writing down"
"on vacation"
"botanical garden"
"backyard"
"feeling confident in themselves"
"their unique ability to purr"
"airport"
"outside"
"Eddie Bauer"
"fruit stand"
"grab"
"hardware store"
"helped the man to relax"
"construction"
"disk drive"
