"Question: A revolving door is convenient for two direction travel, but it also serves as"
"Question: What do people aim to do at work?  Options: A) complete"
"Question: Where would you find magazines along side many other printed works?  Options:"
"Question: Where are  you likely to find a hamburger?  Options: A"
"Question: James was looking for a good place to buy farmland.  Where might he"
"Question: What island country is ferret popular?  Options: A) own home"
"Question: In what Spanish speaking North American country can you get a great cup of coffee"
"Question: What do animals do when an enemy is approaching?  Options: A)"
"Question: Reading newspaper one of many ways to practice your what?  Options: A"
"Question: What do people typically do while playing guitar?  Options: A) cry"
"Question: What would vinyl be an odd thing to replace?  Options: A)"
"Question: If you want harmony, what is something you should try to do with the"
"Question: Where does a heifer's master live?  Options: A) farm"
"Question: Aside from water and nourishment what does your dog need? <pad><pad>"
"Question: Janet was watching the film because she liked what?  Options: A)"
"Question: What are you waiting for someone to meet you with when you're"
"Question: When drinking booze what can you do to stay busy?  Options: A"
"Question: A fencing thrust with a sharp sword towards a person would result in what?"
"Question: Unlike a spider and his many sight seers, people only have what?"
"Question: Where do adults use glue sticks?  Options: A) classroom, B"
"Question: What could go on top of wood?  Options: A) lumberyard"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: Though the thin film seemed fragile, for it's intended purpose it was actually"
"Question: Where could you find a toilet that only friends can use?  Options:"
"Question: What is someone who isn't clever, bright, or competent called? "
"Question: When we think of how to reproduce we often refer to what comes out as"
"Question: The weasel was becoming a problem, it kept getting into the chicken eggs"
"Question: Blue read material outside of his comfort zone because he wanted to gain what?"
"Question: After he got hired he hoped for success at his what? <pad><pad>"
"Question: Committing perjury is a serious what?  Options: A) indictment,"
"Question: If you are prone to postpone work what will you have to do in order"
"Question: James wanted to find an old underground map from the 50s.  Where"
"Question: Sean was in a rush to get home, but the light turned yellow and"
"Question: Where would a person be doing when having to wait their turn?  Options"
"Question: She was always helping at the senior center, it brought her what? "
"Question: The lock kept the steering wheel from moving, but the thief still took his"
"Question: Who is a police officer likely to work for?  Options: A)"
"Question: If you have leftover cake, where would you put it?  Options:"
"Question: A human wants to submerge himself in water, what should he use?"
"Question: Where is a doormat likely to be in front of? <pad>"
"Question: Bob the lizard lives in a warm place with lots of water.  Where"
"Question: August needed  money because he was afraid that he'd be kicked out of"
"Question: He needed more information to fix it, so he consulted the what? "
"Question: Where can you put a picture frame when it's not hung vertically? "
"Question: James knew that he shouldn't have been buying beer for minors.  He"
"Question: What is the result of applying for  job?  Options: A)"
"Question: What must someone do before they shop?  Options: A) get money"
"Question: Because John was first violin, he had to bring something important to work ever"
"Question: What is a place that usually does not have an elevator and that sometimes has"
"Question: Who is likely to be excited about a crab?  Options: A)"
"Question: Where can a human find clothes that aren't pants?  Options: A"
"Question: If I was getting drunk, and people couldn't understand me, what might"
"Question: When a person is beginning work, what are they building? <pad><pad>"
"Question: A child wants to play, what would they likely want?  Options:"
"Question: Talking to the same person about the same thing over and over again is something"
"Question: The teacher doesn't tolerate noise during a test in their what?  Options"
"Question: The freeway had no traffic and few buildings, where is it?  Options"
"Question: Where would you go if you wanted to have fun with a few people?"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: If you are in a bar in a glove shaped state where are you?"
"Question: Where would a computer user be using their own computer?  Options: A"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: Where can you find a snake in tall grass?  Options: A)"
"Question: What is a place that has a bench nestled in trees? <pad>"
"Question: Where is a human likely to go as a result of being hungry? "
"Question: He was beginning to regret taking the fight when he saw how what his opponent"
"Question: Where would you find a single shower curtain being used?  Options: A"
"Question: Where is a good idea but not required to have a fire extinguisher?"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: If you have to read a book that is very dry and long you may"
"Question: Sally used a clipboard to hold her papers while she read off names at the"
"Question: The kids didn't clean up after they had done what?  Options:"
"Question: Despite the name a pawn can be quite versatile, all the parts are important"
"Question: What would not be true about a basketball if it had a hole in it"
"Question: If you are awaking multiple times throughout the night because a lot is on"
"Question: Where does a wild bird usually live?  Options: A) cage,"
"Question: Where would you expect to find white mice?  Options: A) bell"
"Question: John felt that his actions were fate.   Harry said that he could"
"Question: What could committing murder prevent someone from doing?  Options: A) go"
"Question: George didn't have a car, but he still had his two feet."
"Question: A crane uses many a steel cable when working a what?  Options:"
"Question: What is the main purpose of farmers?  Options: A) raise cattle"
"Question: Where can I put this penny to save for later?<pad><pad><pad><pad>"
"Question: Where would you put uncooked crab meat?  Options: A) wh"
"Question: The man had a fear of illness, so he never visited friends who were"
"Question: Where would you put pans if you want to bring them with you? "
"Question: If you're remembering something, it's because of your what of it to"
"Question: Which large land mass is home to the most monkeys?  Options: A"
"Question: Friday was James's 5th Anniversary.  They planned on going to bed"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: You'll find a landing at the top of what?  Options: A"
"Question: Anybody could be hired in the kitchen, what was needed of them?"
"Question: Where can you find a number of wind instruments together in public?  Options"
"Question: A mountie got off at a subway stop.  What city might he"
"Question: What do you want someone to do when you illustrate point?  Options:"
"Question: Billy set aside a block of time for having fun after work. Why might"
"Question: The man in the white suit was very lazy.  He did nothing useful"
"Question: What would you be unable to do if you have too much greed? "
"Question: It was a long trip from the farm, so he stayed in a hotel"
"Question: I did not need a servant.  I was not a what? "
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: An underrated thing about computers is how they manage workflow, at one time it"
"Question: Obstructing justice is sometimes an excuse used for police brutality which causes what"
"Question: While washing clothes they became what when caught on the sharp object?  Options"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: James's daughter was interested in learning about her grandfather. She was"
"Question: James looked up and saw the start twinkling in the black yonder"
"Question: What would encourage someone to continue playing tennis?  Options: A) becoming"
"Question: James found the sound relaxing.   It was so relaxing he almost did"
"Question: What regions of a town would you have found a dime store? "
"Question: Where might an unused chess set be stored?  Options: A) toy"
"Question: james told his son to settle down and be careful.  There were"
"Question: A man wants air conditioning while we watches the game on Saturday, where will"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: Sailors drive many different types of boats, what type of boat"
"Question: Where could a person avoid the rain?  Options: A) bus stop"
"Question: Why would a person like to have a large house?  Options: A"
"Question: Where will a cheap book be found?  Options: A) bookstore,"
"Question: John and James are idiots. They bought two tickets to the Falcons vs the"
"Question: James noticed that his penis was bigger..  How might he act"
"Question: Who do professors work with?  Options: A) methods of facts,"
"Question: Colorful anemone look somewhat like what object you find on window s"
"Question: From where do aliens arrive?  Options: A) outer space, B"
"Question: The hikers stopped to have a drink, simply put<pad><pad><pad><pad><pad>"
"Question: When you get up in the morning before you begin work you should do what"
"Question: The kitten had nothing to dig it's claws into, so when it tried"
"Answer:   <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: Where could you find hundreds of thousands of home?  Options: A)"
"Question: Playing baseball is a lot like any other sport, there is always a risk"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: The victim was to take stand today, they were going to do what?"
"Question: What does a successful dog grooming session likely to make a owner feel? "
"Question: The runner was in third place, but he pushed harder and thought he might"
"Question: The tourist entered Mammoth cave, what state were they in? <pad>"
"Question: What does someone typically feel when applying for a job?  Options: A"
"Question: He was on trial for obstructing justice, during which he made a questionable"
"Question: What kind of feelings does buying presents for others create?  Options: A"
"Question: What green area is a marmot likely to be found in?  Options"
"Question: Jan tested the current, and noticed that it was high.  He thought"
"Question: What does a kindergarten teacher do before nap time?  Options: A)"
"Question: Sam was a stranger.  Even so, Mark treated him like what?"
"Question: Bob's only light source was a small bulb.  There were four walls"
"Question: James thought of criminal justice like a computer program.  It need to work"
"Question: With the card slot lit up he knew how to get started finding his balance"
"Question: To play sports professionally you must do what very often?  Options: A"
"Question: Some people prefer releasing energy through work while others prefer to release it through what"
"Question: What will a person going for a jog likely be wearing?  Options:"
"Question: The child pretended he was reading newspaper, he couldn't actually do it without"
"Question: Jenny enjoyed helping people.  It brought her a great deal of what?"
"Question: What might someone believe in if they are cleaning clothes?  Options: A"
"Question: Where would you find a basement that can be accessed with an elevator? "
"Question: In order to learn to program from another person you can do what? "
"Question: He was at the gym trying to build muscle, what is it called that"
"Question: What part of plants is pretty?  Options: A) dirt, B"
"Question: The man was going fishing instead of work, what is he seeking? "
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: The man tried to reply to the woman, but he had difficulty keeping track"
"Question: I couldn't find anybody who recalled the event, what were they adroit"
"Question: Where would you find a large dining room containing a fancy chandelier?"
"Question: The extremely large cargo plane could only land at a specialized runway, these were"
"Question: The carpet was smelly and discouraged the league from playing there, where was"
"Question: How can someone be let into a brownstone?  Options: A)"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: Where would you keep an ottoman near your front door?  Options"
"Question: Diving into backyard pools can be very dangerous and can lead to serious head"
"Question: Where would one find a snake in a cage?  Options: A)"
"Question: Where are people likely to become impatient?  Options: A) end of"
"Question: When you fail to finish something, you failed at doing what to it "
"Question: John didn't care about style.  He felt that form was less important"
"Question: When you get together with friends to watch film, you might do plenty of"
"Question: A supermarket is uncommon in what type of collection of shops?  Options:"
"Question: Bill puts meat on the scale, where does Bill work?  Options:"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: Before racers start to run they must do what at the starting line?"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: What is a person called who doesn't have immortality?  Options: A"
"Question: Why would you be watching tv instead of doing something else?  Options:"
"Question: If chewing food is difficult for you, what is a possible reason? "
"Question: He had to wear a tuxedo while playing the keyboard instrument, so"
"Question: Where do you find the most amount of leaf<pad><pad><pad><pad><pad><pad>"
"Question: Where can children play with animals?  Options: A) meadow,"
"Question: What kind of tale might feature a talking weasel?  Options: A"
"Question: What kind of status is the bald eagle given?  Options: A)"
"Question: Why do most people take a quick rest during the day?  Options:"
"Question: What could suddenly stop someone when he or she is running?  Options:"
"Question: Where would you find a monkey in the wild?  Options: A)"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: A gentleman is carrying equipment for golf, what is he likely to have?"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: The computer was difficult for he to understand at the store, so what did"
"Question: If you take the risk buying a used car, you still hope it can"
"Question: Dan was ditting quietly on the couch with a book in his hand."
"Question: What is the primary purpose of cars?  Options: A) cost money"
"Question: Alabama is full of different people, but they are all citizens of what?"
"Question: They were hoping their campaign would create a rise in awareness of the problem and"
"Question: What do airplanes do as they are arriving at the gate?  Options:"
"Question: If a person with mental illness stops treatment what will likely happen? <pad>"
"Question: The gimmicky low brow TV show was about animals when they what? "
"Question: A loud machine is irritating, but many are expected<pad><pad><pad><pad><pad>"
"Question: What part of a table would you put a ruler in?  Options:"
"Question: What happens if someone kisses too hard or too long?  Options: A"
"Question: If I have a modern light source in my living room, what is it"
"Question: The person saw the mess his children made, what was his following reaction?"
"Question: Who might wear dark glasses indoors?  Options: A) blind person,"
"Question: Where would stones not be arranged in a path?  Options: A)"
"Question: A bald eagle is likely to be found on what kind of work? "
"Question: The hostess was good at her job, she always had a smile when"
"Question: What is likely to happen to someone who is learning?  Options: A"
"Question: The inspector was agreeing with the factory protocols, what was the status of the"
"Question: After standing up I had to sit right back down, why would I feel"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: The dad wanted to protect his house, where did he put his gun?"
"Question: What instrument can be played with an air of happiness? <pad><pad><pad>"
"Question: What to kids do for boredom on a ramp?  Options: A)"
"Question: What animal has quills all over it?  Options: A) feather"
"Question: Why would you go to an office?  Options: A) work,"
"Question: When is the worst time for having food?  Options: A) digest"
"Question: If you spend all your time buying and not saving what is is likely to"
"Question: Though a mouse might prefer your house, you might also see him where?"
"Question: What is performing a type of<pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: Joan wants to cook a potato, where should she place it? <pad>"
"Question: Writers with a great what can amass a large fortune?  Options:"
"Question: Where do all animals live?  Options: A) the moon, B"
"Question: How are the conditions for someone who is living in a homeless shelter? "
"Question: You can do knitting to get the feeling of what?  Options: A"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: John got his tax refund back.  He treated it like it was what"
"Question: A person with an allergy might be doing what if they awake suddenly? "
"Question: Where is a ferret unlikely to be?  Options: A) classroom"
"Question: If you jump in any of the oceans you will get?  Options:"
"Question: Immediately after peeing, a person's bladder is what?  Options:"
"Question: The lady would eat and eat, and because of mental issues would then make"
"Question: A car was hailed to chauffeur someone to the opera house, where"
"Question: What do you go to see for live entertainment?  Options: A)"
"Question: The teacher thought that a ferret can be very mischievous and probably"
"Question: A creek is a body of water found in what low land?  Options"
"Question: If I have a pet bird, what does it likely live in? "
"Question: Joe and Mac were playing basketball. They did it every day in their back"
"Question: What makes someone a nomad?  Options: A) unpleasant things,"
"Question: What is a treat that you dog will enjoy?  Options: A)"
"Question: Women used to be expected to wear a dress but it's now acceptable for"
"Question: The fact that Joe was able to memorize the list in spite of his"
"Question: What is a wet person likely to do?  Options: A) gain"
"Question: After recovering from the disease, what did the doctor call the patient? "
"Question: The painter started to edge the room with tape, he always took extra care"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: What could a driving car do to a pedestrian?  Options: A)"
"Question: People do many things to alleviate boredom.  If you can't get out"
"Question: At a grocery store they sell individual potatoes, where does the grocery clerk likely"
"Question: What room is a rubber bath mat usually kept?  Options: A)"
"Question: What would you put meat on top of to cook it? <pad><pad>"
"Question: Minerals can be obtained in what way for a person who avoids leafy"
"Question: What could you be a few hours after you finish cashing in due to"
"Question: The smelly man was having a bath, but what is he pursuing?"
"Question: What might a couple have a lot of when they are deciding on stopping being"
"Question: If a person is working a lot, what are they likely trying to earn"
"Question: The traveling business man was glad his credit card had perks, it offset the"
"Question: Billy hated using other people's toilets. He was only comfortable on his own"
"Question: The forest experienced a cold winter, where is it located?  Options:"
"Question: How can you let someone know about your anger without hurting him or her?"
"Question: Where is one likely to find a brownstone?  Options: A)"
"Question: What may I place the telephone on?  Options: A) bar,"
"Question: What language type is someone from Iran likely to use? <pad><pad><pad>"
"Question: John went to a party that lasted all night.  Because of this,"
"Question: The child wasn't allowed in the kitchen but still wanted to help, what"
"Question: He was having a hard time expressing himself in a healthy way, the psychologist"
"Question: When someone is physically competing what does their body do?  Options: A"
"Question: How would you express information to a deaf person?  Options: A)"
"Question: Printing on a printer can get expensive because it does what?  Options:"
"Question: What will god never do according to religion?  Options: A) anything"
"Question: One of the potential hazards of attending school is what?  Options: A"
"Question: What has a surface with many sides?  Options: A) tetra"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: The old style pop ups literally let you see the story when you did what"
"Question: What is it called when you are talking to someone?  Options: A"
"Question: The family finished dinner, the child's chore was to load the dirty dishes"
"Question: Where could you find a bureau as well as many politicians?  Options:"
"Question: Dad wanted to hide the check in his office, where did he put it"
"Question: For some reason she was devoid of regular emotions, buying products was the only"
"Question: Where are horses judged on appearance?  Options: A) race track,"
"Question: Why do people read non fiction?  Options: A) having fun,"
"Question: While knitting you can do what using a radio?  Options: A)"
"Question: Where are you likely to set papers while working on them?  Options:"
"Question: John had a massive debt to 50 million dollars.  Compared to that,"
"Question: The man flew his airplane over the city and saw pollution visibly in the sky"
"Question: What is a very unlikely side effect of becoming inebriated? "
"Question: when communicating with my boss what should i do  Options: A) misunderstand"
"Question: If not in a stream but in a market where will you find fish?"
"Question: What are people likely to want to do with their friends?  Options:"
"Question: During a shark filled tornado where should you not be?  Options:"
"Question: What is the likely result of buying products in excess?  Options: A"
"Question: What is a person trying to accomplish when taking analgesics? <pad><pad>"
"Question: Where would you put a glass after drinking from it?  Options: A"
"Question: Where would you buy food?  Options: A) freezer, B)"
"Question: When a person admits his mistakes, what are they doing?  Options:"
"Question: Where do play a game for money?  Options: A) casino,"
"Question: When you travel you should what in case of unexpected costs?  Options:"
"Question: Donald is a prominent figure for the federal government, so in what city does"
"Question: There was more than one bum asking for change or a ticket, it was"
"Question: John and Joe like planning games but Joe  was hit by a ball"
"Question: Where can you buy jeans at one of may indoor merchants?  Options"
"Question: What do you write letter in in America?  Options: A) syll"
"Question: Joe owned back taxes as well as what other type of taxes? "
"Question: Where is a broadcast studio likely to be heard?  Options: A)"
"Question: Kramer wrote a self-referential book.  What might that book be"
"Question: Of all the sports, Billy enjoys football, but what does his concerned mother"
"Question: What city will likely have many parking structures?  Options: A) ch"
"Question: Sally was afraid of danger and always double checked what?  Options: A"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: People are very much like the animals, but one thing has changed"
"Question: They children loved having a back yard, and the parents loved that it was"
"Question: While people just throw coins down them now, what originally had a pail"
"Question: Joe was thrown from his boat into the water.  The water was cold"
"Question: When a human is earning money, where are they often found?  Options"
"Question: They passed a apple tree on their way to the racetrack, the"
"Question: Why do people play chess on the weekends?  Options: A) satisfaction"
"Question: What do you need energy to do in gym class?  Options: A"
"Question: Sarah dropped the marble because she wanted to do what?  Options: A"
"Question: We are all human, and we all what?  Options: A)"
"Question: If a person were going to bed, what would be their goal? "
"Question: What are candles good for eliminating?  Options: A) shelf, B"
"Question: WHat leads to an early death?  Options: A) poisonous gas"
"Question: What room would you find many bookcases and is used for contemplation? "
"Question: Where do you head to travel to a star?  Options: A)"
"Question: The player lifted his cornet and walked in rhythm, what was the player"
"Question: What happens at soon as a living being is born?  Options: A"
"Question: When someone is talking and you missed something, what can you do to get"
"Question: Where does one store fabric in their own home?  Options: A)"
"Question: What do most companies not want to have relative to demand?  Options:"
"Question: What is happening while he's playing basketball for such a long time? "
"Question: A traveler laments the fact that mass transit is limited in his city when"
"Question: The person was in physical distress, where should he go? <pad><pad>"
"Question: The cancer patient was expecting to die, so he made out his what?"
"Question: There was a toll road that meandered from Maine to New Hampshire,"
"Question: If you partied all night you could find yourself already what, even when"
"Question: The cat carefully navigated the area, they do everything they can to avoid"
"Question: What is someone usually doing if someone else is talking to him or her?"
"Question: What does the sky do before a rain?  Options: A) appear"
"Question: Pens, computers, text books and paper clips can all be found where?"
"Question: What geographic area is a lizard likely to be?  Options: A)"
"Question: What do you use to carry your briefcase?  Options: A)"
"Question: He picked up his pace to a run, he wanted to do what?"
"Question: What would a person do if they do not have any friends?  Options"
"Question: As a result of dying, what happens to the body? <pad><pad>"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: What do you ask a child to do when you first meet her? "
"Question: Where can you buy a clock, clothing and wrenches?  Options:"
"Question: What do you do when you're in a new place and want to see"
"Question: What happens when to ice when it is in the sun?  Options:"
"Question: Where can you store your dishes in your dwelling?  Options: A)"
"Question: The man laid on the soft moss and looked up at the trees, where"
"Question: What is someone doing if he or she is sitting quietly and his or her"
"Question: Where can I find a stapler in many places?  Options:"
"Question: A man takes a seat at a museum outside of Barcelona, where is he"
"Question: Where would you find a toy soldier that is being played with?  Options"
"Question: Where are you when you're about to use your plane ticket? <pad>"
"Question: Flowers make a good center focal point, just one of many arrangements that look"
"Answer:   <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: Batman bought beer.  There were no bottles available.  He had to"
"Question: You can find a monkey in what West African region on the Gulf of Guinea"
"Question: Surprising an angry person could lead to what?  Options: A)"
"Question: Where is a dining area likely to be small?  Options: A)"
"Question: Killing people should not cause what emotion?  Options: A) vengeance,"
"Question: James slamed into someone playing football, and not for the first time."
"Question: More people should lower the guard and just have fun, we don't got"
"Question: Where can you get a lizard to keep in your home? <pad><pad>"
"Question: What would use a musical instrument?  Options: A) guitar, B"
"Question: She was in an affair, what did that end upon discovery by her husband"
"Question: What is the most famous constellation out of earth?  Options: A)"
"Question: If a reception is held with hotel guests walking by, what is the likely"
"Question: What is a place that is far away from your house and where you could"
"Question: If a court case is dismissed after hearing testimony, what would be a likely"
"Question: Sitting down quickly after eating beans could lead to what?  Options: A"
"Question: John was my neighbor, it was easy to talk to him. He was"
"Question: Where do people want to have a lot of coffee?  Options: A"
"Question: You stop and have food all around you, what are you? <pad>"
"Question: James was meeting a friend.  They had planed a slow day."
"Question: The car's steering seem quite loose, but he still considered purchasing it because"
"Question: Dan was a farmer with just one heifer.  But that was okay"
"Question: It's Friday night and Alice puts off going to bed because she plans on"
"Question: His phone was dead and they couldn't find the expressway, he opened"
"Question: What would someone use a personal key for?  Options: A) car"
"Question: The cat kept pestering it's owner, it was that time of"
"Question: Her voice lent her to the alto section, what group did she"
"Question: Where are you likely to find a Japanese restaurant not run by people from Japan"
"Question: Animals who have hair and don't lay eggs are what?  Options:"
"Question: John was an aristocratic fox hunter.  Where might he live? "
"Question: Where is a grape likely to be being fed to someone else?  "
"Question: Some food can be stored at room temperature until you open it, then you"
"Question: Sam couldn't get back to sleep because of a dream he had. "
"Question: If you're going to a party in a new town what are you hoping"
"Question: How is riding a bike getting it to move?  Options: A)"
"Question: Where does one usually keep literature?  Options: A) books and magazines"
"Question: WHat type of keyboard is made up of one or more pipe divisions?"
"Question: The bell rang, and the congregation began to leave the church."
"Question: James needed smooth sandpaper, but instead he got what type? <pad>"
"Question: Where would you borrow furniture if you do not have any?  Options:"
"Question: What must happen for an animal to and it's offspring to continue livng"
"Question: I want my wine stored in darkness, where should it go?  Options"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: Sarah didn't like to play but she didn't want to be sedentary"
"Question: Joe found spiders while checking something outside.  What might that be"
"Question: What would you do if your date does not show up?  Options:"
"Question: What did the adult do before the job interview?  Options: A)"
"Question: Most items in retail stores are what even when they are on sale? "
"Question: John what is the best place for anemone in what type"
"Question: Brawn opened the curtains so that the sun could do what?<pad><pad>"
"Question: How might releasing energy that has built up feel?  Options: A)"
"Question: What would you do if you have curiosity but are blind and paralyzed? "
"Question: Where might it be hard to get furniture to?  Options: A)"
"Question: A great teacher can be what when you are attending school?  Options:"
"Question: Where would you get jeans and other wearable items to take home with you?"
"Question: In what substance do clouds float?  Options: A) sky, B"
"Question: Where is the large area location of the empire state building?  Options:"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: What kind of service is my body a part of when I'm no longer"
"Question: Many people wanted to leave their country estates for row houses, what did they"
"Question: Where can someone get a new saw?  Options: A) hardware store"
"Question: What would you do to a crime scene before asking a question? <pad>"
"Question: The man didn't do great in college, all his best memories were late"
"Question: In a horror movie victims usually trip when the run in order to do what"
"Question: The coach decided to make a lineup change, the team's effort was suffering"
"Question: Where would you go if you want to buy some clothes?  Options:"
"Question: Where is food likely to stay dry?<pad><pad><pad><pad><pad><pad><pad>"
"Question: What is it called when a person with mental illness is able to lead a"
"Question: Where do you keep musical instrument so it doesn't get scratched?  Options"
"Question: The woman is watching television and trying to forget her day, what is her"
"Question: While John Candy and Dan Aykroyd didn't run into a g"
"Question: When we are running what are we doing?  Options: A) stretches"
"Question: It's dangerous to let pet birds free so it's better to keep them"
"Question: A beaver is know for building prowess, their supplies come from where?"
"Question: Zane doesn't like answering questions.  He's not good at it"
"Question: Going public about a common problem can gain what for a celebrity? <pad>"
"Question: The electricity went out and everyone was shrouded in darkness.  They all remained"
"Question: Where could you find hundreds of beauty salon?  Options: A) clerk"
"Question: If it is Chrismas time what came most recently before?  Options"
"Question: If someone found out their brother was having a daughter, they would have to"
"Question: The criminal insisted he must do the crime to the bank teller, but"
"Question: what do you fill with ink to write?  Options: A) squid"
"Question: He walked into the room and had a great shock, his friends had"
"Question: He wasn't the hugging type, even when he meet friend he'd just"
"Question: If you were lost you might need a map, the best place to find"
"Question: Where would you put a net if you wanted to use it?  Options"
"Question: Sage loved communicating  He liked doing what with his peers?  Options:"
"Question: Where would a cat snuggle up with their human?  Options: A"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: Where do cars usually travel at very high speeds?  Options: A)"
"Question: What might a person be watching if they see a man with a suitcase full"
"Question: Eating breakfast in bed while seeing a homeless person shivering outside your window may"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: If somebody is working at a reception desk, they are located at the front"
"Question: If you're reading a newspaper from another country what are you doing? "
"Question: They wanted to recognize his accomplishment, where should they put his name? "
"Question: What is it called when a person tends to leave things to the last minute"
"Question: What will you do if you do not want to settle in one place?"
"Question: Where would a person live that isn't in the metro area but still has"
"Question: Jane works for the government as a senator, where does she spend a lot"
"Question: What is it called when two people in love have children?  Options:"
"Question: What did the policemen do when they heard a cry from a distance? "
"Question: It takes ambition to complete a job, but the first step is to what"
"Question: Where would I not want a fox?  Options: A) hen house"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: What do humans do to other humans after death?  Options: A)"
"Question: Where can you find a restaurant's phone number?  Options: A)"
"Question: What would you put coins into to make it work?  Options: A"
"Question: A patriotic guy with a camera is looking for a bald eagle, what is"
"Question: Where can you go to use a piano in your neighborhood if you don't"
"Question: Where would you get a shower curtain if you do not have one? "
"Question: Kissing is normally an activity reserved for your partner, but what"
"Question: What does a child learn to do before school?  Options: A)"
"Question: He was getting advice for the job interview, they told him when talking to"
"Question: According to what book did an apple tree lead to the downfall of man?"
"Question: The neighborhood had a great sense of community, there was always a crowd at"
"Question: What might a kind person do?  Options: A) cross street,"
"Question: What will a person do at work?  Options: A) cross street"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: Name a location where you would not want to find mice.  Options:"
"Question: The man started to learn jogging, what was he hoping to do?"
"Question: Where do most people turn to get information on their phones?  Options:"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: What type of non-vegetarian soup is one likely to find a"
"Question: Though she had a disability, what did her encouraging and positive coach see in"
"Question: They had a theory of what they could do in t he big game,"
"Question: When you see something rise, you are where in relation to it? "
"Question: They were getting ready for a really long hike, he put the food can"
"Question: Where would you keep a rug near your front door?  Options: A"
"Question: When you slip from a ladder propped on anything what will you do?"
"Question: What do you do when you need to get food?  Options: A"
"Question: Brad tried to arise from bed but he could not.  Instead, he"
"Question: If a heifer is really high quality, you might take her where?"
"Question: What do people want to acquire from opening business?  Options: A)"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: Where are bus stops more common in what parts?  Options: A)"
"Question: Bill wanted to pick up a stranger, preferably a responsible one with kids."
"Question: Where might a lemur frolic in the market?  Options: A"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: Everybody began performing once their director stated what?  Options: A) fear"
"Question: By learning about the world, many poor college students gain what?  Options"
"Question: Where are required to carry books all day?  Options: A) friend"
"<pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"<pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: John wanted to clean all of the dust out of his place before settling down"
"Question: Something had the nerve to break into the garbage last night, what did it"
"Question: Where would you go to get some pamphlets if you want to own them"
"Question: The audience cheered when a goal was scored, what were they spectating?"
"Question: What western state has thousands of miles of shore?  Options: A)"
"Question: Everybody seemed to be crying at the holy site, the tour guide explained that"
"Question: The smile gave away that the what was one of happiness?  Options:"
"Question: Where is a public monument likely to be erected by a city?  Options"
"Question: Where would a person live if they wanted no neighbors?  Options: A"
"Question: Where is the control room that controls a PWR located?  Options:"
"Question: What happens to a dog before someone puts up posters of them?  "
"Question: Where are the most famous BBQ steakhouses in america?  Options"
"Question: He kept plugging away in his cubicle, it seemed he was the"
"Question: If you're attending school and are falling asleep you're likely experiencing what?"
"Question: I want to buy a gong, where should I look for one?"
"Question: What would friends do if they need each others' help?  Options:"
"Question: When people are playing a game, what is their motivation to play? "
"Question: Where could there be a battle that involves words?  Options: A)"
"Question: John didn't mind getting in line.  It was what game after that"
"Question: What is the process of going somewhere?  Options: A) fire,"
"Question: The old man needed to have rest multiple times a day, he would do"
"Question: The end of the barrel of what primitive firearm is bell shaped?  Options"
"Question: Where is a good place to store pamphlets in your home or office?"
"Question: Many humans enjoy fishing and enjoy another relaxing activity at the same time, what"
"Question: Where would you get some maps that you own?  Options: A)"
"Question: Where is a good place to put a hamburger?  Options: A"
"Question: Where is a handy place to store a steel pen in your office? "
"Question: A story about World War II would be set when?  Options: A"
"Question: What type of geographic area will you find a marmot?  Options:"
"Question: Most people make stupid assumptions that are based on their prejudices.  What might"
"Question: What is something children can do while traveling in a car? <pad><pad>"
"Question: Where would you hear a trumpet along with other instruments made from the same material"
"Question: The audience listened to the orchestra play, where were they watching the performance?"
"Question: Stabbing to death of a person is what sort of way to die?"
"Question: What are you getting from you boss at the end of the week? "
"Question: If you have a ticket and you are planning to eat hot dogs, where"
"Question: Where is a great place to buy fresh fruit?  Options: A)"
"Question: The man took paperwork to other people to consult over it, where was he"
"Question: Stark was just having fun, and he wasn't hurting anyone.  What"
"Question: The church was giving assistance, what were they hoping to accomplish? <pad>"
"Question: I you believe in god, where will you go when you die? "
"Question: What can eating hamburger cause immediately after eating it?  Options: A"
"Question: Where is a shelf likely to be hidden behind a door?  Options:"
"Question: The man got a pail to catch the draining motor oil, where was"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: Where could you go to between 1000 and 10000 restaurant?  Options: A"
"Question: The pitcher stepped on the mound ready to throw, where was he located specifically"
"Question: Where is a statute found on a platform?  Options: A) below"
"Question: If it's not used for hair a round brush is an example of what"
"Question: His parents thought he was suffering from boredom, but the teen loved to lay"
"Question: At the picnic she was stuck eating hamburger, she was worried because she"
"Question: The electrode wouldn't spark, it turned out that the what hadn't been"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: What must a student in engineering do?  Options: A) answer question"
"Question: The teacher knew her students understood division, what was she hoping they would learn"
"Question: There were times where kids wanted to know a definition, so there was a"
"Question: Riding a bike for a long time can cause what?  Options: A"
"Question: What could happen to a cat other than wanting food? <pad><pad><pad>"
"Question: If you turn off the music in a room with no other noise that room"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: I want to use string to keep something from moving, how should I do"
"Question: Where would walk through a central passage to catch an elevator? <pad><pad>"
"Question: A potato is kept in the cellar, where is likely to be stored?"
"Question: What do people do when networking?  Options: A) build trust,"
"Question: Where can you store you spare linens near your socks?  Options:"
"Question: What do people do when they think too quickly?  Options: A)"
"Question: What is someone likely to want as a result of sex? <pad><pad>"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: To get clean clothes you to what to them?  Options: A)"
"Question: The person tried to reduce his weight with a shrink ray, but he got"
"Question: Christine couldn't be having a baby at her age, she thought to herself"
"Question: Joe plays a percussion instrument in something.  What might be play in?"
"Question: If I'm playing ball, I'm mostly trying to do what? "
"Question: What do the terms need to be in order to compete against someone? "
"Question: If you wanted to show off silk, what item could it be on?"
"Question: Where is known to be a wealth of information?  Options: A)"
"Question: I saw the receptionist carelessly toss my resume into the drawer, where"
"Question: What will happen if you inject water into yourself?  Options: A)"
"Question: Athletes soak in hot tubs to relieve what after playing baseball? "
"Question: What does a gambler do that causes him or her to be unhappy?"
"Question: There's one obvious reason to eat vegetables, they're good for you."
"Question: John was a bit think in the head, but he knew that he never"
"Question: Where would you hear a violin along side many string and wind instruments? "
"Question: What is the sun ultimately responsible for?  Options: A) earth warming"
"Question: Mandy lived in a train station.  She longed to see distant"
"Question: Joe is a  squirrel, which is an animal. He probably lives in"
"Question: Where could a personal ficus live?  Options: A) cabin in"
"Question: The shark actually counted as evidence, so where did the legal team bring it"
"Question: If the president wanted to ban snakes, where would he issue such a decree"
"Question: They were searching for rocks, so they missed the birds overhead as they stared"
"Question: Her son scraped his knee, she fetched a bottle of peroxide"
"Question: Where would you expect to find a dictionary along side other writings you can borrow"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: A statue that shoots liquid is called a what? <pad><pad><pad><pad>"
"Question: If you have a child who gets in trouble for being hyperactive you may"
"Question: John loved to paint houses.  How did he usually do it? "
"Question: When you wipe you feet on the door mat and walk through the door where"
"Question: What can you use to store a book while traveling?  Options: A"
"Question: Where would you find gazelle under a G?  Options: A"
"Question: Competing can lead to great highs, and also great lows when suffering what"
"Question: What blocks sunshine?  Options: A) summer, B) park,"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: Where would you store a pillow case that is not in use?  Options"
"Question: If the kitten was going to grow up to be a mouser like"
"Question: Where is that man buying silk from?  Options: A) space shuttle"
"Question: Where is a teacher likely to keep her clavichord?  Options"
"Question: Where are you if your bieifcase is going through an x-"
"Question: They were kissing each other good bye, they had no worries because their relationship"
"Question: Why would you take a bus to work?  Options: A) commute"
"Question: If you are hungry and going fishing?  Options: A) to see"
"Question: Dogs are very loyal if they have a good owner, they will always"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: For many males hair is a concern as they get older, it begins to"
"Question: What happens someone who is bad play poker?  Options: A) think"
"Question: John loved his snake.  It was the only ting he loved."
"Question: The fresh herbs, flowers, and vegetables will shrivel up if people don"
"Question: I picked from an apple tree outside of Fort Wayne, where am I?"
"Question: The janitor never had much to clean after a paper or two to pick"
"Question: If you're celebrating with too many cocktails what may you have in the morning"
"Question: Danny found an old film in a sealed what?  Options: A)"
"Question: Where are you likely to find much more than a drop of blood on the"
"Question: Where is the first place someone leaving the planet ends up?  Options:"
"Question: The town house went right to the curb, a slot effectively made a mailbox"
"Question: The architect thought that a mezzanine would look good, but the"
"Question: The person wasn't bothered by the weather, she had remembered to bring her"
"Question: If you want to learn about the world and understand the real reasons behind cultural"
"Question: What is the hopeful result of going to see a play?  Options:"
"Question: A person would join a trade school for finding information related to what? "
"Question: Joan was a baby, so there were many things she couldn't do,"
"Question: Where would you put some ham if you want to cook it?  Options"
"Question: Running errands with screaming kids will likely cause what?  Options: A"
"Question: Sam wasn't lying, but he left out important details. He was being"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: What kind of place has a leader?  Options: A) army,"
"Question: How is a person likely to communicatewith others?  Options: A)"
"Question: Where may you be if you're buying pork chops at a corner shop?"
"Question: Where is a well used toy car likely to be found?  Options:"
"Question: Where can fisherman store their rods when on a fishing trip? <pad>"
"Question: Danny is having fun just dancing and singing with his friends. He wasn't"
"Question: Where would you find an office worker gossiping with their colleagues?  Options"
"Question: Where would you put nails if they are already packaged?  Options: A"
"Question: What is a person who is good at sports considered?  Options: A"
"Question: The man acted ridiculous at the funeral, what attitude should he have taken?"
"Question: The pencil sharpener was broken in the classroom, where did the teacher recommend"
"Question: Where does a child likely sit at a desk?  Options: A)"
"Question: He was trying to procreate with many individuals, this led to a what"
"Question: What does playing soccer and winning lead to?  Options: A) excitement"
"Question: What attraction is sometimes so large that you need a map to find your way"
"Question: If my husband never helps me doing housework, what might that lead to"
"Question: The advertisement came in the form of a pop-up, where did it"
"Question: WHere do people live?  Options: A) apartment, B)"
"Question: People are what when you're a stranger?  Options: A) train"
"Question: The juror was quite bored and zoning out but wanted to convey he was"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: When a main artery is used to expedite travel what would it be referred"
"Question: If someone rules the universe of what are they in charge? <pad><pad>"
"Question: The butt was bare, and Sam couldn't stop staring at it. "
"Question: Where can many stores with clothing be found?  Options: A) shop"
"Question: After working on the car, what did it end up doing?  Options"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: Where is beer drank by people watching sticks and pucks?  Options:"
"Question: Where is there a telephone book in almost every room?  Options: A"
"Question: Where might you see a green field while driving?  Options: A)"
"Question: Some people got escorted out of the library, they were probably what? "
"Question: If there is a pond with trees around it, where it it likely located"
"Question: Blowfish require what specific thing to live?  Options: A) sea"
"Question: What is the least likely immediate side effect of eating hamburger? <pad>"
"Question: What would I be doing while going to work and walking?  Options:"
"Question: A showroom feature washers and refrigerators, where is this show"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: I am looking for honey right from the source, where should I look?"
"Question: Where are there likely to be a variety of flats to choose from? "
"Question: A weasel has a thin body and short legs to easier bur"
"Question: What can disease destroy?  Options: A) rug, B) third"
"Question: What does a person from Avalon live in?  Options: A) pain"
"Question: Where is one likely to find a fan for their stove? <pad><pad>"
"Question: Jodie felt a tightness in her chest. She was worried but"
"Question: If you're buying beer for a float trip what are you preparing to do"
"Question: Piece of land in Canada where you can find marmot?  Options:"
"Question: The surgeon's clients had begun to reduce, it seemed girls no longer want"
"Question: While waiting for this appointment, people often read magazines.  Options: A"
"Question: Where would you find a fox that is made up?  Options: A"
"Question: In basic training they build you up only to do what, all in hopes"
"Question: Billy saw a dog running from him and did his best to get away from"
"Question: John and Judy were parents.  They had two wonderful kids who weren't"
"Question: What are you playing if you're fiddling on a violin?  Options"
"Question: If somebody buys something and gives it to me as a free gift, what"
"Question: Why does someone flirt with many people at once?  Options: A)"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: Why would a band be performing when there are no people nearby? <pad>"
"Question: The dogs were protecting their own when they decided to what the bad man?"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: If you have a large satchel with you when you fly you'll be"
"Question: Where would someone keep their nylon leggings?  Options: A)"
"Question: If you spend a long time running after a ball how are you likely to"
"Question: When you need to rest it's often because you have been doing what?"
"Question: Boredom and hunger led to a wandering waste of time and a cart"
"Question: He was beginning to worry they wouldn't get on the ride before closing,"
"Question: This is an unavoidable physiological consequence of running.  <pad><pad>"
"Question: Sometimes a person has a fear of water or a dislike of being wet,"
"Question: Where would there be an auditorium with only a single person speaking? "
"Question: To get out of there the person had to keep on walking, they had"
"Question: What very large group of western citizens has bees everywhere?  Options: A"
"Question: Miss Grady took a stick from Bob because he was playing with it during"
"Question: How does a person begin reproducing?  Options: A) genetic mutation"
"Question: Joe and Jill didn't want their children to be sedentary.  They"
"Question: They were making sauerkraut, the instructor explained the liquid should"
"Question: From where would you normally take a cup when you're about to get a"
"Question: What are you using if there are speakers strapped on your ears?  Options"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: Where is likely to not just have a kosher restaurant?  Options: A"
"Question: The bald eagle flew from Mount St Helen's to the Puget Sound and"
"Question: Where could you get some knives if you are planning to bring them outside with"
"Question: How can people fulfill their own calorie requirements?  Options: A) compete"
"Question: What does a stove do to the place that it's in? <pad>"
"Question: What is the best way to begin going into trance? <pad><pad><pad>"
"Question: A computer user working on an important work assignment is located in what structure?"
"Question: The music was festive but why are the horses dancing in circles<pad><pad><pad>"
"Question: In the building where James worked there was a small mezzanine in"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: Where would you have a stove if you don't live in a detached dwelling"
"Question: What kind of place has a revolving door and has things to buy in it"
"Question: Where can books be read?  Options: A) cabinet, B)"
"Question: Where is seaweed usually found alive?  Options: A) ocean,"
"Question: If a lizard is fed by people every day, what has happened to it"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: If you wanted a license to catch crabs, what government office would you go"
"Question: What furniture will you normally find near a side chair?  Options: A"
"Question: Metal is used to make what?  Options: A) junkyard"
"Question: What is the word added to Manchester that signifies what county it is in?"
"Question: The program kept getting errors, the end user began to what? "
"Question: John knew that the sun produced a massive amount of energy in two forms."
"Question: Lawyers often talk in front of an audience where?  Options: A)"
"Question: James bought a new set of tire chains and put them somewhere he could find"
"Question: If I wanted to eat something that is made from plants and needs to be"
"Question: Ficus can be planted in a yard to make summer more bearable,"
"Question: Children's behavior is a direct reflection of their what?  Options: A"
"Question: Most people who are family like to greet each other with a what? "
"Question: John bought a new water hose.  But he found his old one near"
"Question: Where is a control room needed to prevent wide spread disaster? <pad><pad>"
"Question: Where do you keep your pizza slice before you eat it?  Options:"
"Question: Everybody was changing into costumes in the dressing room, it was almost time to"
"Question: The homeowner had to pay the property tax, but at the price of gas"
"Question: A thoroughfare meandered through fields and woods, where was it passing"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: Sean was leaving work and took the roadway that led to his what? "
"Question: What can you use to get a jellyfish?  Options: A)"
"Question: What has a shelf that does not allow you to see what is inside of"
"Question: What will likely happen after stabbing to death a person?  Options: A"
"Question: The boat passenger was explaining his fear of blowfish, but the captain figured"
"Question: Where could you find only a few office?  Options: A) skysc"
"Question: Where can I go to be a religious gentleman?  Options: A)"
"Question: I want to see a prepared slide up close, what would I use"
"Question: Where can you buy a magazine, paper or gum?  Options: A"
"Question: Where would you get some wood if you do not have any?  Options"
"Question: The pitcher felt stress and tension on the mound, what did he feel like"
"Question: What negative effect can competing in a chess game on a cold day have?"
"Question: Why is it hard for a young child to read a long book? "
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: What is likely to be found in a book that is not a foreword"
"Question: How many hours are in a day? <pad><pad><pad><pad><pad><pad>"
"Question: Why is religion so hard to understand?  Options: A) both positive"
"Question: The couple explained they were having trouble communicating, it seemed every conversation took"
"Question: What would a person need to do if his or her captain dies at sea"
"Question: What do children require to grow up healthy?  Options: A) need"
"Question: I live in a neighborhood, but where is the center of a community is"
"Question: The field general began to write out a letter to the king, he was"
"Question: What will you put on a pen to prevent it from drying out? "
"Question: After climbing the mountains, the explorer found the cave<pad><pad><pad>"
"Question: They dealt with combustible mixtures in their experiments, this is why they"
"Question: If someone mean wanted to insult somebody by calling them a fruit, where is"
"Question: Where would you get a toothpick if you do not have any? "
"Question: What would you be building if you designed a place for an annoying critter"
"Question: The man working in the attic swatted away a bee, but soon the"
"Question: What do you need to wear when hiking?  Options: A) cast"
"Question: What type of store would have lots of sports equipment?  Options: A"
"Question: The business man was promoted recently, to celebrate he went where to buy an"
"Question: How is a child eager to be going to play likely to get there?"
"Question: There's some new buying products designed to get you money if you have"
"Question: Where can you buy a replacement ax handle?  Options: A) bathroom"
"Question: Is that person acting as silly as a clown?  Options: A)"
"Question: Which group of states is Louisiana part of?  Options: A) deep"
"Question: Where would you put a plate immediately after eating from it?  Options:"
"Question: James couldn't get comfortable.  There was too much dirt.  He"
"Question: The rats were hiding in the house, where were they? <pad><pad>"
"Question: What do people do when they don't understand something?  Options: A"
"Question: James saw a kite flying in the sky.  He traced the string"
"Question: What rubber toy filled with helium will make a child happy?  Options:"
"Question: Where do people get beer after a bit of gambling?  Options: A"
"Question: What can happen to you when you are using television and it is not interesting"
"Question: The business men left the discussion in the dressing room, now they just wanted"
"Question: Where is a likely place for an ivy plant?  Options: A"
"Question: Where has the newest baseball stadium?  Options: A) phoenix"
"Question: What type of residence has a ground floor with a stoop? <pad>"
"Question: If the wood texture is not smooth it is what?  Options: A"
"Question: What might happen if someone is not losing weight?  Options: A)"
"Question: Billy lived in the capital of his country, then he moved.  Where"
"Question: Making a schedule was easy to pick, the major called for knowledge that required"
"Question: When getting in shape, this is something that does wonders?  Options:"
"Question: What could prevent a driving car from continuing to drive?  Options: A"
"Question: Where do you store a large container?  Options: A) supermarket,"
"Question: What is a person likely to experience after they stop being married to a mean"
"Question: Despite the large crowds, how did the depressed man feel?  Options:"
"Question: Where does a maid empty a trash can?  Options: A) bus"
"Question: The dog curled up for a nap, it was tuckered out because"
"Question: He used an umbrella while tanning, where was he likely? <pad>"
"Answer:   <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: The ancient seafaring Norse tribesman brought pelts of weasel aboard his"
"Question: What is the opposite of an area of elevation?  Options: A)"
"Question: What do singers need to do before a show?  Options: A)"
"Question: When a person with mental illness receives medication and therapy, what has happened?"
"Question: What type of feeling is performing for the first time likely to produce? "
"Question: If someone is found to be committing murder, what did they do to someone"
"Question: The computer was hooked up to the internet, what could it do as a"
"Question: The planet Mercury is unsuitable for human life or what? <pad><pad>"
"Question: Seeing idea become reality was a dream of hers for a long time, but"
"Question: A creek could be located in the opposite for the city which is called what"
"Question: Where off the eastern U.S. would you find an anemone"
"Question: Where are traveling clothes often kept?  Options: A) suitcase, B"
"Question: If one needed the bathroom they needed a key, to get it they had"
"Answer:   <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: The hardcovers were especially tall, so he removed a shelf on the"
"Question: If you're watching a comedy film what would you expect to hear from the"
"Question: What can eating lunch cause that is painful?  Options: A) headache"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: Eating is part of living, but your body doesn't use it all and"
"Question: Where are you if you've paid to get a pizza?  Options:"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: If you're seeking a connection for your laptop, what are you trying to"
"Question: The child didn't know the problems his mother was going through, all he"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: What can happen when you contemplate alone for a long time?  Options:"
"Question: The pioneer went to the general store for storage measures, what was he looking"
"Question: I was apprehensive to buy the expensive equipment to play a game with so"
"Question: What can a newspaper be used to do to an engagement?  Options:"
"Question: John needed a straight wire.  Unfortunately, this one had endured some abuse"
"Question: Metal is taken from what which is pulled from the ground?  Options:"
"Question: When not in use where on your property would you store you bucket? "
"Question: What does someone do to relax at night?  Options: A) find"
"Question: Where might the stapler be if I cannot find it?<pad><pad>"
"Question: Many homes in this country are built around a courtyard. Where is it?"
"Question: Sean was a wreck.  He  loved to build houses, but in"
"Question: What would be happening if you are pretending to be a police officer? "
"Question: Where would you buy a finely crafted writing instrument?  Options: A)"
"Question: The detective was finding information from witnesses, why would he do that? "
"Question: Joe found spiders in the place where he keeps his tools.  Where might"
"Question: While on the fan boat he thought he'd see swamps and gators"
"Question: Where are you likely to find a supermarket?  Options: A) buy"
"Question: Where would you need to use a lantern?  Options: A) grocery"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: Why would a woman kill a stranger she met in a dark alley? "
"Question: The baby was cranky, it needed to eat breakfast but refused to what"
"Question: What is made up of people?  is it<pad><pad><pad><pad><pad>"
"Question: He was afraid he would die from his cold, so he wisely decided to"
"Question: Where would you get a pen if you do not have one?  Options"
"Question: Why would a small dog pant if it's hot outside?  Options:"
"Question: She asked her little boy why, he replied that he didn't know and"
"Question: Where would you display a picture on a horizontal surface?  Options: A"
"Question: What skill is needed for riding a bike?  Options: A) wheels"
"Question: He looked at the field of pumps, all slowing churning oil out of"
"Question: The department to where vendors deliver goods for sale is called what?  Options"
"Question: Where is the worst place to be in a ticket office?  Options:"
"Question: Exercise is very good for you, for faster recovery you should always do what"
"Answer:   <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: Where would you acquire a wind instrument for you own use?  Options:"
"Question: Where would a person light alcohol on fire to observe the reaction?  Options"
"Question: If a storey contained a panoramic view, what kind of structure"
"Question: Where does lettuce arrive by large trucks?  Options: A) kitchen,"
"Question: Why do people who are dying receive social security payments?  Options: A"
"Question: What should I do with a jumping rope?  Options: A) fatigue"
"Question: What do geese do every fall in fields?  Options: A)"
"Question: I took my seat, the curtains drew back and I enjoyed the what?"
"Question: What should everyone do who doesn't want to fight anymore? <pad>"
"Question: Where is the ideal location for a post office?  Options: A)"
"Question: Where outside of a city would a squirrel live?  Options: A)"
"Question: You should watch out for snakes if floating down what African body of"
"Question: At the end of the day as he began to eat he paused and thanked"
"Question: To what do trees roots cling?  Options: A) yard, B"
"Question: What probably has a lot of dust in the back?  Options: A"
"Question: At the new comic store he found himself making friends, it was nice to"
"Question: The student explained he had a clue what neuroepithelium was and"
"Question: What could people do that involves talking?  Options: A) confession,"
"Question: If you're a child answering questions and an adult is asking them that adult"
"Question: He has lactose intolerant, but was eating dinner made of cheese,"
"Question: The teacher played on the upright piano, she was explaining the song to all"
"Question: When you get an F, you fail. If you get A's you"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: The ball was hit over a boundary and struck an audience member.  What"
"Question: What is someone operating a vehicle likely to be accused of after becoming ineb"
"Question: Where would you get jewelry if you do not have any?  Options:"
"Question: What is a philosopher waiting for to eventually gain through his studies?  Options"
"Answer:   <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: She loved spending money at the thrift store on knickknacks,"
"Question: I listened to lecture intensely, what is my goal?  Options: A"
"Question: If a person is using a computer to talk to their granddaughter, what might"
"Question: Joe was there to meet a large number of people.  As he filed"
"Question: John wanted scatter his wife's remains in a lake in the wilderness. "
"Question: Many towns and cities have trash cans where on sidewalks?  Options: A"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: What happens when airplane engines cut off and are unable to be restarted in"
"Question: Where would you be concerned about finding a cavity?  Options: A)"
"Question: Human beings learn about current events from what print item?  Options: A"
"<pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: He wanted lodging in the actual what, so that he was already where he"
"Question: If I am suffering from boredom, and I want to see something beautiful,"
"Question: The goal was to hit the target, but a projectile ball can't hit"
"Question: Where is a good place to set a cup of coffee while relaxing? "
"Question: If a fried egg was runny and there was no toast to sop"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: Before lifting weights he liked to warm up on the squash court, he really"
"Question: What will happen to animals after eating food?  Options: A) bite"
"Question: If I wanted to grow plants, where could I put a lot of dirt"
"Question: What does a person often feel about someone judging them guilty?  Options:"
"Question: A town between two mountains is located in a what?  Options: A"
"Question: James need to use a toilet but there were no public ones in sight."
"Question: Why did the heavy metal band need electricity at the stadium?  Options:"
"Question: What is a person looking for when completing puzzles or riddles?  Options"
"Question: If someone was making breakfast, they'd probably put two slices of bread in"
"Question: His house was a mess, he began doing housework to get what<pad>"
"Question: Where would a corpse be covered by a blanket?  Options: A)"
"Question: The man  tried to break the glass in order to make his escape in"
"Question: The trucker plopped on the bench with a sense of relief, where"
"Question: What is part of a republic like the USA?  Options: A)"
"Question: Where do you keep extra clothing on a hike?  Options: A)"
"Question: What could an apple tree do?  Options: A) new hamp"
"Question: What very cold area in the east can a crab be found?  Options"
"Question: The chef wanted to perfect his craft, what did he do?  Options"
"Question: She wanted a kitten and puppy so why did she only get the puppy?"
"Question: There was no shade for Jenny.  She was forced to lie there exposed"
"Question: What could happen to you after you are cleaning house for a long time?"
"Question: What is someone doing when scheduling when to go to party?  Options:"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: What do people feel after having sex that requires them to shower?  Options"
"Question: The vet found malignant tumors on the animals, what is their likely fate"
"Question: What is the thing that is agitated in your head when kissing?  Options"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: Where do you keep a pail in your house?  Options: A"
"Question: what is printed with ink and distributed daily?  Options: A) fountain"
"Question: What are people likely to do when an unexpected decent outcome occurs?  Options"
"<pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: The company sent off many purchases, they used recycled cardboard as their what?"
"Question: Why might a person be known as a liar? <pad><pad><pad><pad>"
"Question: The child was politely waiting for dessert, he was eventually rewarded for his what"
"Question: The man was giving assistance to a pan handler in the streets, how did"
"Question: What do you call the caretakers of a child? <pad><pad>"
"Question: Where would you run in to a niece you only see every one and a"
"Question: Working on the elaborate task was taxing, it require extreme what?"
"Question: What may you have after awaking after a night of heavy drinking? "
"Question: What uses a ribbon to put words on paper?  Options: A)"
"Question: Where are sheep likely to live?  Options: A) school, B"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: While walking the student needed to store his writing insturment away, where"
"Question: Who watches a play in an auditorium? <pad><pad><pad><pad><pad>"
"Question: What is a possible outcome for committing murder?  Options: A) problems"
"Question: where is a good place to obtain new soap?  Options: A)"
"Question: What do people do for food?  Options: A) talk to each"
"Question: There was many a bottle to choose from behind the cashier?  Options"
"Question: They had to know where to go, they got on the national highway after"
"Question: What do professors primarily do?  Options: A) master physics, B"
"Question: Where do you throw a ball at pins?  Options: A) bowling"
"Question: What might you need to do cleaning?  Options: A) sing a"
"Question: If i were to spit a lot without noticing i may have extra what?"
"Question: If student got a list of supplies from class like paper and pencils,"
"Question: Why do young people swallow semen<pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: Sally was standing in queue.  The line was very, very slow."
"Question: What is the animal trying to accomplish?  Options: A) sand trap"
"Question: James and Holly went dancing together. As they danced, he  pressed himself"
"Question: If a house has a subscription, what likely shows up in the driveway every"
"Question: What does a person do when they feel dirty?  Options: A)"
"Question: After the weight cut he was worried about his energy levels, but this was"
"Question: what does a person do to stay healthy?  Options: A) fever"
"Question: Who is the guard for?   Options: A) man post,"
"Question: If a person stutters when he experiences anxiety or excitement, he'll have"
"Question: Where can you keep letter opener when it likely to be needed soon? "
"Question: Danny found that the carpet did not,match the drapes, which"
"Question: What do people need to do to change their lives?  Options: A"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: Someone who had a very bad flight might be given a trip in this to"
"Question: Nature can be good and bad for the person who walks, what are some"
"Question: Jim decided to lose weight.  He thought that exercise is the best way"
"Question: Nature creates more beautiful structures than those that are what?  Options: A"
"Question: The water in clouds turn in to what when it gets cold?  Options"
"Question: What southern U.S. state is know for having many swamps?"
"Question: When going to sleep what happens to your body?  Options: A)"
"Question: Where is a monkey likely to enjoy being?  Options: A) banana"
"Question: What is a form of anaerobic exercising?  Options: A)"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: Where would you put a container can after you buy it?  Options:"
"Question: Where did you meet your best friend since Kindergarten?  Options:"
"Question: James was below the balloon.  He watched it rise.  What direction"
"Question: John and Tim like playing. It makes them what? <pad><pad><pad>"
"Question: What could happen if someone is seeing new presents at a birthday party? "
"Question: Joe's cat smelled something delicious and jumped into this, causing him to panic"
"Question: Why would a person put flowers in a room with dirty gym?  Options"
"Question: The table wasn't level.  some parts were higher and some were lower"
"Question: The person signed up for home insurance, what is he seeking?  Options"
"Question: James know that committing murder was wrong, but he thought that he could get"
"Question: How can someone die from eating hamburger?  Options: A) gas"
"Question: Where would using a boat not require navigation skills?  Options: A)"
"Question: What does a self assured person often do?  Options: A) acknowledgment"
"Question: He was very outgoing, for him making friends was no big deal"
"Question: What do you feel when giving assistance to the needy?  Options: A"
"Question: Paul wants carrots and doesn't need to drive anywhere. He gets them from"
"Question: He was a sloppy eater, so where did he leave a mess? "
"Question: What does every person want?  Options: A) life partner, B"
"Question: If a small flying animal picks up a string, where are they taking it"
"Question: He had no issue committing perjury, he had a what that he would get"
"Question: What could go to a tennis court?  Options: A) desert,"
"Question: What could you use to fill a cup and then drink from it? "
"Question: The two played video games all night in the living room, he enjoyed"
"Question: The weasel ran up away from danger, somebody joked only our first president"
"Question: If you were looking for a blowfish, you wouldn't look on dry"
"Question: George checked the rotor of the Apache, which wasn't powered by internal combustion"
"Question: The poker dealer spread the flop of cards across the what?  Options"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: Where would you put a dollar if you want to go to a store and"
"Question: What room is likely to have a sideboard on the counter? <pad>"
"Question: What is unlikely to get bugs on its windshield due to bugs' inability to"
"Question: What mall store sells jeans for a decent price?  Options: A)"
"Question: Where can a bath towel be borrowed?  Options: A) cupboard"
"Question: Why do people stop caring about their problems?  Options: A) no"
"Question: John rode on the plain until it reached the ocean and couldn't go any"
"Question: They were never going to be big actors, but they all had passion for"
"Question: Where would you use a folding chair but not store one? <pad><pad>"
"Question: If you spend a long time shopping in uncomfortable shoes, you might develop what"
"Question: What does impeachment mean for the president?  Options: A) vote,"
"Question: Noble citizen of the Roman empire believed those born with lower status were what to"
"Question: Spraining an ankle while playing baseball will cause what?  Options: A"
"Question: John was traveling to a new city and took time to check out a business"
"Question: If you have a condo in a Wisconsin city known for beer, where are"
"Question: Where is hard to read likely to be?  Options: A) fridge"
"Question: How does someone go about buying beer?  Options: A) have no"
"Question: If there is gum on your shoe where did it likely come from? "
"Question: If a person isn't able to pay their bills what must they do?"
"Question: What is main benefit to exercising?  Options: A) losing weight,"
"Question: Steve thought that it was possible, but he was what?  Options:"
"Question: What region of a west coast U.S. city would you find a"
"Question: What is a tactic used to interfere with learning about science?  Options:"
"Question: What do people usually feel when falling in love?  Options: A)"
"Question: The tiger was stuck in what animal prison where he got lazy and fat?"
"Question: What do parents tell a child to do on the weekend? <pad><pad>"
"Question: Why are dogs often known as man's best friend?  Options: A"
"Question: Where can you buy a two wheel transportation machine?  Options: A)"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: Where do you buy condoms?  Options: A) supermarket, B)"
"Question: What animal is known for being a follower? What animal<pad><pad>"
"Question: The soldier was told to get to the rendezvous point, for there he"
"Question: If you want to kill someone you can do what to them with a gun"
"Question: The hostess greeted the employees to the program, she then led them to"
"Question: Where is a likely place to store unused soap?  Options: A)"
"Question: Loss of someone you love can cause what kind of feeling in your heart?"
"Question: Where in your home would you keep a ballpoint pen when not in use"
"Question: James was someone who was caught in his own delusions.  To him,"
"Question: He wanted to live somewhere were every yard was uniform in size and landscaping"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: What was the man encouraged to do after he expressed his anger violently? "
"Question: Where can a student learn to play a triangle?  Options: A)"
"Question: What do you need to do to use television if it is already turned on"
"Question: The guys had a regular poker game, rather than going to the movies"
"Question: When you stroke a dogs fur what have you done?  Options: A"
"Question: Dan fell off a bar stool.  He did this because he was"
"Question: The wood was still rough to the touch, what did the woodworker have"
"Question: The chief saw his entire tribe wiped out, he was a leader with a"
"Question: The flower grew tall to compete for sunlight, what did its neighbor do?"
"Question: If while driving to work another car makes a careless maneuver, what emotion might"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: Where would you find the sharpest parts of a triangle?  Options:"
"Question: How might a automobile get off a freeway?  Options: A) exit"
"Question: What does going to bed with your spouse for sex lead to?  Options"
"Question: What would it be if they get a surprising show over and over? "
"Question: Sally thought that competing wasn't worth the risk. If she pushed more"
"Question: John is sitting in a toilet stall in a bathroom, outside he can hear"
"Question: What event might one buy tickets for seats?  Options: A) park"
"Question: The merchant wanted to open in a high-traffic space, where did"
"Question: The newlyweds began copulating their marriage, they wanted many what?"
"Question: How does a planet usually move around the sun?  Options: A)"
"Answer:   <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: What emotion leads to punching? <pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: They kept doing things the same, she suggested they also try doing things what"
"Question: Where could you find a shark before it was caught?  Options: A"
"Question: Where is one likely to find poker chips?  Options: A) supermarket"
"Question: Dance can be elegant and specific, or you can just have fun and what"
"Question: Where can one obtain a bass fiddle?  Options: A) jazz"
"Question: Why does having a disability sometimes making academic tasks hard for a person? "
"Question: What is the purpose of playing games for children?  Options: A)"
"Question: If for some reason you were to start killing people, what would you be"
"Question: If someone laughs after surprising them they have a good sense of what? "
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: What is likely to have a better school cafeteria?  Options: A)"
"Question: When someone has little knowledge and is judging someone they are considered what? "
"Question: She wanted to get in shape, but she couldn't stay focused on the"
"Question: When you do something and have fun, its something you?  Options:"
"Question: What is a salesman responsible to do at work?  Options: A)"
"Question: How does going jogging generally affect one's self esteem?  Options:"
"Question: Where would you find people standing in a line outside?  Options: A"
"Question: If you are committing perjury you have done what while under oath?  Options"
"Question: Where can you find the meaning of \"ficus\"?<pad><pad><pad><pad>"
"Question: When are people buying products more?  Options: A) debt, B"
"Question: The buildings were intended to not have residential kitchens in them, what were they"
"Question: Animals come in all types, some fly thanks to their wings, some don"
"Question: The child felt like it was all pretend, he didn't understand what?"
"Question: Where is a lake likely to be glacial?  Options: A)"
"Question: They needed grape juice for their party, they went to buy it and other"
"Question: Why do some people get passports and go to different locations?  Options:"
"Question: Where do apples form on an apple tree?  Options: A) south"
"Question: Where areas are there likely to be many nightclubs?  Options: A"
"Question: What can machines do that humans cannot?  Options: A) fail to"
"Question: What does someone stop doing when being dead?  Options: A) moving"
"Question: The place where my linen closet is really needs repainting a light color"
"Question: Punk rock music is an important part of what action sport?  Options:"
"Question: Where might a mouse be found to make it country?  Options: A"
"Question: Where is a bird likely to make it's home?  Options: A"
"Question: When a person suffers from hunger early in the day what do they do?"
"Question: How would you express information if you do not have a pen or pencil?"
"Question: What does everyone feel of monsters?  Options: A) looking for love"
"Question: Why does someone want to examine thing closely?  Options: A) buy"
"Question: What does................................................................................................................................................................................................................................<pad><pad><pad><pad><pad><pad>"
"Question: Where would your hear a bass clarinet along side other wood wind instruments?"
"Question: What is the opposite of a little of something?  Options: A)"
"Question: The princess was pure, the evil wizard wished to do what to her<pad>"
"Question: The piece of paper was worth a lot of money, it was an old"
"Question: During the winter hunt he could hear every motion in the woods, this was"
"Question: If a car-less person want to listen to talk radio in private,"
"Question: Billy was an astronaut.  When he looked at the world from space,"
"Question: Where is a good place to have a fireplace in a house? <pad>"
"Question: If you own a cat where is the last place you'd want to find"
"Question: Where would you find a kosher deli along side a number of different places"
"Question: What do you do when you're going to market?  Options: A"
"Question: She feared that she had cancer, but upon discovering truth that she hadn't"
"Question: What is the feeling of one having fun?  Options: A) smiling"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: Christians believe you will go to heaven if you're what?  Options:"
"Question: James loved to surf but he wasn't good at it. He would always"
"Question: Sarah gave her brother a key to her home.  While she was gone"
"Question: When did mammoth's live?  Options: A) boscage,"
"Question: After killing people, the murderer went to church after feeling what? <pad>"
"Question: What might result in an unsuccessful suicide attempt?  Options: A) die"
"Question: What can happen if you are buying products that someone else does not want you"
"Question: The child was getting many gifts for his birthday, his father reminded him to"
"Question: Bob stands in the grass surrounded by trees and nature, where is Bob?"
"Question: Bart entered his horse into the contest.  Where did he do this?"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: All the power tools like the drill used for fixing cars made for a very"
"Question: Applying for a job can make someone feel what sort of emotion, even"
"Question: A farmer sees a weasel in the woods, where is the farmer?"
"Question: He picked up the perfect pebble, he planned to skip it across"
"Question: Traveling from new place to new place is likely to be what? "
"Question: Turkey only has a small northern part of their country located in part of the"
"Question: Where might someone store a reusable shopping bag?  Options: A) supermarket"
"Question: How could you have fun by yourself with no one around you?  Options"
"Question: The potato might be the official vegetable of what?  Options: A)"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: What type of fruit is easily broken in to sections?  Options: A"
"Question: Marathoners feel fatigued after running twenty six miles, but some that have"
"Question: Billy liked driving cars.  He was good at it.  But he"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: Copulating with the wrong partner may be ill advised, many diseases can be"
"Question: What do audiences clap for? <pad><pad><pad><pad><pad><pad><pad>"
"Question: Where would you get a balalaika if you do not have one?"
"Question: Hoping for a beautiful day, what did the clouds do that disappointed everyone"
"Question: What type of demands to the unions need to be making to go off strike"
"Question: The landscaper was carefully arching stones together, he was creating an elaborate"
"Question: John was not happy with his marriage. He and his wife drifted apart."
"Question: The poor girls needed a light to see, what was the relationship between that"
"Question: Where would you find a ticket booth and see a concert?  Options:"
"Question: Who is not famous for a superhighway with no speed limit? "
"Question: The low trickle of water revealed a stone, where was the stone found?"
"Question: Where is the closest place from where you could borrow salt?  Options:"
"Answer:   <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: A meteor travels through galaxies which are a part of what?  Options:"
"Answer:   <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: She had an interest in the man, what did she want to do with"
"Question: Where is a drug kept in a home bathroom?  Options: A)"
"Question: When cooking sheep meat a lot of people might want to be well? "
"Question: Where would you sit in a chair while working toward an advanced degree? "
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: A good interview after applying for a job may cause you to feel what?"
"Question: Computers have allowed everybody to answer questions they have quickly, but still we"
"Question: There was a long cottage somewhere.  It was overgrown, there was"
"Question: Where is knight always portrayed as a hero?  Options: A) middle"
"Question: James is carrying a duffel bag with him because he doesn't have"
"Question: What would you need if you want to smoke?  Options: A)"
"Question: James decided that competing was the right choice.   Not competing has a"
"Question: What could you use to get to some airplanes?  Options: A)"
"Question: What happens when driving?  Options: A) lack of fuel, B"
"Question: What are our bodies doing after having food?  Options: A) falling"
"Question: Why would one try to avoid work?  Options: A) making money"
"Question: What do you do in order to fly in airplane? <pad><pad><pad>"
"Question: What is another name for the color of the fur of a dog with light"
"Question: Sally was bored because she didn't like the junk that was on what?"
"Question: The lion sensed his competitor was timid, so what attitude did the lion take"
"Question: John felt a snake slither over him as he rested.  He was"
"Question: Where can you find a place to eat in an urban area close to local"
"Question: You have to a lot of thinking while studying a new subject, but it"
"Question: How will you communicate if you are far away from who you want to communicate"
"Question: Why would you not trust your friends after chatting with friends?  Options:"
"Question: He came from old money and had a fortune, but he made new money"
"Question: Animals make up a large part of the<pad><pad><pad><pad><pad><pad><pad>"
"Question: At a shop what can you buy to put your spare unused things? "
"Question: A person with digestion issues eats a meat-filled breakfast, what does he"
"Question: What is a prisoner sentenced to do?  Options: A) scape"
"Question: Jesse  enjoyed remembering the past because he helped him understand it.  And"
"Question: David watched some nesting birds using his binoculars while on vacation. "
"Question: Where would you find many varieties of plants including a rosebush?  Options"
"Question: If I did not have a rosebush, where would I get one?"
"Answer:  <pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"
"Question: What are cats often known for?  Options: A) whiskers,"
"Question: As he looked out the window, he knew the landing was happening soon,"
"Question: Where can you find a dogs house?  Options: A) found outside"
"Question: Tweed is a rare fabric in modern clothing, what brand should I look"
"Question: If you really wanted a grape, where would you go to get it?"
"Question: What would you do to a rock when climb up a cliff?  Options"
"Question: His compressor needed a new hose, where did he go?  Options:"
"Question: The man closed his eyes as the music played, what effect did the music"
"Question: Setting up framing, truss and beam are some of the first steps in"
"Answer:   "
