"store<pad><pad>"
"kill animals<pad>"
"store<pad>"
"restaurant"
"farmland<pad><pad>"
"<pad><pad>"
"great cup of coffee"
"pass water<pad><pad>"
"money bank"
"singing"
"record store"
"peace<pad>"
"stockyard<pad>"
"walk"
"being entertained<pad>"
"hotel<pad>"
"stay busy"
"sharp sword"
"brain<pad>"
"office<pad>"
"floor<pad><pad><pad>"
"painting<pad><pad>"
"indestroyable"
"rest area<pad><pad>"
"ineffectual"
"have children<pad>"
"out of doors"
"new perspective<pad>"
"new job<pad>"
"lie<pad>"
"eat<pad>"
"subway station"
"slow down<pad>"
"stand in line"
"feel better<pad>"
"train<pad><pad>"
"street<pad>"
"bakery"
"cup<pad>"
"front door"
"rock<pad><pad>"
"pay bills<pad>"
"chicken"
"painting<pad>"
"beer<pad><pad>"
"employment<pad><pad>"
"cash<pad><pad>"
"symphony orchestra"
"telephone book"
"fishmongers"
"dress shop<pad>"
"death<pad><pad>"
"tiredness"
"play tag<pad>"
"friendship<pad>"
"classroom<pad>"
"big town"
"fungrounds"
"cold<pad>"
"go somewhere"
"public house"
"school<pad><pad><pad>"
"fish market<pad><pad>"
"pet shops<pad><pad>"
"bus depot<pad>"
"cook dinner<pad>"
"confidence<pad><pad>"
"shower stall"
"house<pad><pad>"
"europe<pad>"
"learn new<pad>"
"office supply store"
"clean up"
"checkers"
"round<pad>"
"depression"
"windowill<pad>"
"white mice<pad>"
"freedom<pad><pad>"
"go to jail"
"walking<pad>"
"winch<pad>"
"farm land"
"pocket<pad><pad>"
"red lobster"
"hospital<pad>"
"cook food"
"remembering"
"research laboratory<pad>"
"sleeping in"
"fall down<pad>"
"airport<pad>"
"wash dishes<pad>"
"music room<pad>"
"metropolis<pad>"
"understand"
"fun<pad><pad>"
"lazybutt"
"play poker<pad>"
"hotel<pad>"
"hired help"
"barge<pad>"
"open mind<pad>"
"workflow<pad>"
"police brutality"
"wear out"
"city<pad>"
"grandfather"
"night sky<pad>"
"<pad>"
"relaxation"
"dime store"
"living room<pad>"
"froggy"
"park<pad><pad>"
"music store<pad>"
"board ship<pad><pad>"
"street corner"
"house<pad><pad><pad>"
"store<pad><pad><pad>"
"hockey game"
"bigger<pad>"
"state facts<pad>"
"under water<pad>"
"world news<pad>"
"celebrating"
"apply for job"
"floor<pad>"
"procrastinate"
"city<pad><pad>"
"play baseball<pad>"
"drive in movie"
"<pad><pad>"
"cleanliness<pad><pad>"
"race<pad><pad><pad>"
"scotland"
"employment<pad><pad>"
"getting hurt<pad>"
"make happy"
"great plains"
""
"time test"
"park<pad>"
"closed room"
"power down<pad><pad>"
"ticket machine<pad><pad>"
"practice<pad><pad><pad>"
"movement"
"grope<pad><pad>"
"reading<pad><pad><pad>"
"feel good about yourself"
"sweat<pad><pad>"
"office building"
"computer<pad>"
"bodybuilder"
"dirt"
"food<pad>"
"mine<pad>"
"ask"
"wash dishes"
"table<pad><pad>"
"airport<pad>"
"basketball alley<pad>"
"new york"
"music store<pad>"
"living room"
"splats<pad>"
"pet store<pad>"
"address<pad><pad>"
"passing<pad>"
"shapeless"
"pass time<pad>"
"store<pad>"
"bathroom"
"bowl"
"walk slowly"
"mask<pad><pad>"
"death<pad><pad>"
"laziness"
"eating<pad><pad>"
"band<pad><pad><pad>"
"ground<pad><pad>"
"play room<pad><pad>"
"chicken coop"
"protection<pad><pad><pad>"
"rest<pad><pad><pad>"
"sweating<pad><pad>"
"barrel"
"transport"
"meetings<pad>"
"office complex<pad>"
"school<pad><pad>"
"go fast<pad><pad>"
"sleep<pad>"
"turn right<pad><pad>"
"floribama"
"park<pad>"
"land"
"dancing"
"attack<pad>"
"library<pad>"
"office<pad>"
"hot flashes"
"light source"
"bank savings<pad>"
"glasses"
"<pad>"
"painting<pad>"
"park"
"growth<pad>"
"contract<pad>"
"balance"
"night out"
"police station"
"play games"
"go skiing"
"calligraphy"
"city<pad><pad>"
"gas<pad><pad><pad>"
"feel better<pad><pad>"
"cupboard"
"act<pad>"
"speed up"
"dustbin"
"cooking"
"bank roll<pad>"
"zoo"
"living"
"pain"
"conference<pad>"
"free money"
" yawn<pad>"
"outside<pad>"
"deep<pad>"
"empty"
"throw up"
"go fast"
"concert venue"
"hutch"
"creek"
"cage"
"have fun<pad>"
"no home<pad>"
"petted<pad>"
"pants<pad>"
"sleep<pad>"
"cross street"
"healthy<pad>"
"center<pad><pad><pad>"
"intertidal zone"
"smoke<pad><pad>"
"play cards<pad><pad>"
"potato<pad>"
"living room<pad>"
"hotdog<pad>"
"michigan"
"getting paid"
"cleanliness<pad>"
"<pad>"
"new car<pad>"
"airport<pad><pad>"
"bathroom<pad><pad>"
"national park"
"punch<pad><pad>"
"live in"
"desktop<pad>"
"closed room"
"stay home"
"honey"
"pain<pad>"
"sweat"
"write down"
"store information<pad>"
"judgment<pad>"
"colds<pad>"
"surface"
"container<pad>"
"open book"
"communication<pad>"
"dirty dishes"
"office building<pad>"
"cash register<pad>"
"debt"
"race track<pad>"
"learn new things"
"watch tv<pad>"
"set papers"
"dwarf"
"pollution"
"stomach"
"communication<pad>"
"aquarium"
"talk to each other"
"pool hall<pad><pad><pad>"
"overstocking<pad><pad>"
"pain<pad><pad><pad><pad>"
"cabinet<pad>"
"home<pad><pad><pad>"
"learn to swim<pad>"
"family room"
"fly in airplane<pad><pad>"
"city<pad><pad><pad><pad>"
"bus depot<pad><pad><pad>"
"good natured ribbing"
"shopping mall"
"grammar<pad>"
"front<pad><pad>"
"radio station<pad>"
"school room"
"fun<pad>"
"parking"
"secure<pad>"
"burrow"
"make tools"
"back yard"
"ground<pad>"
"machine<pad>"
"park<pad><pad>"
"maryland"
"play chess<pad>"
"play sports"
"store<pad>"
"death"
"sleep<pad>"
"table<pad><pad><pad>"
"nuclear weapons"
"house<pad><pad><pad>"
"space<pad><pad><pad>"
"band<pad><pad><pad>"
"death<pad><pad><pad>"
"walking<pad><pad>"
"fabric store"
"superabundance"
"pain<pad><pad>"
"bus stop"
"hospital<pad><pad><pad>"
"death<pad><pad><pad>"
"new england<pad>"
"procrastination"
"fall<pad><pad><pad>"
"language<pad><pad>"
"rain<pad><pad>"
"table<pad><pad>"
"arid regions"
"school<pad><pad><pad>"
"get away from"
"stand alone<pad><pad>"
"death<pad><pad><pad>"
"different standards"
"dress herself"
"store<pad>"
"new experience"
"sculptured"
"store<pad><pad>"
"forest<pad><pad>"
"sleep<pad>"
"desktop<pad><pad>"
"martorell"
"toy soldier"
"airport<pad>"
"table<pad>"
"cross a river"
"bottle<pad>"
"rain forest"
"jocose"
"dark cave<pad>"
"revenge<pad>"
"head injuries<pad>"
"get laid<pad>"
"pet shop<pad>"
"music room<pad>"
"marriage"
"stars<pad>"
"reception"
" keg"
""
"fall asleep"
"distance"
"office<pad>"
"food<pad>"
"relaxation"
"car description<pad>"
"farm yard<pad>"
"sleeping in"
"navigation<pad>"
"personal key"
"cat"
"concerto<pad>"
"restaurant<pad>"
"sexually<pad><pad>"
"new hampshire"
"painting<pad><pad>"
"store<pad><pad>"
"dreamworker<pad>"
"new friends"
"good balance<pad>"
"meetings"
"office<pad>"
"run away"
"sandpaper"
"living room<pad>"
"<pad>"
"bed"
"texas<pad>"
"longplay<pad>"
"storage bag"
"dress nice<pad>"
"dress himself<pad>"
"park<pad><pad>"
"swimming pool"
"warm house<pad>"
"exhaustion"
"go somewhere<pad>"
"store<pad><pad>"
"graduate<pad><pad>"
"wearable items"
"ground level"
"office<pad>"
"office<pad>"
"home<pad>"
"city<pad>"
"tool kit"
"touch everything"
"building<pad>"
"get away<pad>"
"stagnant"
"shop<pad>"
"cooking<pad>"
"treat<pad>"
"music room<pad>"
"fall asleep<pad>"
"gazelle"
"run<pad><pad>"
"caged in<pad>"
"beaver"
"conversation<pad>"
"pain<pad>"
"grand canyon"
"strip mall"
"give gift"
"baby shower<pad>"
"bank teller"
"print"
"surprised"
"hug<pad>"
"truck stop"
"sports<pad>"
"learning<pad><pad>"
"sleeping"
"shower<pad><pad>"
"parking lot<pad>"
"cargo hold<pad>"
"breakfast"
"kitchen"
"hotel"
"eat cake"
"cell phone<pad>"
"procrastinate"
"agitate<pad>"
"suburban<pad>"
"c, D) russia"
"matrimony<pad><pad><pad><pad><pad>"
"direct traffic<pad><pad><pad><pad><pad><pad>"
"work<pad><pad><pad><pad><pad><pad>"
"hunting"
"office building<pad>"
"death<pad>"
"business sector<pad>"
"desk"
"canada"
"music store"
"bathtub"
"kissing"
"clean room<pad>"
"small talk<pad>"
"apple tree<pad>"
"airport<pad><pad>"
"open doors<pad><pad>"
"falling down<pad>"
"louisiana"
"mice"
"fatigue"
"book<pad>"
"death<pad>"
"chowder<pad>"
"competence"
"park<pad><pad>"
"fall<pad><pad>"
"recycling center"
"living room<pad>"
"fall down<pad>"
"shop<pad>"
"fall down"
"dairy farm<pad>"
"get rich<pad><pad>"
"postgraduate<pad><pad>"
"airport"
"pick up"
"rain forest"
"building<pad>"
"action"
"travel<pad>"
"table"
" seaweed"
"store<pad><pad>"
"dust<pad><pad>"
"brainstem"
"library<pad><pad>"
"spectating<pad><pad>"
"california<pad>"
"damage<pad><pad><pad>"
"make others happy too"
"public monument<pad>"
"Neighborhood"
"prison<pad><pad>"
"roll over"
"building<pad>"
"building<pad>"
"graduate<pad>"
"gong"
"group together<pad>"
"dance<pad>"
"war<pad><pad>"
"standing in line"
"car"
"relax"
"wind instrument"
"library<pad>"
"get wet<pad>"
"library<pad><pad>"
"restaurant"
"car shop<pad>"
"future<pad>"
"petting zoo"
"play games<pad>"
"play chess<pad>"
"music store"
"school<pad>"
"death<pad>"
"energy"
"hot dogs"
"fresh fruit"
"office<pad>"
"painting"
"help<pad><pad>"
"church<pad><pad>"
"eating hamburger"
"store<pad><pad>"
"car<pad><pad>"
"cold storage<pad>"
"small town<pad>"
"baseball"
"concert hall<pad>"
"brush<pad><pad>"
"meet interesting people"
"food poisoning<pad>"
"electricity<pad><pad>"
"tax office<pad><pad>"
"count<pad><pad><pad>"
"multiplication"
"table<pad><pad>"
"falling down"
"thirsty"
"silence<pad>"
"fast food restaurants"
"wind<pad><pad>"
"public building<pad>"
"store<pad>"
"belief"
"home<pad><pad>"
"pay bills<pad>"
"procreation<pad>"
"communication<pad>"
"clean clothes"
"grow<pad>"
"adult"
"musical instrument"
"win<pad>"
"cheat<pad><pad>"
"expensive clothing<pad>"
"library<pad><pad>"
"office desk<pad>"
"wet clothes"
"pain<pad>"
"double winnings"
"good for<pad>"
"free flowing<pad>"
"string quartet"
"light"
"big city<pad>"
"forest<pad><pad>"
"california"
"shark<pad><pad>"
"new mexico"
"ground<pad><pad><pad>"
"peroxide<pad><pad>"
"library<pad><pad><pad>"
"sweat"
"central park<pad><pad>"
"park<pad><pad><pad>"
"painting<pad>"
"school<pad><pad>"
"pocket<pad><pad>"
"gazelle"
"sweat<pad>"
"moon<pad>"
"fan<pad><pad>"
"bedding store"
"living room"
"bar<pad>"
"music room<pad>"
"airport<pad>"
"trust"
"travel"
"catch"
"attack"
"plant seeds"
"grow in ear<pad>"
"<pad><pad>"
"pet<pad><pad><pad>"
"drive to the nearest pool"
"apple tree<pad><pad><pad>"
"house<pad><pad><pad><pad>"
"hangover<pad><pad><pad>"
"film<pad>"
"blood bank"
"orbit<pad>"
"front door"
"school<pad>"
"warm coat"
"open mind"
"jobless"
"learning<pad><pad>"
"baby"
"rigerator<pad>"
"tiredness"
"relax"
"death<pad>"
"country<pad>"
"open mouth"
"town<pad>"
"toy car"
"fishing camp"
"fun<pad><pad>"
"baby shower"
"store<pad>"
"lazy"
"funeral"
"library<pad>"
"office building"
"kiss<pad>"
""
"truck stop"
"park<pad><pad>"
"store<pad><pad>"
"bus depot"
"train<pad>"
""
"blowfish"
"travel<pad>"
"text book"
"covered"
"shopping"
"go fast"
"caregiver<pad>"
"beer<pad><pad><pad>"
"library<pad><pad><pad>"
"landscape"
"<pad>"
"bathroom"
"sea water<pad>"
"health problems<pad>"
"walking<pad>"
"car dealership<pad>"
"san diego"
"honey<pad>"
"city<pad><pad><pad>"
"chicken coop"
"building<pad><pad><pad>"
"pain<pad><pad><pad>"
"hot room"
"concert"
"have fun"
"united states"
"expand<pad><pad>"
"magazines<pad><pad>"
"natural habitat"
"destroy<pad><pad><pad>"
"dog trapped<pad>"
"parenting"
"string instrument<pad>"
"cost status<pad>"
"dance"
"broadcast"
"blaring"
"attack<pad>"
"grain<pad><pad>"
"airport<pad>"
"car"
"sweating<pad>"
"sleep<pad>"
"play cards<pad><pad>"
"hair<pad><pad><pad>"
"falling down"
"get wet<pad><pad><pad>"
"crowd<pad><pad><pad>"
"rollerskate"
"trash can<pad><pad>"
"office<pad>"
"kiss<pad>"
"play sports"
"container<pad>"
"water fountain"
"conference<pad>"
"cool off"
"dining"
"bald eagle"
"kitchen<pad>"
"feed themselves<pad>"
"hot stove<pad>"
"sleep"
"internet cafe"
"night club"
"classroom"
"make bread<pad>"
"living room<pad>"
"new york"
"table<pad><pad>"
"water<pad>"
"garden"
"depress"
"catch crabs"
"office<pad><pad><pad>"
"metal fabrication shop<pad>"
"lancashire"
"write code<pad><pad>"
"life on earth"
"office building<pad>"
"tire chains"
"plant<pad><pad>"
"covered porch<pad>"
"play ball<pad>"
"hug<pad>"
"new water hose"
"nuclear plant"
"table<pad>"
"train<pad>"
"board windows"
"city<pad><pad>"
"living room<pad>"
"city<pad><pad>"
"jellyfish"
"bookcase<pad>"
"<pad>"
"piranhas"
"city<pad><pad>"
"church<pad>"
"camera<pad>"
"gum"
"boat<pad>"
"relief"
"sweat<pad>"
"book<pad>"
"cool off<pad>"
"afterword<pad><pad>"
"night<pad><pad>"
"religion<pad><pad>"
"conversation"
"cross road"
"fast food"
"street"
"email<pad>"
"pencil<pad>"
"<pad>"
"fire extinguisher"
"store<pad><pad>"
"mouth<pad>"
"fly away"
"soft drink"
"shins"
"school<pad><pad>"
"jewelery"
"play<pad>"
"debt<pad>"
"water fountain<pad><pad>"
"mental unhinged"
"united states<pad><pad>"
"table<pad><pad>"
"street<pad><pad><pad>"
"basement<pad><pad>"
"believe in god"
"kite<pad><pad>"
"learn<pad>"
"gambling"
"turn off"
"house<pad>"
"windowsill<pad>"
"san francisco"
"office building<pad>"
"solid<pad><pad>"
"beauty"
"jail"
"class<pad>"
"jogging"
"smoke"
"store<pad>"
"grief"
"alone"
"street<pad>"
"walk"
"beach"
"dark<pad>"
""
"depression"
"clear throats"
"treatment<pad>"
"action<pad><pad><pad><pad>"
"death<pad><pad><pad><pad>"
"believe in god<pad>"
"mercury"
"celebrate<pad>"
"creek<pad>"
"florida"
"drawer<pad>"
"rest area"
"sunrise"
"bookcase"
"being entertained"
"heartburn<pad><pad>"
"cape canaveral"
"defecating<pad>"
"oven<pad><pad><pad>"
"telephone<pad>"
"connection<pad><pad>"
"learn<pad><pad>"
"go to movies"
"sleep<pad><pad>"
"baking soda"
"play golf<pad><pad>"
"educate<pad><pad>"
"straight<pad>"
"car<pad>"
"<pad>"
"check mail"
"desktop<pad>"
"office complex"
"build<pad>"
"play<pad>"
"stationery store"
"get answers<pad>"
"toolbox<pad>"
"bald eagle"
"get supplies"
"dark place"
"street<pad>"
"passcode"
"baby"
"classroom"
"never want"
"pocket<pad>"
"dog show"
""
"painting"
""
"street"
"pick up"
"ticket office"
"stretch"
"turn around"
"music store"
"bar<pad>"
"storey"
"farm<pad>"
"rejuvenation"
"jumping rope"
"<pad>"
"auditorium"
"shoes<pad>"
"center of town"
"forest<pad>"
"tree<pad><pad>"
"make food<pad>"
"surface of earth"
"library<pad><pad>"
"friendship"
"blind<pad><pad>"
"sing<pad><pad>"
"providing<pad>"
"feel better<pad>"
"music store<pad>"
"pass<pad><pad>"
"exfoliation"
"basketball<pad>"
"car accidents<pad>"
"safe deposit box"
"job<pad><pad>"
"knit<pad><pad>"
"clutter<pad>"
"concentrate"
"computer<pad><pad>"
"convention center"
"dead body<pad>"
"hotel<pad>"
"give away<pad>"
"<pad>"
"brushed tooth"
"read newspapers"
"sea water<pad>"
"hotel<pad>"
"watch film<pad>"
"flintlock"
"office<pad><pad>"
"house<pad><pad>"
"provocative<pad>"
"swimming pool"
"pass water<pad>"
"street<pad><pad>"
"judgment<pad>"
"hospital"
"bathroom<pad>"
"electricity"
"pass grade"
"toaster"
"clean house"
"hospital<pad>"
"train<pad>"
"bus stop"
"democracy<pad>"
"packet"
"bloom"
"fresh water"
"cook dinner"
"soft<pad><pad>"
"sunshine<pad>"
"clean house<pad>"
"meet new people"
"solid nucleus"
"shower"
"death<pad>"
"kissing"
"ground"
"pail"
"print"
"pain<pad>"
"garden"
"recycling"
"home<pad>"
"dessert"
"out of pocket"
"birth<pad><pad>"
"family reunion"
"concentration"
"pain<pad><pad>"
"bath"
"farm<pad>"
"hot room<pad>"
"pocket<pad>"
"city<pad>"
"prison"
"washing<pad>"
"kill animals"
"gas station<pad>"
"national highway<pad>"
"school students<pad>"
"throw a ball"
"cleanliness<pad>"
"spittle<pad>"
"store<pad><pad>"
"sexually"
"move forward"
"leave home"
"dance"
"street<pad>"
"wash themselves"
"sleep"
"food<pad>"
"prisoner<pad>"
"dance<pad>"
"stationery store"
"brothel<pad>"
"pay bills"
"school"
"travelling"
"nature<pad>"
"fastfood<pad><pad>"
"city<pad>"
"teardrops"
"swamp<pad><pad>"
"sleep<pad><pad>"
"research laboratory<pad>"
"fall down<pad>"
"fotograph"
"store<pad>"
"internet cafe"
"aloft"
"burn<pad>"
"new presents"
"living room"
"plant themselves"
"unbalanced"
"living well"
"death<pad><pad>"
"gas<pad><pad>"
"navigation skills"
"trust himself<pad>"
"friendship<pad>"
"<pad>"
"carrot"
"table"
"money<pad>"
"park<pad>"
"lying"
"park<pad>"
"water fountain<pad><pad>"
"home<pad><pad><pad>"
"chicken coop"
"sea water"
"electric motor"
"play games"
"store<pad>"
"pocket<pad>"
"living room"
"scooter"
"bedroom<pad>"
"bath towel<pad><pad>"
"learn from each other"
"sandplain<pad><pad>"
"show<pad><pad><pad>"
"<pad><pad><pad>"
"shoes<pad><pad>"
"board room"
"humili<pad><pad>"
"pain<pad><pad>"
"chair<pad><pad>"
"residential area"
"bed<pad><pad>"
"beer<pad><pad>"
"water fountain<pad>"
"make more money"
"sweat<pad>"
"can do"
"downtown<pad><pad>"
"repetition<pad>"
"pain<pad><pad><pad>"
"kill<pad><pad><pad>"
"clean room<pad><pad>"
"dog<pad><pad><pad>"
"train station"
"space<pad>"
"store<pad>"
"follow"
"fight enemy"
"shoot<pad>"
"work room"
"store"
"painful"
"office desk<pad>"
"work to advantage"
"parking garage"
"bordello"
"fight"
"music class"
"plug in"
"fun<pad>"
"petted<pad>"
"bar stool<pad>"
"petrify"
"followers<pad>"
"open<pad>"
"getting there<pad>"
"food<pad>"
"three sides"
"exit ramp"
"sleepiness"
"fight<pad>"
"death<pad>"
"public place<pad>"
"auditorium"
"store<pad>"
"baby<pad>"
"outerspace"
"cough<pad>"
"hit<pad>"
"expensive<pad>"
"marine museum"
"bar<pad>"
"fall down"
"group band"
"disability"
"learning<pad>"
"prison sentence"
"fun<pad>"
"playground<pad>"
"polytechnic"
"experience<pad>"
"excercise"
"pay for"
"sellers<pad><pad>"
"jogging<pad><pad>"
"bus depot<pad><pad>"
"lie"
"libary"
"trading"
"small city"
"head<pad><pad>"
"daydreams"
"new york<pad>"
"food store<pad><pad>"
"travel<pad><pad>"
"new york"
"drink<pad>"
"fly<pad><pad>"
"deadworks"
"house<pad>"
"listen"
"computer lab"
"tree<pad>"
"food<pad>"
"write down<pad>"
"monster"
"buy"
"alcohol"
"school band<pad>"
"big<pad>"
"dirty<pad>"
"copy machine"
"stillness"
"talk radio"
"square"
"living room"
"home"
"food court"
"travel"
"pain<pad>"
"fun"
""
"change of color"
"wet<pad>"
"open doors<pad>"
"prehistory<pad>"
"religion"
"death<pad>"
"pain<pad>"
""
"rest area<pad>"
"state fair"
"billow<pad><pad>"
"repair shop<pad><pad>"
"failure<pad><pad>"
"chicken coop"
"playground<pad><pad>"
"relocation<pad><pad>"
"provide meat<pad>"
"store<pad><pad><pad>"
"fun<pad><pad><pad>"
"chicken"
"sky<pad><pad>"
"band<pad><pad>"
"passing out"
"death<pad>"
"cold"
"sex"
"show<pad>"
"music store"
"clouds<pad>"
"union<pad><pad>"
"ground<pad>"
"disenchanted"
"light<pad><pad>"
"ticket booth<pad>"
"superhighway"
"water bed<pad>"
"shaker<pad>"
"infiniverse"
"space<pad><pad>"
"bullying<pad>"
"play game"
"drug cabinet"
"done<pad>"
"living room"
"farm land<pad>"
"employment<pad><pad>"
"produce sound"
"railroad"
"castle<pad><pad><pad>"
"duffel bag"
"smoking<pad><pad>"
"competing<pad><pad>"
"car"
"tires turning"
"gas"
"work<pad><pad>"
"gas<pad><pad>"
"game"
"caddy<pad>"
"aggressive<pad><pad>"
"sleeping<pad>"
"downtown"
"weight<pad><pad>"
"talk to people"
"smoking<pad><pad>"
"real estate"
"environment<pad><pad><pad>"
"container<pad><pad><pad>"
"heartburn<pad>"
"dream of freedom"
"writing down<pad>"
"nesting birds"
"beautiful garden"
"ground<pad><pad>"
"trust himself<pad>"
"four legs<pad>"
"airport"
"four legs"
"brown"
"farm"
"fall<pad><pad>"
"new hose<pad>"
"music<pad>"
"new construction"
"computer store"
